(() => {
  'use strict';
  if(window.SARSocialUI)return;
  const EVENTS=['BALANCE_FEEDBACK','BUFF_REACTION','NERF_REACTION','META_SHIFT','META_OPINION','WEAPON_ENTERED_TOP_3','WEAPON_LEFT_TOP_3','NEW_WEAPON','FAVORITE_WEAPON_CHANGED','PERSONAL_WEAPON_BREAKOUT','PERSONAL_WEAPON_COLLAPSE','HOT_STREAK','SLUMP','SEASON_RANK_UP','SEASON_RANK_DOWN','SEASON_LEAD','SEASON_LOST_LEAD','SEASON_FINAL_3_DAYS','SEASON_FINAL_DAY','SEASON_WIN','SEASON_LOSS','CAREER_500_KILLS','CAREER_1000_KILLS','CAREER_2500_KILLS','CAREER_BEST_GAME','RIVAL_BEAT_BOT','BOT_BEAT_RIVAL','TOURNAMENT_ANNOUNCEMENT','TOURNAMENT_INVITE','TOURNAMENT_ELIMINATION','TOURNAMENT_WIN','MAP_FEEDBACK','PLAYER_MESSAGE'];
  const MOODS=['neutral','confident','happy','angry','frustrated','hyped','sarcastic','concerned','disappointed','amused','focused'],CATEGORIES=['balance','meta','season','rivalry','tournament','career','personal','weapon','map'];
  const state={ai:null,data:{messages:[]},signature:'',tabs:'',jobs:new Map(),outputs:new Map(),threads:new Map(),drafts:new Map(),lastAccount:null,epoch:0,inboxSeen:null,refreshPromise:null,edit:null,lab:{bot:'',event:'BALANCE_FEEDBACK',context:'{}'},panels:{},feedback:new Map(),settingsSignature:'',toolOpen:{},temperatureDraft:null,pendingPrefs:new Map(),preferenceRevision:0};
  const safe=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const api=(path,options)=>window.SARCloud.api(path,options);
  const accountId=()=>window.SARCloud?.state.account?.id||null;
  const activeView=()=>document.querySelector('#modal.visible #modalContent')?.dataset.view;
  const date=value=>Number.isFinite(Number(value))?new Date(Number(value)).toLocaleString():'—';
  const current=epoch=>epoch===state.epoch&&accountId()===state.lastAccount;
  let phoneView='home',phoneModule,phoneSearch='',phoneReturnView='inbox';
  const messageViews={inbox:{search:'',scroll:0},contacts:{search:'',scroll:0}};
  function rememberMessages(){const v=messageViews[phoneView];if(v){v.search=phoneSearch;v.scroll=document.querySelector('.inbox-threads')?.scrollTop??v.scroll;}}
  const appTitles={scores:'LIVE SCORES',spectate:'SPECTATE',bots:'BOT LEADERBOARD',botmeta:'BOT WEAPON META'};
  const owner=()=>window.SARCloud?.state.account?.username==='noahhicks719';
  const phoneIcons={messages:'<path d="M5 4h14v11H9l-4 4V4Z"/><path d="M9 8h6M9 11h4"/>',contacts:'<circle cx="12" cy="8" r="3"/><path d="M5 20v-2a7 7 0 0 1 14 0v2M4 3h16"/>'};
  const phoneIcon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${phoneIcons[name]||phoneIcons.messages}</svg>`;
  const unreadCount=()=>state.data.unread??state.data.unreadCount??state.data.messages.filter(row=>row.direction==='bot'&&!row.readAt).length;
  const initials=name=>String(name||'?').slice(0,2).toUpperCase();
  function shortDate(value){const at=new Date(Number(value)),now=new Date();if(!Number.isFinite(at.getTime()))return '';return at.toDateString()===now.toDateString()?at.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):at.toLocaleDateString([],{month:'short',day:'numeric'});}
  function phoneScreen(body){return `<div class="phone-status"><span>${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span><span class="phone-signal" aria-label="Private bot network"><i></i><i></i><i></i><i></i></span></div><nav class="phone-navigation" aria-label="Phone navigation"><button data-phone-action="back" aria-label="Back" ${phoneView==='home'?'disabled':''}>‹ <span>${phoneView==='conversation'?(phoneReturnView==='contacts'?'Contacts':'Messages'):'Back'}</span></button><span>${phoneView==='home'?'SKIRMISH':phoneView==='conversation'?'CONVERSATION':phoneView==='contacts'?'CONTACTS':appTitles[phoneView]||'MESSAGES'}</span><button data-phone-action="home" aria-label="Phone home">⌂</button></nav><div class="phone-app">${body}</div><div class="phone-home-indicator" aria-hidden="true"></div>`;}
  function phoneFrame(body){return `<div class="phone-device"><canvas id="phoneModel" width="440" height="828" aria-label="Phone device"></canvas><section class="phone-screen" data-phone-screen="${phoneView}">${phoneScreen(body)}</section></div>`;}
  function paintPhone(){const c=document.getElementById('phoneModel');if(!c)return;phoneModule??=import('./inspect-25d.mjs');phoneModule.then(module=>module.paintInspection(c,{kind:'phone'})).catch(()=>{const g=c.getContext('2d');g?.clearRect(0,0,c.width,c.height);});}
  function modal(html,view){const panel=document.querySelector('#modal'),content=document.querySelector('#modalContent');if(!panel||!content)return;const phone=view==='messages'||view==='phone'||view==='phone-app',screen=phone&&content.querySelector?.('.phone-screen');if(screen){screen.dataset.phoneScreen=phoneView;screen.innerHTML=phoneScreen(html);}else content.innerHTML=phone?phoneFrame(html):html;content.dataset.view=view;document.querySelector('#modal .modal')?.classList.remove('meta-wide');panel.classList.add('visible');window.SAR?.preparePanel?.();window.SARFullscreen?.setCombatActive(false);if(phone&&!screen)paintPhone();}
  function say(text){const out=document.querySelector('#socialStatus');if(out)out.textContent=text;}
  function statusText(){return ({CONNECTED:'Connected',CHECKING:'Connecting',OLLAMA_OFFLINE:'Reconnecting',MODEL_NOT_INSTALLED:'Service unavailable',MODEL_ERROR:'Reply unavailable'})[state.ai?.status||'CHECKING']||'Reconnecting';}
  function queueText(){const q=state.ai?.queue||{};return q.active||q.pending?`${q.active||0} replying · ${q.pending||0} waiting`:q.paused?'Messaging paused':'Private bot network';}
  function bots(){const source=state.data.bots;return Array.isArray(source)?source:Object.values(source||window.SAR?.getProfiles?.()||{});}
  function botId(bot){return bot?.botId||bot?.id;}
  function preferences(){const saved=state.ai?.preferences||state.data.preferences||{botMessages:true,botInitiated:true,playerReplies:true,developerMode:false};return {...saved,...Object.fromEntries([...state.pendingPrefs].map(([key,change])=>[key,change.value]))};}
  function draftKey(){return 'sar.social.replyDrafts.'+state.lastAccount;}
  function persistDrafts(){if(!state.lastAccount)return;try{window.localStorage?.setItem(draftKey(),JSON.stringify(Object.fromEntries([...state.drafts].filter(([,text])=>text).slice(-50))));}catch(_){}}
  function captureInputs(){
    const reply=document.querySelector('#socialReply');if(reply?.dataset.botId&&reply.dataset.accountId===String(state.lastAccount)){state.drafts.set(reply.dataset.botId,reply.value);persistDrafts();}
    const context=document.querySelector('#aiLabContext');if(context)state.lab={bot:document.querySelector('#aiLabBot')?.value||state.lab.bot,event:document.querySelector('#aiLabEvent')?.value||state.lab.event,context:context.value};
    const subject=document.querySelector('#aiEditSubject');if(subject&&state.edit)state.edit={...state.edit,subject:subject.value,body:document.querySelector('#aiEditBody')?.value||'',mood:document.querySelector('#aiEditMood')?.value||state.edit.mood,category:document.querySelector('#aiEditCategory')?.value||state.edit.category};
    for(const detail of document.querySelectorAll('[data-ai-tool]'))state.toolOpen[detail.dataset.aiTool]=detail.open;
  }
  function syncAccount(){
    const id=accountId();if(id===state.lastAccount)return state.epoch;
    captureInputs();state.lastAccount=id;state.epoch++;state.inboxSeen=null;state.inboxNewest=0;state.ai=null;state.data={messages:[]};state.signature='';state.settingsSignature='';state.jobs.clear();state.outputs.clear();state.threads.clear();state.drafts.clear();state.feedback.clear();state.edit=null;state.panels={};state.refreshPromise=null;state.lab={bot:'',event:'BALANCE_FEEDBACK',context:'{}'};state.toolOpen={};state.temperatureDraft=null;state.pendingPrefs.clear();state.preferenceRevision=0;phoneSearch='';phoneReturnView='inbox';
    for(const view of Object.values(messageViews)){view.search='';view.scroll=0;}
    if(window.SARCloud?.state)window.SARCloud.state.messageThread=null;
    if(id)try{const saved=JSON.parse(window.localStorage?.getItem(draftKey())||'{}');for(const [bot,text] of Object.entries(saved))if(typeof text==='string')state.drafts.set(bot,text.slice(0,500));}catch(_){}
    const view=activeView();if(view==='messages'||view==='ai')modal(`<div class="eyebrow">BOT NETWORK</div><h2>${view==='messages'?'MESSAGES':'MESSAGING'}</h2><p class="analytics-note">${id?'Loading this account…':'Sign into the account server to use persistent messages.'}</p>`,view);
    updateBadge();return state.epoch;
  }
  function updateBadge(){const count=state.data.unread??state.data.unreadCount??state.data.messages.filter(m=>m.direction==='bot'&&!m.readAt).length;for(const el of document.querySelectorAll('[data-action="messages"]')){el.textContent=count?`PHONE ●${count}`:'PHONE';el.setAttribute('aria-label',count?`Messages, ${count} unread`:'Messages');}}
  function updateStatus(){for(const el of document.querySelectorAll('[data-ai-status]'))el.textContent=statusText();for(const el of document.querySelectorAll('[data-ai-queue]'))el.textContent=queueText();const error=document.querySelector('#aiConnectionError');if(error)error.textContent=owner()?state.ai?.error||'':state.ai?.error?'Messaging service unavailable. Check connection.':'';}
  function feedback(row){
    if(!owner()||!preferences().developerMode||!row.generationId)return '';state.outputs.set(row.generationId,{subject:row.subject||'Bot message',body:row.body,mood:row.mood||'neutral',category:row.category||'personal',wantsReply:row.wantsReply??true,certainty:row.certainty??.5});
    return `<div class="message-feedback"><span>TRAINING</span><button data-social-action="feedback" data-generation="${safe(row.generationId)}" data-rating="GOOD">GOOD</button><button data-social-action="feedback" data-generation="${safe(row.generationId)}" data-rating="BAD">BAD</button><button data-social-action="edit" data-generation="${safe(row.generationId)}">EDIT</button><span data-feedback-result="${safe(row.generationId)}">${safe(state.feedback.get(row.generationId)||'')}</span></div>`;
  }
  function messageCard(row,name,thread=false){return `<article class="message-card ${row.direction==='player'?'message-sent':''}" data-message-id="${safe(row.id)}"><div class="message-meta"><strong>${row.direction==='player'?'You':safe(name||row.botName||row.botId)}</strong><time title="${safe(date(row.createdAt))}">${safe(thread?shortDate(row.createdAt):date(row.createdAt))}</time></div>${row.subject?`<h4>${safe(row.subject)}</h4>`:''}<p>${safe(row.body)}</p>${feedback(row)}${String(row.id).startsWith('lab-')?'':`<button class="message-delete" data-message-delete="${safe(row.id)}" title="Delete this message" aria-label="Delete message from ${row.direction==='player'?'you':safe(name||row.botName||row.botId)}">Delete</button>`}</article>`;}
  function selectedBot(){const cloud=window.SARCloud.state,roster=bots(),ids=new Set(roster.map(botId));if(!ids.has(cloud.messageThread))cloud.messageThread=state.data.messages[0]?.botId||botId(roster[0]);return cloud.messageThread;}
  function threadState(id){if(!state.threads.has(id))state.threads.set(id,{messages:[],nextCursor:null,loaded:false,pending:null,error:'',loadedAt:0,latestId:null,visibleCount:100});return state.threads.get(id);}
  function threadRows(id){const entry=state.threads.get(id);return entry?.loaded?entry.messages:state.data.messages.filter(m=>m.botId===id);}
  function messageSignature(){const id=window.SARCloud?.state.messageThread;return JSON.stringify([id,state.data.messages,threadRows(id),state.threads.get(id)?.nextCursor,preferences()]);}
  async function refreshThread(id,older=false,force=false){
    if(!id)return;const epoch=syncAccount(),entry=threadState(id);if(entry.pending)return entry.pending;if(older&&!entry.nextCursor)return;
    const latest=state.data.messages.find(row=>row.botId===id);if(!older&&!force&&entry.loaded&&Date.now()-entry.loadedAt<15000&&(!latest||latest.id===entry.latestId))return;
    const before=older?entry.nextCursor:null;
    let pending;pending=(async()=>{try{
      const result=await api('/messages/thread/'+encodeURIComponent(id)+(before?'?before='+encodeURIComponent(before):''));if(!current(epoch))return;
      const incoming=Array.isArray(result.messages)?result.messages:[],existing=entry.messages;
      // A fresh first page replaces its old time range; already loaded older pages remain available.
      const boundary=incoming[incoming.length-1];
      const retained=older?existing:entry.loaded&&incoming.length>=100?existing.filter(row=>Number(row.createdAt)<Number(boundary.createdAt)||Number(row.createdAt)===Number(boundary.createdAt)&&String(row.id)<String(boundary.id)):[];
      entry.messages=[...new Map([...retained,...incoming].map(row=>[row.id,row])).values()].sort((a,b)=>b.createdAt-a.createdAt||String(b.id).localeCompare(String(a.id)));
      if(older||!entry.loaded||incoming.length<100)entry.nextCursor=result.nextCursor||null;
      entry.loaded=true;entry.error='';entry.loadedAt=Date.now();entry.latestId=entry.messages[0]?.id;if(older)entry.visibleCount+=100;
    }catch(error){if(current(epoch))entry.error=error.message;}finally{if(entry.pending===pending)entry.pending=null;}})();
    entry.pending=pending;return pending;
  }
  function restoreEdit(){
    const edit=state.edit,host=document.querySelector('#socialEditHost');if(!edit||!host)return;
    host.innerHTML=`<div class="message-compose ai-correction"><strong>PREFERRED CORRECTION</strong><label>SUBJECT<input id="aiEditSubject" maxlength="100" value="${safe(edit.subject)}"></label><label>BODY<textarea id="aiEditBody" maxlength="900" rows="4">${safe(edit.body)}</textarea></label><div class="ai-lab-fields"><label>MOOD<select id="aiEditMood">${MOODS.map(v=>`<option ${edit.mood===v?'selected':''}>${v}</option>`).join('')}</select></label><label>CATEGORY<select id="aiEditCategory">${CATEGORIES.map(v=>`<option ${edit.category===v?'selected':''}>${v}</option>`).join('')}</select></label></div><button data-social-action="save-edit" data-generation="${safe(edit.id)}">SAVE CORRECTION</button><button data-social-action="cancel-edit">CANCEL</button></div>`;
  }
  function renderMessages(){
    captureInputs();const rows=state.data.messages||[],roster=bots(),byId=Object.fromEntries(roster.map(b=>[botId(b),b])),selected=selectedBot(),bot=byId[selected],entry=threadState(selected),inThread=phoneView==='conversation',thread=inThread?threadRows(selected).slice(0,entry.visibleCount).sort((a,b)=>a.createdAt-b.createdAt||String(a.id).localeCompare(String(b.id))):[];
    const oldReply=document.querySelector('#socialReply'),focused=document.activeElement?.id,selectionStart=document.activeElement?.selectionStart,selectionEnd=document.activeElement?.selectionEnd,list=document.querySelector('.message-list'),sameThread=oldReply?.dataset.botId===selected,scroll=sameThread?list?.scrollTop||0:0,atBottom=!sameThread||!list||list.scrollHeight-list.scrollTop-list.clientHeight<40,oldThreads=document.querySelector('.inbox-threads'),threadScroll=oldThreads?.scrollTop||0;
    const summaries=new Map();for(const row of rows){const summary=summaries.get(row.botId)||{latest:row,unread:0};if(row.direction==='bot'&&!row.readAt)summary.unread++;summaries.set(row.botId,summary);}
    const contacts=phoneView==='contacts',query=phoneSearch.trim().toLowerCase(),ids=roster.map(botId).filter(id=>(contacts||summaries.has(id)||threadRows(id).length)&&(!query||`${byId[id].name} ${byId[id].playstyle||''}`.toLowerCase().includes(query))).sort((a,b)=>contacts?byId[a].name.localeCompare(byId[b].name):(summaries.get(b)?.latest?.createdAt||threadRows(b)[0]?.createdAt||0)-(summaries.get(a)?.latest?.createdAt||threadRows(a)[0]?.createdAt||0)||byId[a].name.localeCompare(byId[b].name));
    const form=bot?.form??window.SAR?.getUniverse?.()?.bots?.[bot?.name]?.recentForm,playstyle=bot?.playstyle||bot?.socialProfile?.playstyle||bot?.archetype||'Competitor';
    const listHtml=`<header class="phone-app-heading"><div><h2>${contacts?'Contacts':'Messages'}</h2><p>${contacts?roster.length+' competitors':unreadCount()?unreadCount()+' unread messages':'Your conversations'}</p></div><button data-social-action="refresh" class="phone-refresh" aria-label="Refresh inbox" title="Refresh inbox">↻</button></header><nav class="phone-app-tabs" aria-label="Messaging views"><button data-phone-action="messages" ${!contacts?'aria-current="page"':''}>Inbox</button><button data-phone-action="contacts" ${contacts?'aria-current="page"':''}>Contacts</button></nav><label class="phone-search"><span aria-hidden="true">⌕</span><input id="phoneContactSearch" type="search" maxlength="50" placeholder="${contacts?'Find a competitor':'Search conversations'}" aria-label="${contacts?'Find a competitor':'Search conversations'}" value="${safe(phoneSearch)}"></label><div class="inbox-layout"><aside class="inbox-threads" aria-label="${contacts?'Contacts':'Conversations'}">${ids.map(id=>{const person=byId[id],summary=summaries.get(id),latest=summary?.latest||threadRows(id)[0],unread=summary?.unread||0;return `<button data-message-thread="${safe(id)}" class="phone-contact ${unread?'unread':''}" aria-label="${safe(person.name)}${unread?', '+unread+' unread messages':''}"><span class="phone-avatar" aria-hidden="true">${safe(initials(person.name))}</span><span class="phone-contact-copy"><span class="phone-contact-top"><strong>${safe(person.name)}</strong>${!contacts&&latest?`<time title="${safe(date(latest.createdAt))}">${safe(shortDate(latest.createdAt))}</time>`:contacts?`<span class="contact-power">${Number(person.power)||0} PWR</span>`:''}</span><small>${safe(contacts?person.playstyle||'Competitor':latest?(latest.direction==='player'?'You: ':'')+latest.body.slice(0,100):'Start a conversation')}</small></span>${unread?`<span class="phone-unread">${unread>99?'99+':unread}</span>`:'<span class="phone-contact-chevron" aria-hidden="true">›</span>'}</button>`;}).join('')||`<div class="phone-empty"><span aria-hidden="true">${phoneIcon('messages')}</span><h3>${query?'No matches':state.inboxSeen===null?'Loading your inbox…':'Your inbox is clear'}</h3><p>${query?'Try a different name.':state.inboxSeen===null?'Your saved conversations will appear here.':'Start a conversation with someone on the circuit.'}</p>${!query&&state.inboxSeen!==null?'<button data-phone-action="contacts">Open Contacts</button>':''}</div>`}</aside></div><div class="phone-network"><span data-ai-status>${safe(statusText())}</span><span data-ai-queue>${safe(queueText())}</span></div>`;
    let previousDay='';const threadHtml=thread.map(row=>{const day=new Date(Number(row.createdAt)).toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'}),separator=day!==previousDay?`<div class="message-day">${safe(day)}</div>`:'';previousDay=day;return separator+messageCard(row,bot?.name,true);}).join('');
    const conversationHtml=`<section class="inbox-conversation"><header class="inbox-bot"><span class="phone-avatar" aria-hidden="true">${safe(initials(bot?.name))}</span><div><strong>${safe(bot?.name||'Contact')}</strong><small>${safe(playstyle)}</small></div>${bot?`<button data-bot-profile="${safe(bot.name)}" aria-label="View ${safe(bot.name)} profile">Profile ↗</button>`:''}</header><div class="phone-contact-facts"><span>${Number(bot?.power)||0} Power</span><span>Form ${Number.isFinite(form)?Number(form).toFixed(1):'—'}</span>${bot?.seasonRank?`<span>Season #${bot.seasonRank}</span>`:''}</div><div class="message-list" role="log" aria-label="Conversation with ${safe(bot?.name||'contact')}">${(entry.nextCursor||entry.messages.length>entry.visibleCount)?`<button class="message-older" data-social-action="older" ${entry.pending?'disabled':''}>LOAD OLDER MESSAGES</button>`:''}${entry.error?`<p class="analytics-note" role="status">${safe(entry.error)}</p>`:''}${threadHtml||`<div class="phone-empty"><h3>${!entry.loaded&&!entry.error?'Loading conversation…':'Say hello to '+safe(bot?.name||'this competitor')}</h3><p>${!entry.loaded&&!entry.error?'Your saved messages will appear here.':'Ask about their loadout, the latest patch or the next tournament.'}</p></div>`}</div><div id="socialEditHost"></div><div class="message-compose"><label><span class="phone-compose-label">Message ${safe(bot?.name||'contact')} <span id="phoneDraftCount">${(state.drafts.get(selected)||'').length}/500</span></span><textarea id="socialReply" data-bot-id="${safe(selected)}" data-account-id="${safe(state.lastAccount)}" rows="2" maxlength="500" placeholder="Write a message…" ${!preferences().playerReplies?'disabled':''}>${safe(state.drafts.get(selected)||'')}</textarea></label><button data-social-action="send" aria-label="Send message" title="Send message (Ctrl+Enter)" ${!selected||!preferences().playerReplies||!preferences().botMessages?'disabled':''}>↑</button><span id="socialStatus" role="status">${preferences().botMessages?'': 'Messaging is switched off in Settings.'}</span></div></section>`;
    modal(inThread?conversationHtml:listHtml,'messages');restoreEdit();const newList=document.querySelector('.message-list');if(newList)newList.scrollTop=atBottom?newList.scrollHeight:scroll;const newThreads=document.querySelector('.inbox-threads');if(newThreads)newThreads.scrollTop=threadScroll;
    if(focused&&(sameThread||focused==='phoneContactSearch')){const el=document.getElementById(focused);el?.focus();if(typeof el?.setSelectionRange==='function'&&typeof selectionStart==='number')el.setSelectionRange(selectionStart,selectionEnd??selectionStart);}
    state.signature=messageSignature();const epoch=state.epoch,unread=thread.filter(m=>m.direction==='bot'&&!m.readAt);
    if(inThread&&unread.length)Promise.allSettled(unread.map(m=>api('/messages/'+encodeURIComponent(m.id)+'/read',{method:'POST',body:'{}'}))).then(results=>{if(!current(epoch))return;let marked=0;results.forEach((result,index)=>{if(result.status==='fulfilled'){const id=unread[index].id;for(const row of [...state.data.messages,...entry.messages])if(row.id===id)row.readAt=Date.now();marked++;}});state.data.unread=Math.max(0,(state.data.unread??state.data.unreadCount??unread.length)-marked);updateBadge();});
  }
  async function refresh(force=false){
    const epoch=syncAccount(),cloud=window.SARCloud?.state;if(!cloud?.available||!cloud.account||!cloud.loaded)return;
    if(state.refreshPromise){await state.refreshPromise;if(current(epoch)&&force&&activeView()==='messages')renderMessages();return;}
    const requestedPreferenceRevision=state.preferenceRevision;
    let pending;pending=(async()=>{try{
      // Connection checks and generation polling are independent of inbox rendering.
      void api('/ai/status').then(value=>{if(!current(epoch))return;state.ai=requestedPreferenceRevision===state.preferenceRevision?value:{...value,preferences:preferences()};updateStatus();if(!!document.getElementById('messagingSettings')&&state.settingsSignature!==JSON.stringify(preferences()))renderSettings();}).catch(()=>{});
      const data=await api('/messages');if(!current(epoch))return;
      const ids=new Set((data.messages||[]).map(row=>row.id));
      if(state.inboxSeen&&(data.messages||[]).some(row=>row.direction==='bot'&&!state.inboxSeen.has(row.id)&&row.createdAt>=state.inboxNewest))window.SARAudio?.emit({type:'message'});
      state.inboxNewest=Math.max(state.inboxNewest||0,...(data.messages||[]).map(row=>row.createdAt||0));state.inboxSeen=ids;state.data=data;
      updateBadge();updateStatus();
      if(activeView()==='messages'){
        if(force||state.signature!==messageSignature())renderMessages();
        if(phoneView==='conversation')void refreshThread(selectedBot(),false,force).then(()=>{if(current(epoch)&&activeView()==='messages'&&state.signature!==messageSignature())renderMessages();});
      }else if(activeView()==='phone')renderPhoneHome();else if(!!document.getElementById('messagingSettings')&&state.settingsSignature!==JSON.stringify(preferences()))renderSettings();
      await pollJobs(epoch);
    }catch(error){if(current(epoch))say(error.message);}finally{if(state.refreshPromise===pending)state.refreshPromise=null;}})();state.refreshPromise=pending;return pending;
  }
  function renderPhoneHome(){const unread=unreadCount();modal(`<div class="phone-home-clock"><strong>${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</strong><span>${new Date().toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'})}</span></div><div class="phone-home-title"><h2>Your circuit</h2></div><div class="phone-app-grid"><button class="phone-app-icon" data-phone-action="messages"><span>${phoneIcon('messages')}${unread?`<b>${unread>99?'99+':unread}</b>`:''}</span>Messages</button>${[['scores','Live Scores','<path d="M4 18V9h4v9M10 18V4h4v14M16 18v-7h4v7"/>'],['spectate','Spectate','<path d="m9 5 10 7-10 7V5Z"/>'],['bots','Bot Leaderboard','<path d="M8 3h8v8a4 4 0 0 1-8 0V3ZM8 6H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4m-4 2v6m-4 0h8"/>'],['botmeta','Bot Weapon Meta','<path d="M4 4v16h16M8 15l4-6 4 3 4-7"/>']].map(([id,title,icon])=>`<button class="phone-app-icon" data-phone-open="${id}"><span><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true">${icon}</svg></span>${title}</button>`).join('')}</div>`,'phone');}
  function showPhone(){syncAccount();captureInputs();rememberMessages();window.SARPhone?.didHome?.();phoneView='home';renderPhoneHome();void refresh();}
  function showPhoneList(view){syncAccount();captureInputs();rememberMessages();window.SARPhone?.didMessages?.();phoneView=view;phoneSearch=messageViews[view]?.search||'';if(!accountId()){modal('<div class="phone-empty"><h2>Messages</h2><p>Sign in to open your persistent inbox.</p></div>','messages');return;}renderMessages();const list=document.querySelector('.inbox-threads');if(list)list.scrollTop=messageViews[view]?.scroll||0;void refresh();}
  function showApp(id,html){captureInputs();rememberMessages();phoneView=id;modal(html,'phone-app');}
  document.addEventListener('click',event=>{const action=event.target.closest('[data-phone-action]')?.dataset.phoneAction;if(!action)return;if(appTitles[phoneView]){if(action==='home')showPhone();else if(action==='back')window.SARPhone?.back?.();return;}if(action==='home'||action==='back'&&phoneView!=='conversation'){showPhone();return;}showPhoneList(action==='contacts'?'contacts':action==='back'?phoneReturnView:'inbox');});
  async function showMessages(){rememberMessages();window.SARPhone?.didMessages?.();if(phoneView==='inbox'||phoneView==='contacts')phoneReturnView=phoneView;phoneView='conversation';const epoch=syncAccount();captureInputs();if(!accountId()){modal('<div class="eyebrow">BOT NETWORK</div><h2>MESSAGES</h2><p class="analytics-note">Sign into the account server to use the persistent inbox.</p>','messages');return;}renderMessages();void refresh();void refreshThread(selectedBot()).then(()=>{if(current(epoch)&&activeView()==='messages')renderMessages();});}
  function panelHtml(name){const panel=state.panels[name];return panel?messageCard(panel.row,panel.name):'';}
  function settingsSectionHtml(){const p=preferences();return `<section class="settings-section"><h3>Messaging</h3><div class="social-connection"><strong data-ai-status>${safe(statusText())}</strong><span data-ai-queue>${safe(queueText())}</span></div><p id="aiConnectionError" class="meta-note">${state.ai?.error?'Messaging service unavailable. Check connection.':''}</p><div class="ai-preferences">${[['botMessages','Bot messages'],['botInitiated','Bot-initiated messages'],['playerReplies','Player replies']].map(([key,label])=>`<label class="camera-setting"><input type="checkbox" data-social-pref="${key}" ${p[key]?'checked':''}> ${label}</label>`).join('')}</div><div class="account-actions"><button data-social-action="test">TEST CONNECTION</button><button data-social-action="refresh">CHECK CONNECTION</button></div><p id="socialStatus" role="status" class="meta-note"></p><div id="aiJobResult">${panelHtml('test')}</div></section>`;}
  function renderSettings(){
    state.settingsSignature=JSON.stringify(preferences());const host=document.getElementById('messagingSettings');if(!host)return;
    const active=document.activeElement,inside=host.contains?.(active),key=inside?['id','data-social-pref','data-social-action'].find(name=>active.hasAttribute(name)):null,value=key?active.getAttribute(key):null;
    host.innerHTML=settingsSectionHtml();
    if(key)[...host.querySelectorAll('['+key+']')].find(el=>el.getAttribute(key)===value)?.focus({preventScroll:true});
  }
  async function showSettings(){window.SAR?.showSettings?.('ai');await refresh();renderSettings();}
  function outputFrom(g){return g?.validatedMessage||g?.output||g?.message||g;}
  async function pollJobs(epoch=state.epoch){
    for(const [id,panel] of state.jobs){try{const result=await api('/ai/jobs/'+encodeURIComponent(id));if(!current(epoch))return;const job=result.job||result,done=['COMPLETED','DONE','complete','completed','done','succeeded'].includes(job.status);
      if(done){state.jobs.delete(id);const g=result.generation||job.generation,output=outputFrom(g);if(output?.body&&panel!=='reply'){const genId=g.id||g.generationId||job.generationId,row={...output,id:'lab-'+id,generationId:genId,createdAt:job.completedAt||Date.now(),direction:'bot'};state.panels[panel]={row,name:g.botName||'Connection test'};const target=document.querySelector(panel==='lab'?'#aiLabResult':'#aiJobResult');if(target)target.innerHTML=panelHtml(panel);}say(panel==='reply'?'Reply received':'Preview ready');}
      else if(['FAILED','failed','cancelled','CANCELLED'].includes(job.status)){state.jobs.delete(id);say(panel==='reply'?'Reply could not be completed. Send the same message to retry.':'Preview could not be completed. Try again.');}else say(panel==='reply'?(job.status==='RUNNING'?'Writing a reply…':'Reply queued'):'Preview '+String(job.status||'QUEUED').toLowerCase());
    }catch(error){if(current(epoch))say(error.message);}}
  }
  async function saveFeedback(id,rating,correctedOutput){const epoch=state.epoch;await api('/ai/feedback',{method:'POST',body:JSON.stringify({generationId:id,rating,...(correctedOutput?{correctedOutput}:{})})});if(!current(epoch))return;state.feedback.set(id,rating+' SAVED');const out=[...document.querySelectorAll('[data-feedback-result]')].find(el=>el.dataset.feedbackResult===id);if(out)out.textContent=rating+' SAVED';say(rating+' TRAINING RECORD SAVED');}
  async function savePreference(key,value){
    const epoch=state.epoch,revision=++state.preferenceRevision;state.pendingPrefs.set(key,{value,revision});
    try{const result=await api('/ai/preferences',{method:'PATCH',body:JSON.stringify({[key]:value})});if(!current(epoch)||state.pendingPrefs.get(key)?.revision!==revision)return;const next=result.preferences||result;state.ai={...(state.ai||{}),preferences:{...preferences(),[key]:typeof next[key]===typeof value?next[key]:value}};state.pendingPrefs.delete(key);state.preferenceRevision++;}
    catch(error){if(current(epoch)&&state.pendingPrefs.get(key)?.revision===revision){state.pendingPrefs.delete(key);state.preferenceRevision++;}throw error;}
  }
  function edit(id){const row=state.outputs.get(id);if(!row)return;state.edit={...row,id};restoreEdit();document.querySelector('#socialEditHost textarea')?.focus();}
  document.addEventListener('input',event=>{if(event.target.id==='aiTemperature')state.temperatureDraft=event.target.value;if(event.target.id==='phoneContactSearch'){phoneSearch=event.target.value;renderMessages();return;}captureInputs();if(event.target.id==='socialReply'){const count=document.getElementById('phoneDraftCount');if(count)count.textContent=event.target.value.length+'/500';}});
  document.addEventListener('keydown',event=>{if(event.target.id==='socialReply'&&event.key==='Enter'&&(event.ctrlKey||event.metaKey)){event.preventDefault();document.querySelector('[data-social-action="send"]')?.click();}});
  document.addEventListener('click',async event=>{
    const button=event.target.closest('[data-social-action]');if(!button)return;syncAccount();const epoch=state.epoch,action=button.dataset.socialAction;button.disabled=true;
    try{
      if(action==='refresh')await refresh(true);
      else if(action==='older'){const id=selectedBot(),list=document.querySelector('.message-list'),height=list?.scrollHeight||0,scroll=list?.scrollTop||0;await refreshThread(id,true);if(current(epoch)&&selectedBot()===id&&activeView()==='messages'){renderMessages();const next=document.querySelector('.message-list');if(next)next.scrollTop=scroll+next.scrollHeight-height;}}
      else if(action==='send'){const el=document.querySelector('#socialReply'),text=el?.value.trim(),id=el?.dataset.botId;if(!text)throw new Error('Write a message first.');captureInputs();const result=await api('/messages/reply',{method:'POST',body:JSON.stringify({botId:id,text})});if(!current(epoch))return;if(state.drafts.get(id)?.trim()===text)state.drafts.delete(id);persistDrafts();if(document.querySelector('#socialReply')?.dataset.botId===id&&document.querySelector('#socialReply').value.trim()===text)document.querySelector('#socialReply').value='';if(result.jobId)state.jobs.set(result.jobId,'reply');await refresh(true);if(current(epoch))say('Message sent · reply queued');}
      else if(action==='test'||action==='lab'){captureInputs();const body=action==='lab'?{botId:state.lab.bot,eventType:state.lab.event,mockContext:JSON.parse(state.lab.context)}:{};if(action==='lab'&&(!body.mockContext||Array.isArray(body.mockContext)||typeof body.mockContext!=='object'))throw new Error('Mock context must be a JSON object.');const result=await api('/ai/'+action,{method:'POST',body:JSON.stringify(body)});if(!current(epoch))return;state.jobs.set(result.jobId||result.id,action);say('GENERATION QUEUED · YOU CAN CONTINUE PLAYING');await refresh();}
      else if(action==='feedback')await saveFeedback(button.dataset.generation,button.dataset.rating);
      else if(action==='edit')edit(button.dataset.generation);
      else if(action==='save-edit'){captureInputs();const id=button.dataset.generation,original=state.outputs.get(id),corrected={...original,subject:state.edit.subject.trim(),body:state.edit.body.trim(),mood:state.edit.mood,category:state.edit.category};await saveFeedback(id,'EDIT',corrected);if(current(epoch)){state.edit=null;const host=document.querySelector('#socialEditHost');if(host)host.innerHTML='';}}
      else if(action==='cancel-edit'){state.edit=null;document.querySelector('#socialEditHost').innerHTML='';}
      else if(action==='temperature'){await savePreference('temperature',Number(document.querySelector('#aiTemperature').value));if(current(epoch))state.temperatureDraft=null;await refresh();if(current(epoch))say('TEMPERATURE SAVED');}
      else if(action==='export'){const response=await fetch('/api/ai/export',{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(20000)});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.error||'Export failed');}const text=await response.text();if(!current(epoch))return;const lines=text.trim()?text.trim().split(/\r?\n/):[];lines.forEach(line=>JSON.parse(line));const url=URL.createObjectURL(new Blob([text],{type:'application/x-ndjson'})),link=document.createElement('a');link.href=url;link.download='skirmish-personality-training-'+new Date().toISOString().slice(0,10)+'.jsonl';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say(lines.length+' EVALUATED EXAMPLES EXPORTED');}
    }catch(error){if(current(epoch))say(error.message);}finally{button.disabled=false;}
  });
  // Handle real-message deletion here so loaded older pages cannot resurrect it from the cache.
  document.addEventListener('click',async event=>{const button=event.target.closest('[data-message-delete]');if(!button)return;event.stopImmediatePropagation();event.preventDefault();const epoch=syncAccount(),id=button.dataset.messageDelete;button.disabled=true;try{await api('/messages/'+encodeURIComponent(id),{method:'DELETE'});if(!current(epoch))return;state.data.messages=state.data.messages.filter(row=>row.id!==id);for(const entry of state.threads.values())entry.messages=entry.messages.filter(row=>row.id!==id);await refresh(true);}catch(error){if(current(epoch))say(error.message);}finally{button.disabled=false;}},true);
  document.addEventListener('change',async event=>{
    captureInputs();const key=event.target.dataset?.socialPref;if(!key)return;const epoch=syncAccount(),enabled=event.target.checked;event.target.disabled=true;
    try{await savePreference(key,enabled);if(!current(epoch))return;renderSettings();await refresh();}
    catch(error){if(current(epoch)){event.target.checked=!enabled;say(error.message);}}finally{event.target.disabled=false;}
  });
  // One social refresh timer; generation and simulation run independently.
  const timer=setInterval(()=>{syncAccount();if(!document.hidden)refresh();},8000);
  window.SARSocialUI={showPhone,showMessages,showSettings,showApp,settingsSectionHtml,refresh,getState:()=>state,destroy:()=>clearInterval(timer)};
})();
