(function(){
 'use strict';
 const titles={scores:'Live Scores',spectate:'Spectate',bots:'Bot Leaderboard',botmeta:'Bot Weapon Meta'};
 const memory=Object.fromEntries(Object.keys(titles).map(app=>[app,{app,detail:null,expanded:false,scroll:0,filter:'all',openRows:[],botMode:'tdm',meta:{cohort:'bot',mode:'tdm',kind:'primary'}}]));
 let route=null,active=false,profileReturn=null,account=null,lastPaint=0;
 const safe=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const clock=ms=>{const n=Math.max(0,Math.ceil(ms/1000));return Math.floor(n/60)+':'+String(n%60).padStart(2,'0');};
 const shown=()=>active&&!document.hidden&&document.querySelector('#modal.visible #modalContent[data-view="phone-app"]');
 function remember(){if(!route)return;if(route.expanded&&route.app==='botmeta')Object.assign(route.meta,window.SAR?.getMetaSelection?.('bot')||{});if(route.expanded&&route.app==='bots')route.botMode=window.SAR?.getBotMode?.()||route.botMode;if(document.querySelector('.phone-screen')?.dataset.phoneScreen!==route.app)return;route.scroll=document.querySelector('.phone-scroll')?.scrollTop??route.scroll;route.openRows=[...document.querySelectorAll('.phone-stat-row[open],.phone-meta-row[open]')].map(el=>el.dataset.row);}
 function accountScope(){const id=window.SARCloud?.state?.account?.id||null;if(id!==account){account=id;active=false;route=null;profileReturn=null;for(const view of Object.values(memory)){view.detail=null;view.scroll=0;view.openRows=[];view.expanded=false;view.filter='all';view.botMode='tdm';view.meta={cohort:'bot',mode:'tdm',kind:'primary'};}}}
 function didHome(){remember();active=false;route=null;profileReturn=null;}
 function home(){remember();window.SARPhoneUI?.showPhone?.();}
 function open(app){accountScope();if(!memory[app])return;remember();route=memory[app];active=true;profileReturn=null;render();}
 function openSpectate(options={}){accountScope();remember();route=memory.spectate;active=true;route.expanded=false;if(options.matchId!==undefined)route.detail=Number(options.matchId);else if(options.tournamentId){const match=window.SAR?.getState?.().matches.find(m=>m?.tournamentId===options.tournamentId);route.detail=match?.id??null;}render();}
 function back(){remember();if(profileReturn){route=memory[profileReturn.app];Object.assign(route,profileReturn);profileReturn=null;render();return;}if(route?.expanded){route.expanded=false;render();return;}if(route&&route.detail!==null){route.detail=null;render();return;}home();}
 function decoratePanel(html,view){
  if(view==='profile'&&active&&route){remember();profileReturn={...route};route.expanded=true;}
  if(!active||!route?.expanded||!['meta','bots','profile'].includes(view))return html;
  return '<div class="phone-workspace"><nav class="phone-workspace-nav" aria-label="Phone app navigation"><button data-phone-workspace="back">← Back</button><strong>PHONE / '+safe(titles[route.app])+'</strong><button data-phone-workspace="home">Phone Home</button></nav>'+html+'</div>';
 }
 function matchData(){const game=window.SAR?.getState?.();return {game,matches:game?.matches||[],actors:window.SAR?.getActorSnapshots?.()||[]};}
 function matchBody(match,actors,detail=false){
  const label='MATCH '+String(match.id+1).padStart(2,'0'),ffa=match.mode==='deathmatch',list=actors.filter(a=>a.matchId===match.id),status=match.status;
  const mode=ffa?'DEATHMATCH':'TEAM DEATHMATCH',required=match.requiredParticipants??10,target=match.limit??(ffa?30:60),foot='<p class="phone-match-foot"><span>'+mode+'</span><span>'+target+' KILLS</span></p>';
  if(status==='waiting')return '<div class="phone-match-top"><strong>'+label+'</strong><span>WAITING</span></div><p class="phone-next">Waiting for participants</p>'+foot+'<p class="phone-match-context">'+Math.min(required,match.availableParticipants??0)+' / '+required+' bots available'+(match.waitReason==='tournament-reservations'?' · Tournament reservations active':'')+'</p>';
  if(status==='cooldown')return '<div class="phone-match-top"><strong>'+label+'</strong><span>COMPLETE</span></div><p class="phone-next">Next match in '+Math.ceil((match.slotCooldownMs||0)/1000)+'s</p>'+foot;
  const presentation=window.SAR?.getTeamPresentation?.(match.id),rows=window.SAR?.getMatchStandings?.(match.id)||[];
  let score;
  if(ffa){score='<p class="phone-score-line"><strong>'+safe(rows[0]?.name||'No leader yet')+'</strong><span>'+(rows[0]?.kills??0)+' KILLS</span></p>';if(detail)score+='<ol class="phone-ffa-standings">'+rows.map(a=>'<li>'+safe(a.name)+' <b>'+a.kills+' / '+a.deaths+'</b></li>').join('')+'</ol>';}
  else score='<div class="phone-team-score">'+[0,1].map(team=>{const side=presentation?.team(team)||{label:team?'RED':'BLUE',color:team?'#ec8893':'#79C5F3'};return '<span style="--team-color:'+side.color+'"><small>'+safe(side.label)+'</small><strong>'+match.score[team]+'</strong></span>';}).join('<i>—</i>')+'</div>';
  return '<div class="phone-match-top"><strong>'+label+'</strong><span>'+safe(status==='countdown'?'STARTING':status.toUpperCase())+'</span></div>'+score+'<p class="phone-match-foot"><span>'+mode+'</span><span>'+(match.overtime?'OVERTIME':clock(match.timeLeftMs))+'</span></p><p class="phone-match-context">'+list.length+' / '+required+' participants · '+target+' kills'+(detail?' · '+safe(presentation?.perspectiveLabel||'Neutral view'):'')+'</p>';
 }
 function matchesHtml(){const {game,matches,actors}=matchData(),selected=route.detail===null?null:matches.find(m=>m?.id===route.detail);
  if(route.detail!==null){if(!selected)return '<div class="phone-empty"><h3>Match unavailable</h3><p>This slot is not currently hosting a match.</p><button data-phone-retry>Refresh</button></div>';const canWatch=['active','countdown'].includes(selected.status);return '<article class="phone-match-detail" data-mode="'+selected.mode+'" data-status="'+selected.status+'">'+matchBody(selected,actors,true)+'<button class="primary phone-watch" data-phone-watch="'+selected.id+'" '+(canWatch?'':'disabled')+'>WATCH MATCH</button>'+(canWatch?'':selected.status==='waiting'?'<p>This slot resumes when enough persistent bots are available.</p>':'<p>The next game will be available after the slot cooldown.</p>')+'</article>';}
  const list=matches.filter(m=>m&&(!m.tournamentId||m.status==='active')&&(route.filter==='all'||m.mode===route.filter));
  const slots=matches.filter(m=>m&&m.id<4),active=slots.filter(m=>['active','countdown'].includes(m.status)).reduce((n,m)=>n+m.participants,0),waiting=slots.filter(m=>m.status==='waiting').length;
  const scheduler='<p class="phone-match-context phone-scheduler" role="status">'+slots.filter(m=>m.mode==='tdm').length+' TDM · '+slots.filter(m=>m.mode==='deathmatch').length+' Deathmatch<br>'+active+' active participants · '+(game?.idleBots??0)+' in waiting pool'+(waiting?' · '+waiting+' '+(waiting===1?'slot':'slots')+' waiting':'')+'</p>';
  return '<label class="phone-filter">MODE<select data-phone-filter><option value="all" '+(route.filter==='all'?'selected':'')+'>All matches</option><option value="tdm" '+(route.filter==='tdm'?'selected':'')+'>Team Deathmatch</option><option value="deathmatch" '+(route.filter==='deathmatch'?'selected':'')+'>Deathmatch</option></select></label>'+scheduler+(!list.length?'<div class="phone-empty"><h3>No matches in this view</h3><p>Choose another mode or check back shortly.</p></div>':list.map(m=>'<button class="phone-match-card" data-phone-match="'+m.id+'" data-mode="'+m.mode+'" data-status="'+m.status+'">'+matchBody(m,actors)+'</button>').join(''));
 }
 function botRowsHtml(){const data=window.SAR?.getBotTable?.(route.botMode);if(!data)return '<p>Loading careers…</p>';const template=document.createElement('template');template.innerHTML='<table><thead><tr>'+data.head+'</tr></thead><tbody>'+data.body+'</tbody></table>';const heads=[...template.content.querySelectorAll('th')].map(el=>el.textContent.trim().replace(/[▲▼↑↓]/g,'')),options=[...template.content.querySelectorAll('[data-sort-key]')].map(el=>'<option value="'+el.dataset.sortKey+'" '+(data.sort?.key===el.dataset.sortKey?'selected':'')+'>'+safe(el.textContent.trim())+'</option>');return '<label class="phone-filter">MODE<select data-phone-bot-mode><option value="tdm" '+(route.botMode==='tdm'?'selected':'')+'>Team Deathmatch</option><option value="deathmatch" '+(route.botMode==='deathmatch'?'selected':'')+'>Deathmatch</option></select></label><label class="phone-filter">SORT<select data-phone-bot-sort>'+options.join('')+'</select></label><button class="phone-sort-direction" data-phone-sort-direction>Order: '+(data.sort?.dir===1?'ascending ↑':'descending ↓')+'</button>'+[...template.content.querySelectorAll('tbody tr')].map((row,i)=>{const cells=[...row.children],id=cells[0]?.textContent.trim()||String(i);return '<details class="phone-stat-row" data-row="'+safe(id)+'" '+(route.openRows.includes(id)?'open':'')+'><summary>'+cells[0]?.innerHTML+'<span>'+safe(heads[1])+': '+cells[1]?.innerHTML+'</span></summary><dl>'+cells.slice(1).map((cell,j)=>'<div><dt>'+safe(heads[j+1])+'</dt><dd>'+cell.innerHTML+'</dd></div>').join('')+'</dl></details>';}).join('');}
 function metaHtml(){const m=route.meta;return '<div class="phone-meta-filters"><label>CATEGORY<select data-phone-meta-kind><option value="primary" '+(m.kind==='primary'?'selected':'')+'>Primary</option><option value="sidearm" '+(m.kind==='sidearm'?'selected':'')+'>Sidearm</option></select></label><label>MODE<select data-phone-meta-mode><option value="tdm" '+(m.mode==='tdm'?'selected':'')+'>TDM</option><option value="deathmatch" '+(m.mode==='deathmatch'?'selected':'')+'>Deathmatch</option></select></label></div>'+(window.SAR?.compactMetaHtml?.(m)||'<p>Loading weapon statistics…</p>');}
 function render(){if(!route)return;window.SAR?.preparePanel?.();if(route.expanded){if(route.app==='botmeta')window.SAR?.showWeaponMeta?.(route.meta);else if(route.app==='bots'){window.SAR?.setBotMode?.(route.botMode);window.SAR?.showBotLeaderboard?.();}return;}
  let body;try{body=route.app==='bots'?botRowsHtml():route.app==='botmeta'?metaHtml():matchesHtml();}catch(error){console.error('Phone '+route.app+' failed',error);body='<div class="phone-empty"><h3>Could not load this app</h3><p>Your data has been retained.</p><button data-phone-retry>RETRY</button></div>';}
  const expandable=['bots','botmeta'].includes(route.app);window.SARPhoneUI?.showApp?.(route.app,'<header class="phone-app-heading"><div><h2>'+titles[route.app]+'</h2><p>'+(route.app==='scores'?'The circuit, live':route.app==='spectate'?'Choose a match to watch':route.app==='bots'?(route.botMode==='deathmatch'?'Deathmatch career records':'TDM career records'):'Bot participants · current patch')+'</p></div>'+(expandable?'<button data-phone-expand>Expand ↗</button>':'')+'</header><div class="phone-scroll">'+body+'</div>');document.querySelectorAll('.phone-meta-row').forEach(el=>el.open=route.openRows.includes(el.dataset.row));const scroll=document.querySelector('.phone-scroll');if(scroll)scroll.scrollTop=route.scroll;lastPaint=Date.now();
 }
 document.addEventListener('click',event=>{const el=event.target.closest('button');if(!el)return;
  if(el.dataset.phoneOpen){open(el.dataset.phoneOpen);return;}
  if(el.dataset.phoneWorkspace){el.dataset.phoneWorkspace==='home'?home():back();return;}
  if(el.hasAttribute('data-phone-retry')){render();return;}
  if(el.hasAttribute('data-phone-match')){remember();route.detail=Number(el.dataset.phoneMatch);route.scroll=0;render();return;}
  if(el.hasAttribute('data-phone-watch')){const id=Number(el.dataset.phoneWatch);memory.spectate.detail=id;memory.spectate.filter=route.filter;route=memory.spectate;active=false;window.SARFullscreen?.onPlay?.();if(!window.SAR?.watchMatch?.(id)){active=true;render();}return;}
  if(el.hasAttribute('data-phone-expand')||el.hasAttribute('data-phone-meta-weapon')){remember();route.expanded=true;if(route.app==='botmeta'&&el.dataset.phoneMetaWeapon)route.meta.weapon=el.dataset.phoneMetaWeapon;render();return;}
  if(el.hasAttribute('data-phone-sort-direction')){window.SAR.setBotSort(window.SAR.getBotTable().sort.key);render();}
 });
 document.addEventListener('change',event=>{if(!route)return;const el=event.target;if(el.hasAttribute('data-phone-filter'))route.filter=el.value;else if(el.hasAttribute('data-phone-bot-mode')){route.botMode=el.value==='deathmatch'?'deathmatch':'tdm';window.SAR?.setBotMode?.(route.botMode);}else if(el.hasAttribute('data-phone-bot-sort'))window.SAR?.setBotSort?.(el.value);else if(el.hasAttribute('data-phone-meta-kind'))route.meta.kind=el.value;else if(el.hasAttribute('data-phone-meta-mode'))route.meta.mode=el.value;else return;route.scroll=0;render();});
 // Reuse simulation snapshots. Only the visible match app refreshes its DOM.
 const timer=setInterval(()=>{accountScope();if(shown()&&!route?.expanded&&['scores','spectate'].includes(route?.app)&&Date.now()-lastPaint>=950&&!document.activeElement?.matches('select')){const focus=document.activeElement?.getAttribute('data-phone-match');remember();render();if(focus!==null)document.querySelector('[data-phone-match="'+focus+'"]')?.focus({preventScroll:true});}},1000);
 window.SARPhone={open,openSpectate,back,home,didHome,decoratePanel,returnFromSpectate(){active=true;route=memory.spectate;render();},suspend(){remember();active=false;},getState:()=>({app:route?.app,detail:route?.detail,expanded:!!route?.expanded,active}),destroy:()=>clearInterval(timer)};
})();
