(() => {
 'use strict';
 const state={events:[],earnings:[],history:[],details:{},month:new Date(new Date().getFullYear(),new Date().getMonth(),1),selected:null,selectedDate:null,kind:'all',status:'all',detailTab:'overview',sort:{teams:{key:'aggregateKills',direction:'desc'},players:{key:'kills',direction:'desc'}},epoch:0,error:'',loaded:false,connection:'loading',view:'board',refreshing:false,flushing:false,mutating:false,lastRefresh:0};
 const safe=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
 const account=()=>window.SARCloud?.state.account,api=(path,body)=>window.SARCloud.api(path,body?{method:'POST',body:JSON.stringify(body)}:undefined),now=()=>window.SARCloud?.now?.()||Date.now();
 const key=()=>`sar.tournament.calendar.${account()?.id||''}`,pendingKey=()=>`sar.tournament.pending.${account()?.id||''}`;
 const money=value=>'$'+Number(value||0).toLocaleString(),date=value=>new Date(value).toLocaleString([],{dateStyle:'medium',timeStyle:'short'}),zone=()=>Intl.DateTimeFormat().resolvedOptions().timeZone;
 const scheduledDate=(value,timezone,precise=false)=>new Date(value-(timezone==='EST'?5*3600000:0)).toLocaleString([],{dateStyle:'medium',timeStyle:precise?'medium':'short',...(timezone==='EST'?{timeZone:'UTC'}:timezone==='America/New_York'?{timeZone:timezone}:{})})+(timezone==='EST'?' EST':timezone==='America/New_York'?' Eastern':'');
 const publicState=value=>({QF:'Quarterfinal',SF:'Semifinal',FINAL:'Final',champion:'Champion',placed:'Placed',completed:'Completed',registered:'Registered','in-progress':'In progress','awaiting-tie-policy':'Awaiting tie policy',eliminated:'Eliminated','waiting-next-round':'Waiting for next round','waiting-opponents':'Waiting for opponents',countdown:'Pre-match countdown',active:'Playing',playing:'Playing',ended:'Finalized'})[value]||String(value||'—').replaceAll('_',' ').replaceAll('-',' ');
 const dateKey=value=>{const d=new Date(value);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
 const viewing=()=>document.getElementById('modalContent')?.dataset.view==='tournaments'&&document.getElementById('modal')?.classList.contains('visible');
 const upcoming=t=>['REGISTRATION','ANNOUNCED','UPCOMING'].includes(t.status);
 const yours=t=>t.teams.find(team=>team.participants.some(p=>p.id===account()?.id)||t.replacementHistory?.some(r=>r.teamId===team.id&&r.previous?.id===account()?.id));
 const completeTeams=t=>t.teams.length===8&&t.teams.every(team=>team.participants.length===5);
 const aggregateRuleset='arena-refined-aggregate-kills-v1',aggregate=(t,s)=>((s?.rulesetId)||t.rulesetId)===aggregateRuleset;
 const aggregateAtStart=t=>aggregate(t)||(upcoming(t)&&!(t.series||[]).some(s=>s.games?.length));
 const requiredGames=s=>s.requiredGames||(s.round==='FINAL'?5:3);
 const tied=s=>s.status==='awaiting-tie-policy'||s.advancement?.status==='tied';
 const tieLabel=s=>s.advancement?.criterion==='explicit-ruling-required'?'Kills and total damage tied · awaiting explicit ruling':'Aggregate tied · awaiting a confirmed tie policy';
 const playable=(t,s)=>!s.winnerTeamId&&s.teamIds.every(Boolean)&&(!aggregate(t,s)||(!tied(s)&&s.status!=='complete'&&(s.completedGames??s.games?.length??0)<requiredGames(s)));
 const eventFormat=t=>aggregateAtStart(t)?'3-game aggregate kills · final: 5-game aggregate kills':'Historical format · BO3 / BO5';
 const title=t=>t.displayName||t.name;
 const scheduled=t=>t?.schedulePolicy?.confirmed===true;
 const checkpointKey=(owner,gameId)=>'sar.tournament.runtime.'+owner+'.'+gameId;
 let entryAttempt=null,activeLease=null,heartbeatBusy=false,lastHeartbeat=0;
 function clientId(){if(state.clientOwner===account()?.id&&state.clientId)return state.clientId;const key='sar.tournament.client.'+account()?.id;let id;try{id=sessionStorage.getItem(key);}catch{}if(!id){id=globalThis.crypto?.randomUUID?.()||('client-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2));try{sessionStorage.setItem(key,id);}catch{}}state.clientOwner=account()?.id;return state.clientId=id;}
 function gameRows(t){return Object.values(t?.scheduling?.games||{});}
 function ownScheduledGame(t){const team=yours(t);return gameRows(t).filter(g=>!g.finalizedAt&&t.series?.find(s=>s.id===g.seriesId)?.teamIds.includes(team?.id)).sort((a,b)=>a.checkInOpenAt-b.checkInOpenAt)[0]||null;}
 function ownCheckedIn(g){return !!g?.checkIns?.[account()?.id];}
 function scheduledEntryPanel(t){
  const g=ownScheduledGame(t);if(!g)return '<p class="circuit-footnote">Your next scheduled pairing will appear after advancement is finalized.</p>';
  const checked=ownCheckedIn(g),open=now()>=g.checkInOpenAt&&now()<g.checkInCloseAt,error=g.error?.message||g.error||'',replaced=[...(g.replacements||[]),...(t.replacementHistory||[])].some(r=>[r.previous?.id,r.originalParticipantId,r.absentParticipantId,r.userId,r.originalId].includes(account()?.id)),busy=entryAttempt?.gameId===g.gameId;
  let action=checked?'<strong class="circuit-checkin-confirmed">CHECKED IN</strong>':`<button class="primary" data-circuit-action="check-in" data-game="${safe(g.gameId)}" ${open&&!replaced?'':'disabled'}>CHECK IN</button>`;
  if(checked&&g.rostersLockedAt&&!error&&!activeLease&&!busy)action+=`<button data-circuit-action="scheduled-play" data-game="${safe(g.gameId)}">${state.entrySuppressed===g.gameId?'RETRY ENTRY':'ENTER SCHEDULED GAME'}</button>`;
  const info=replaced?'Your tournament place was filled by an eligible bot. The replacement keeps the place and its earnings for this event.':error?'Schedule conflict · '+error:busy?'Preparing your scheduled match…':checked?'Your check-in is saved. The game prepares automatically after rosters lock.':open?'Check in before the deadline to keep your place.':now()<g.checkInOpenAt?'Check-in opens at the saved time below.':'Check-in is closed.';
  return `<div class="circuit-checkin" data-game="${safe(g.gameId)}"><div class="circuit-toolbar">${action}</div><p role="status">${safe(info)}</p><dl><div><dt>Check-in opens</dt><dd>${safe(scheduledDate(g.checkInOpenAt,t.schedulePolicy.timezone,true))}</dd></div><div><dt>Check-in closes</dt><dd>${safe(scheduledDate(g.checkInCloseAt,t.schedulePolicy.timezone,true))}</dd></div><div><dt>Match starts</dt><dd>${safe(scheduledDate(g.matchStartAt,t.schedulePolicy.timezone,true))}</dd></div></dl></div>`;
 }
 async function prepareScheduledGame(t,g,{manual=false}={}){
  if(window.SARCloud?.state.tournamentResetBlocked){state.error='Tournament recovery is retained. Free local storage and refresh to retry cleanup before entering a game.';if(viewing())detail(t);return false;}
  if(!account()||entryAttempt||activeLease||!g||!ownCheckedIn(g)||!g.rostersLockedAt||g.error||(!manual&&(state.entrySuppressed===g.gameId||now()<(state.entryRetryAt||0))))return;
  const current=window.SAR?.getState?.();if(current?.playerMatchId!=null||current?.queued||current?.running&&current?.mode==='play')return;
  const owner=account().id,client=clientId(),attempt={owner,gameId:g.gameId,tournamentId:t.id},checkpoint=window.SARStorage?.getTournament?.(checkpointKey(owner,g.gameId));entryAttempt=attempt;state.entrySuppressed=null;state.entryRetryAt=0;
  try{
    const data=await api('/tournaments/'+t.id+'/play',{gameId:g.gameId,clientId:client,resume:!!checkpoint});
    if(owner!==account()?.id||entryAttempt!==attempt)return;const context=data.context;if(!context?.schedule||context.gameId!==g.gameId)throw Error('The scheduled game did not return its authoritative roster.');
    activeLease={owner,tournamentId:t.id,gameId:g.gameId,clientId:client,leaseToken:context.leaseToken};lastHeartbeat=0;void heartbeat();
    const result=await window.SAR.beginTournamentEntry(context,{checkpoint,cancel(){state.entrySuppressed=g.gameId;activeLease=null;if(viewing())detail(state.events.find(item=>item.id===t.id));},async ready(signal){
      if(signal.aborted||owner!==account()?.id)throw Error('Tournament entry cancelled.');
      const confirmed=await api('/tournaments/'+t.id+'/ready',{gameId:g.gameId,clientId:client,leaseToken:context.leaseToken,resume:!!checkpoint});
      if(signal.aborted||owner!==account()?.id)throw Error('Tournament entry cancelled.');return confirmed.context||context;
    }});
    if(result?.entered&&owner===account()?.id){await window.SARTournaments?.checkpoint?.();}
    else{state.entrySuppressed=g.gameId;activeLease=null;}
  }catch(error){if(owner===account()?.id){activeLease=null;const waitForLease=checkpoint&&error.status===409&&g.lease?.expiresAt>now();state.entrySuppressed=waitForLease?null:g.gameId;state.entryRetryAt=waitForLease?g.lease.expiresAt+25:0;state.error=waitForLease?'Saved game ready. Waiting for the previous window’s lease to close.':'Tournament entry · '+error.message;if(viewing()&&state.selected===t.id)detail(state.events.find(item=>item.id===t.id));}}
  finally{if(entryAttempt===attempt)entryAttempt=null;}
 }
 function autoEntry(){if(entryAttempt||activeLease||window.SARCloud?.state.available===false||window.SARCloud?.state.tournamentResetBlocked)return;for(const t of state.events){if(!scheduled(t)||t.status!=='ACTIVE')continue;const g=ownScheduledGame(t);if(ownCheckedIn(g)&&g.rostersLockedAt){void prepareScheduledGame(t,g);break;}}}
 async function heartbeat(){
  if(heartbeatBusy||!activeLease||activeLease.owner!==account()?.id||Date.now()-lastHeartbeat<3000)return;const lease=activeLease;heartbeatBusy=true;lastHeartbeat=Date.now();
  try{const snapshot=window.SAR?.captureTournamentGame?.(lease.gameId);if(snapshot)await window.SARStorage?.putTournament?.(checkpointKey(lease.owner,lease.gameId),snapshot);const data=await api('/tournaments/'+lease.tournamentId+'/heartbeat',{gameId:lease.gameId,leaseToken:lease.leaseToken,clientId:lease.clientId});if(activeLease!==lease)return;if(['CANCELLED','COMPLETED'].includes(data.status)){window.SAR?.cancelTournament?.(lease.tournamentId);activeLease=null;void refresh();}}
  catch(error){if(activeLease===lease){state.error='Tournament recovery · '+error.message;if([403,404,409,410].includes(error.status)){if(entryAttempt?.gameId===lease.gameId)window.SARModeEntry?.cancel({restore:false});window.SAR?.cancelTournament?.(lease.tournamentId);state.entrySuppressed=lease.gameId;activeLease=null;void refresh();}}}
  finally{heartbeatBusy=false;}
 }
 async function checkpoint(){const lease=activeLease;if(!lease||lease.owner!==account()?.id)return;const snapshot=window.SAR?.captureTournamentGame?.(lease.gameId);if(snapshot)await window.SARStorage?.putTournament?.(checkpointKey(lease.owner,lease.gameId),snapshot);}
 const detailTabs=[['overview','Overview / Schedule'],['bracket','Bracket'],['teams','Team Leaderboard'],['players','Player Stats Leaderboard']];
 function modal(html,{top=false}={}){
  const host=document.getElementById('modalContent');if(!host)return;
  const active=document.activeElement,focus=host.contains?.(active)?{id:active.id,action:active.dataset?.circuitAction,event:active.dataset?.circuitEvent,day:active.dataset?.circuitDay,value:active.dataset?.value}:null,scroll=host.scrollTop,invite=document.getElementById('circuitBot')?.value,scrollers=[...host.querySelectorAll('[data-circuit-scroll]')].map(el=>[el.dataset.circuitScroll,el.scrollTop,el.scrollLeft]);
  host.dataset.view='tournaments';host.innerHTML=html;document.getElementById('modal').classList.add('visible');host.scrollTop=top?0:scroll;
  const select=document.getElementById('circuitBot');if(select&&[...select.options||[]].some(option=>option.value===invite))select.value=invite;
  if(!top)for(const [name,y,x] of scrollers){const el=[...host.querySelectorAll('[data-circuit-scroll]')].find(item=>item.dataset.circuitScroll===name);if(el){el.scrollTop=y;el.scrollLeft=x;}}
  if(focus){const target=focus.id?document.getElementById(focus.id):[...host.querySelectorAll('[data-circuit-action],[data-circuit-event],[data-circuit-day]')].find(el=>focus.action?el.dataset.circuitAction===focus.action&&el.dataset.value===focus.value:focus.event?el.dataset.circuitEvent===focus.event:focus.day&&el.dataset.circuitDay===focus.day);target?.focus({preventScroll:true});}
 }
 function countdown(t){
  if(t.status==='COMPLETED')return 'Completed';if(t.status==='CANCELLED')return 'Cancelled';if(t.status==='ACTIVE')return 'Live';
  const remaining=t.startsAt-now();if(remaining<=0)return completeTeams(t)?'Ready to start':'Waiting for complete teams';
  const minutes=Math.ceil(remaining/60000),days=Math.floor(minutes/1440);return 'Starts in '+(days?days+'d '+Math.floor(minutes%1440/60)+'h':minutes>=60?Math.floor(minutes/60)+'h '+minutes%60+'m':minutes+'m');
 }
 function statusLabel(t){if(t.status==='ACTIVE')return 'Live';if(t.status==='COMPLETED')return 'Completed';if(t.status==='CANCELLED')return 'Cancelled';if(upcoming(t))return t.teams.length>=8?'Registration closed · 8 teams':t.status==='REGISTRATION'?'Registration open':'Scheduled · registration open';return 'Registration closed';}
 const canDelete=t=>t.kind==='custom'&&t.canDelete&&(!t.creatorId||t.creatorId===account()?.id);
 const notice=()=>state.error?'<p class="circuit-notice" data-connection="'+safe(state.connection)+'" role="status">'+safe(state.error)+'</p>':'';
 function eventCard(t,featured=false){
  const checking=t.status==='ACTIVE'&&Object.values(t.scheduling?.games||{}).some(g=>g.state==='CHECK_IN_OPEN'),chip=checking?'CHECK-IN':t.status==='ACTIVE'?'LIVE':t.status==='COMPLETED'?'COMPLETED':t.status==='CANCELLED'?'CANCELLED':'UPCOMING';
  return `<button class="${featured?'circuit-feature':'circuit-event'}" data-circuit-event="${safe(t.id)}" data-status="${safe(t.status)}" aria-label="${safe(title(t))} — ${safe(statusLabel(t))} — ${safe(date(t.startsAt))}"><span class="circuit-event-meta"><span>${t.kind==='official'?'OFFICIAL':'CUSTOM'} <span class="circuit-state-chip" data-state="${chip}">${chip}</span></span><b data-circuit-clock="${safe(t.id)}">${countdown(t)}</b></span><strong>${safe(title(t))}</strong><span class="circuit-event-facts"><time datetime="${new Date(t.startsAt).toISOString()}">${safe(date(t.startsAt))}</time><span>${t.teams.length} / 8 teams</span></span><small>${safe(eventFormat(t))}</small><small>${safe(statusLabel(t))}<span aria-hidden="true"> →</span></small></button>`;
 }
 function filtered(){return state.events.filter(t=>(state.kind==='all'||t.kind===state.kind)&&(state.status==='all'||state.status==='upcoming'&&upcoming(t)||state.status==='live'&&t.status==='ACTIVE'||state.status==='completed'&&t.status==='COMPLETED'||state.status==='cancelled'&&t.status==='CANCELLED')).sort((a,b)=>a.startsAt-b.startsAt);}
 function calendar(events){
  const month=state.month,first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0),today=dateKey(now()),cells=Array.from({length:first.getDay()},()=>'<div class="calendar-spacer" aria-hidden="true"></div>');
  for(let day=1;day<=last.getDate();day++){const d=new Date(month.getFullYear(),month.getMonth(),day),key=dateKey(d),dayEvents=events.filter(t=>dateKey(t.startsAt)===key),selected=key===state.selectedDate;cells.push(`<div class="calendar-day ${key===today?'today':''} ${selected?'selected':''}"><button class="calendar-date" data-circuit-day="${key}" aria-pressed="${selected}" ${key===today?'aria-current="date"':''} aria-label="${safe(d.toLocaleDateString([],{dateStyle:'full'}))}, ${dayEvents.length} ${dayEvents.length===1?'event':'events'}">${day}</button>${dayEvents.map(t=>`<button class="calendar-event" data-circuit-event="${safe(t.id)}" data-status="${safe(t.status)}" aria-label="${safe(title(t))} — ${safe(date(t.startsAt))} — ${safe(statusLabel(t))}" title="${safe(title(t))}">${safe(title(t))}</button>`).join('')}</div>`);}
  return `<section class="circuit-calendar-panel" aria-label="Tournament calendar"><div class="calendar-heading"><button data-circuit-action="previous" aria-label="Previous month">←</button><h3>${month.toLocaleDateString([],{month:'long',year:'numeric'})}</h3>${month.getMonth()!==new Date(now()).getMonth()||month.getFullYear()!==new Date(now()).getFullYear()?'<button data-circuit-action="today">TODAY</button>':''}<button data-circuit-action="next" aria-label="Next month">→</button></div><div class="circuit-calendar">${['SUN','MON','TUE','WED','THU','FRI','SAT'].map(d=>'<strong>'+d+'</strong>').join('')}${cells.join('')}</div><p class="circuit-footnote">Local times · ${safe(zone())}</p></section>`;
 }
 function filterButtons(type,options){return `<div class="circuit-filter-group" role="group" aria-label="${type==='kind'?'Event type':'Event status'}">${options.map(([value,label])=>`<button data-circuit-action="filter-${type}" data-value="${value}" aria-pressed="${state[type]===value}">${label}</button>`).join('')}</div>`;}
 function historyBoard(){
  const records=state.history.length?state.history:state.events.filter(t=>t.kind==='official'&&t.status==='COMPLETED').map(t=>({tournamentId:t.id,name:t.name,startsAt:t.startsAt,rulesetId:t.rulesetId,winnerTeamName:null,winningRoster:[],placements:t.placements}));
  return `<section class="circuit-history"><div class="circuit-section-heading"><h3>OFFICIAL TOURNAMENT HISTORY</h3><span>${records.length} completed ${records.length===1?'event':'events'}</span></div>${records.length?'<div class="circuit-history-list" data-circuit-scroll="history">'+records.slice().sort((a,b)=>b.startsAt-a.startsAt).map(h=>`<article><div><time datetime="${new Date(h.startsAt).toISOString()}">${safe(date(h.startsAt))}</time><h4>${safe(h.name)}</h4><p><b>${safe(h.winnerTeamName||'Winning team unavailable')}</b></p><p class="circuit-footnote">${h.winningRoster?.length?'Winning roster · '+h.winningRoster.map(p=>safe(p.name||p.id)).join(', '):'Winning roster unavailable in this record.'}</p><p class="circuit-footnote">${h.placements?.length?h.placements.slice().sort((a,b)=>a.placement-b.placement).map(p=>safe(p.placement)+' · '+safe(p.name||'Recorded team')).join(' · '):'Placement records unavailable.'}</p></div><button data-circuit-event="${safe(h.tournamentId||h.id)}">VIEW DETAILS →</button></article>`).join('')+'</div>':`<p class="circuit-footnote" role="status">${state.connection==='loading'?'Loading saved official results…':state.connection==='offline'?'Offline — saved official history is unavailable on this device.':state.connection==='error'?'Official history could not be loaded. Refresh to retry.':'No completed official tournaments have been recorded.'}</p>`}</section>`;
 }
 function emptyCalendar(){
  const heading=state.connection==='offline'&&!state.loaded?'Offline calendar':state.connection==='error'&&!state.loaded?'Calendar unavailable':!state.loaded?'Loading tournaments…':state.events.length?'No matching events':'No events scheduled';
  const text=state.connection==='offline'&&!state.loaded?'Reconnect to load events. Saved account and world data remain available.':state.connection==='error'&&!state.loaded?'The schedule request failed. Use Refresh to retry.':!state.loaded?'Your events and saved results will appear here.':state.events.length?'Choose another date or adjust the filters.':'Official events appear here when scheduled. Create a custom tournament to organize your own.';
  return `<div class="circuit-empty" data-connection="${safe(state.connection)}" role="status"><h3>${heading}</h3><p>${text}</p></div>`;
 }
 function board({top=false}={}){
  state.selected=null;state.view='board';const earned=state.earnings.find(p=>p.participantId===account()?.id)?.amount||0,events=filtered(),listed=events.filter(t=>!state.selectedDate||dateKey(t.startsAt)===state.selectedDate),feature=events.find(t=>t.status==='ACTIVE')||events.find(t=>upcoming(t)&&t.startsAt>=now())||events.find(upcoming);
  modal(`<div class="circuit-heading"><div><div class="eyebrow">COMPETITION</div><h2>TOURNAMENTS</h2></div><button class="primary" data-circuit-action="create">CREATE TOURNAMENT</button></div><div class="circuit-summary"><span>Your in-game earnings <strong>${money(earned)}</strong></span><span>8 teams · 5 players per team</span><button data-circuit-action="refresh">REFRESH</button></div>${notice()}${feature?eventCard(feature,true):''}<div class="circuit-filters">${filterButtons('kind',[['all','All events'],['official','Official'],['custom','Custom']])}${filterButtons('status',[['all','All statuses'],['upcoming','Upcoming'],['live','Live'],['completed','Completed'],['cancelled','Cancelled']])}</div><div class="circuit-board">${calendar(events)}<section class="circuit-events-panel" aria-label="Event list"><div class="circuit-list-heading"><h3>${state.selectedDate?safe(new Date(state.selectedDate+'T12:00:00').toLocaleDateString([],{month:'long',day:'numeric'})):'Event list'}</h3>${state.selectedDate?'<button data-circuit-action="clear-date">ALL DATES</button>':`<span>${listed.length} ${listed.length===1?'event':'events'}</span>`}</div><div class="circuit-event-list">${listed.map(t=>eventCard(t)).join('')||emptyCalendar()}</div></section></div>${historyBoard()}`,{top});
 }
 function cache(){
  if(window.SARCloud?.state.tournamentResetBlocked)return;
  const details=Object.fromEntries(Object.entries(state.details).filter(([,entry])=>entry.loaded).map(([id,entry])=>[id,{loaded:true,error:'',loading:false,data:{presentation:entry.data?.presentation}}]));
  try{localStorage.setItem(key(),JSON.stringify({tournaments:state.events,earnings:state.earnings,officialHistory:state.history,details}));state.cacheWarning=false;}catch{if(!state.cacheWarning)console.warn('Tournament display cache could not be saved. The current online records remain available.');state.cacheWarning=true;}
  window.SARCloud.state.tournamentReservations=state.events;window.SAR?.syncTournamentReservations?.(state.events);
  window.SAR?.updateTournamentProfileRecords?.(state.events);
 }
 async function refreshDetail(id,{force=false}={}){
  if(!id)return;const epoch=state.epoch,owner=account()?.id,entry=state.details[id]||={loaded:false,data:null,error:'',loading:false};
  if(entry.loading||(!force&&entry.loaded))return;entry.loading=true;
  try{const data=await api('/tournaments/'+encodeURIComponent(id));if(epoch!==state.epoch||owner!==account()?.id)return;if(!data?.tournament)throw new Error('Tournament details were not returned.');entry.data=data;entry.loaded=true;entry.error='';const index=state.events.findIndex(t=>t.id===id);if(index>=0)state.events[index]=data.tournament;else state.events.push(data.tournament);cache();}
  catch(e){if(epoch===state.epoch&&owner===account()?.id)entry.error=(window.SARCloud?.state.available===false?'Offline — ':'Details unavailable — ')+e.message;}
  finally{entry.loading=false;}
  if(epoch===state.epoch&&owner===account()?.id&&viewing()&&state.selected===id&&state.view==='detail')detail(state.events.find(t=>t.id===id)||entry.data?.tournament);
 }
 async function openEvent(id){
  if(state.selected!==id)state.detailTab='overview';state.selected=id;state.view='detail';const t=state.events.find(t=>t.id===id)||state.details[id]?.data?.tournament;
  if(t)detail(t,{top:true});else modal('<button data-circuit-action="calendar">← BACK TO TOURNAMENTS</button><p role="status">Loading tournament details…</p>',{top:true});
  await refreshDetail(id,{force:true});
 }
 async function refresh(){
  if(state.refreshing)return;state.refreshing=true;state.lastRefresh=Date.now();const epoch=state.epoch,id=account()?.id;
  try{const data=await api('/tournaments');if(id!==account()?.id)return;const reset=await window.SARCloud?.applyTournamentReset?.(data.tournamentResetId);if(epoch!==state.epoch&&!reset)return;state.events=Array.isArray(data.tournaments)?data.tournaments:[];state.history=Array.isArray(data.officialHistory)?data.officialHistory:[];const active=window.SAR?.getActiveTournament?.();if(active&&!state.events.some(t=>t.id===active&&!['CANCELLED','COMPLETED'].includes(t.status))){window.SAR.cancelTournament(active);activeLease=null;state.selected=null;state.view='board';}state.earnings=data.earnings||[];state.error=window.SARCloud?.state.tournamentResetBlocked?'Tournament recovery is retained. Cleanup will retry before entering an old game.':'';state.loaded=true;state.connection='online';cache();if(state.selected&&state.view==='detail')await refreshDetail(state.selected,{force:true});autoEntry();}
  catch(e){if(epoch===state.epoch&&id===account()?.id){state.connection=window.SARCloud?.state.available===false?'offline':'error';state.error=(state.loaded?'Saved calendar · ':'')+(state.connection==='offline'?'Offline — ':'Schedule unavailable — ')+e.message;}}
  finally{state.refreshing=false;if(epoch!==state.epoch&&viewing())void refresh();}
  if(epoch===state.epoch&&id===account()?.id&&viewing()&&state.view!=='create'){if(state.selected)detail(state.events.find(t=>t.id===state.selected));else board();}
 }
 function liveMatches(t){if(!t)return [];return (window.SAR?.getState?.().matches||[]).filter(m=>m&&['countdown','active'].includes(m.status)&&(m.tournamentId||m.context?.tournamentId)===t.id);}
 function registration(t,team,roster){
  const open=upcoming(t),available=Object.values(roster).filter(p=>!t.teams.some(other=>other.participants.some(member=>member.id===p.id))&&!t.invites.some(i=>i.teamId===team?.id&&i.botId===p.id));
  let actions='',explanation='';
  if(open&&!team){const full=t.teams.length>=8;actions=`<button class="primary" data-circuit-action="join" ${full?'disabled aria-describedby="circuitActionHelp"':''}>REGISTER YOUR TEAM</button>`;if(full)explanation='All eight team places are reserved.';}
  if(open&&team){if(team.participants.length<5&&['REGISTRATION','UPCOMING'].includes(t.status)){actions=`<label>Invite a bot<select id="circuitBot" ${available.length?'':'disabled'}>${available.length?available.map(p=>'<option value="'+safe(p.id)+'">'+safe(p.name)+'</option>').join(''):'<option>No available contacts</option>'}</select></label><button data-circuit-action="invite" data-team="${safe(team.id)}" ${available.length?'':'disabled aria-describedby="circuitActionHelp"'}>INVITE</button>`;explanation=available.length?'Invitations follow each bot’s availability and existing commitments.':'All available contacts are already registered or have answered an invitation.';}else explanation=team.participants.length===5?'Your five-player roster is complete.':'Your team is registered. Invitations become available when registration opens.';}
  if(open&&t.kind==='custom'){const ready=now()>=t.startsAt;actions+=`<button data-circuit-action="start" ${ready?'':'disabled aria-describedby="circuitStartHelp"'}>START TOURNAMENT</button>`;explanation+=`<span id="circuitStartHelp">${ready?'Open slots fill with eligible bots before check-in.':'The tournament starts at its scheduled time.'}</span>`;}
  if(t.status==='ACTIVE'&&team){const next=t.series.find(s=>s.teamIds.includes(team.id)&&playable(t,s)),waitingTie=t.series.find(s=>s.teamIds.includes(team.id)&&aggregate(t,s)&&tied(s)),eliminated=t.series.some(s=>s.winnerTeamId&&s.teamIds.includes(team.id)&&s.winnerTeamId!==team.id);actions=`<button class="primary" data-circuit-action="play" ${next?'':'disabled aria-describedby="circuitActionHelp"'}>PLAY NEXT GAME</button>`;explanation=next?'Your next series is ready.':waitingTie?tieLabel(waitingTie):eliminated?'Your team has been eliminated. Follow the remaining series below.':'Waiting for the opposing team’s series to finish.';}
  if(!open&&!team)explanation=t.status==='ACTIVE'?'Registration is closed. Follow the bracket below.':t.status==='CANCELLED'?'This event was cancelled. Registration and play are unavailable.':'Registration is closed.';
  if(scheduled(t)&&team&&t.status==='ACTIVE')return `<section class="circuit-registration"><h3>YOUR SCHEDULED GAME</h3>${scheduledEntryPanel(t)}</section>`;
  if(scheduled(t)&&open)explanation+=' Official games open check-in automatically at their scheduled times.';
  return `<section class="circuit-registration"><h3>${team?'YOUR TEAM':'REGISTRATION'}</h3><div class="circuit-toolbar">${actions}</div><p id="circuitActionHelp" class="circuit-footnote">${explanation}</p></section>`;
 }
 function seriesCard(t,s){
  const winner=resolvedWinner(t,s),teams=s.teamIds.map(id=>t.teams.find(team=>team.id===id)),participants=teams.flatMap(team=>(team?.participants||[]).map(p=>({participantId:p.id,team:team.id}))),presentation=window.SARTeamPresentation?.create({mode:'tdm',teamIds:s.teamIds,participants,viewerId:account()?.id}),name=(team,index)=>{const display=team?presentation?.team(team.id):null;return `<span class="circuit-series-team" ${winner&&winner===team?.id?'data-winner="true"':''} ${display?'data-side="'+safe(display.side)+'"':''}>${safe(team?.name||'Awaiting winner')}${display?'<small>'+safe(display.label)+'</small>':''}</span>`;};
  const isAggregate=aggregate(t,s),score=isAggregate?(s.aggregateKills||[0,0]):(s.wins||[0,0]),required=requiredGames(s),completed=s.completedGames??s.games?.length??0,remaining=s.remainingGames??Math.max(0,required-completed);
  const gameScores=s.games?.length?`<table class="circuit-game-kills"><caption>Recorded game kills</caption><thead><tr><th scope="col">Team</th>${s.games.map((g,i)=>'<th scope="col" title="Game '+(i+1)+'">G'+(i+1)+'</th>').join('')}</tr></thead><tbody>${teams.map((team,index)=>'<tr><th scope="row">'+safe(team?.name||'Awaiting winner')+'</th>'+s.games.map(g=>'<td>'+safe(Number.isInteger((g.teamKills||g.score)?.[index])?(g.teamKills||g.score)[index]:'—')+'</td>').join('')+'</tr>').join('')}</tbody></table>`:'';
  const progress=isAggregate?`<span>${completed} / ${required} games complete · ${remaining} remaining</span>`:'';
  const outcome=winner?'<span class="circuit-winner">Winner · '+safe(t.teams.find(team=>team.id===winner)?.name||'Recorded team')+(s.advancement?.criterion==='total-team-damage'?' · total damage '+s.advancement.aggregateDamage.map(n=>Math.round(n).toLocaleString()).join(' — '):'')+'</span>':isAggregate&&tied(s)?'<span class="circuit-tie" role="status">'+safe(tieLabel(s))+'</span>':!s.teamIds.every(Boolean)?'<span>Waiting for the previous round</span>':!isAggregate?'<span>'+(s.games?.length||0)+' completed '+(s.games?.length===1?'game':'games')+'</span>':'';
  return `<article class="circuit-series" data-series="${safe(s.id)}" data-round="${safe(s.round)}" data-status="${winner?'COMPLETED':isAggregate&&tied(s)?'AWAITING_TIE_POLICY':s.teamIds.every(Boolean)?'READY':'PENDING'}"><small>${({QF:'QUARTERFINAL',SF:'SEMIFINAL',FINAL:'FINAL'})[s.round]||safe(s.round)} · ${isAggregate?required+'-game aggregate kills':'Historical · BO'+safe(s.bestOf)}</small><strong>${name(teams[0],0)}<b aria-label="${isAggregate?'Total team kills':'Series score'} ${safe(score[0])} to ${safe(score[1])}">${safe(score[0])} — ${safe(score[1])}</b>${name(teams[1],1)}</strong>${gameScores}${progress}<span class="circuit-series-state">${safe(seriesState(t,s))}</span>${outcome}</article>`;
 }
 function resolvedWinner(t,s){if(!s.winnerTeamId||!s.teamIds.includes(s.winnerTeamId))return null;if(!aggregate(t,s))return s.winnerTeamId;return !tied(s)&&(s.games?.length||0)>=requiredGames(s)&&(s.completedGames??s.games?.length??0)>=requiredGames(s)&&s.status==='complete'&&s.advancement?.status==='decided'?s.winnerTeamId:null;}
 function seriesState(t,s){const schedule=state.details[t.id]?.data?.presentation?.schedule,live=schedule?.liveGames?.find(g=>g.seriesId===s.id),scheduled=schedule?.seriesGames?.find(g=>g.seriesId===s.id&&g.state!=='FINALIZED');return live?({countdown:'Pre-match countdown',active:'Playing',playing:'Playing',finalized:'Finalized'})[live.status]||live.status:resolvedWinner(t,s)?'Finalized':tied(s)?(s.advancement?.criterion==='explicit-ruling-required'?'Awaiting explicit ruling':'Awaiting tie policy'):!s.teamIds.every(Boolean)?'Waiting for opponents':scheduled?(scheduled.conflict?'Schedule conflict · ':'')+String(scheduled.state||'Scheduled').replaceAll('_',' ').toLowerCase():s.games?.length?'Waiting for next game':'Ready';}
 function liveGameLabel(t,g){const s=t.series.find(s=>s.id===g.seriesId),number=g.gameId?.match(/:game(\d+)$/)?.[1],pair=s?.teamIds.map(id=>t.teams.find(team=>team.id===id)?.name||'Awaiting winner').join(' / ');return (s?publicState(s.round)+' · ':'')+(pair?pair+' · ':'')+(number?'Game '+number:'Live game');}
 function schedulePanel(t){
  const entry=state.details[t.id],schedule=entry?.data?.presentation?.schedule;
  const rows=(schedule?.rounds||[]).map(r=>'<tr><th scope="row">'+safe(({QF:'Quarterfinals',SF:'Semifinals',FINAL:'Final'})[r.round]||r.name||r.round)+'</th><td>'+safe(scheduledDate(r.startsAt,schedule.timezone))+'</td><td>'+safe(scheduledDate(r.endsAt,schedule.timezone))+'</td></tr>').join('');
  const gameRows=(schedule?.seriesGames?.length?schedule.seriesGames:schedule?.games||[]).map(g=>{const series=t.series.find(s=>s.id===g.seriesId),pair=series?.teamIds.map(id=>t.teams.find(team=>team.id===id)?.name||'Awaiting winner').join(' / ');return '<tr><th scope="row">'+safe((pair?pair+' · ':'')+g.round+' G'+g.gameNumber)+'</th><td>'+safe(g.checkInOpenAt?scheduledDate(g.checkInOpenAt,schedule.timezone,true):'—')+'</td><td>'+safe(g.checkInCloseAt?scheduledDate(g.checkInCloseAt,schedule.timezone,true):'—')+'</td><td>'+safe(g.matchStartAt?scheduledDate(g.matchStartAt,schedule.timezone,true):'—')+'</td><td>'+safe(g.conflict?'Schedule conflict':g.state?.replaceAll('_',' ').toLowerCase()||'Scheduled')+'</td></tr>';}).join('');
  return '<section class="circuit-schedule-section"><h3>SCHEDULE</h3><p class="circuit-footnote">Saved event start · '+safe(scheduledDate(schedule?.eventStartsAt||t.startsAt,schedule?.timezone))+' · '+safe(schedule?.timezone||zone())+'</p>'+(schedule?.status==='confirmed'&&rows?'<table class="circuit-schedule-table"><thead><tr><th>Round</th><th>Start</th><th>End</th></tr></thead><tbody>'+rows+'</tbody></table>':'<p class="circuit-footnote" data-schedule-state="'+safe(schedule?.status||'loading')+'">'+safe(t.status==='COMPLETED'?'Historical round and check-in timestamps are unavailable in this record.':schedule?.message||(entry?.loaded?'No fixed round timetable is available.':entry?.error||'Loading schedule details…'))+'</p>')+(schedule?.status==='confirmed'&&gameRows?'<div class="circuit-table-wrap" data-circuit-scroll="schedule"><table class="circuit-schedule-table"><thead><tr><th>Pairing / game</th><th>Check-in opens</th><th>Check-in closes</th><th>Match starts</th><th>State</th></tr></thead><tbody>'+gameRows+'</tbody></table></div>':'')+(schedule?.liveGames?.length?'<div class="circuit-live-games">'+schedule.liveGames.map(g=>'<p><b>'+safe(liveGameLabel(t,g))+'</b> · '+safe(publicState(g.status))+(Number.isFinite(g.countdownRemainingMs)&&g.status==='countdown'?' · '+Math.ceil(g.countdownRemainingMs/1000)+'s countdown':'')+(Array.isArray(g.score)?' · '+g.score.map(safe).join(' — '):'')+(Number.isFinite(g.elapsedMs)?' · '+Math.floor(g.elapsedMs/60000)+':'+String(Math.floor(g.elapsedMs/1000)%60).padStart(2,'0')+' elapsed':'')+'</p>').join('')+'</div>':'')+'</section>';
 }
 function overviewPanel(t,team,roster){
  const prizes=[50000,35000,20000,12500,7500,5000,2500,1000],recordedAwards=t.status==='COMPLETED'&&t.kind==='official'?t.placements.map(place=>{const members=t.teams.find(team=>team.id===place.teamId)?.participants||[],awards=t.earnings.filter(e=>members.some(p=>p.id===e.participantId));return '<li><span>Place '+safe(place.placement)+'</span><strong>'+(awards.length?[...new Set(awards.map(e=>money(e.amount)))].join(' / '):'Unavailable')+'</strong></li>';}).join(''):null,teamName=id=>safe(t.teams.find(team=>team.id===id)?.name||'Recorded team');
  return schedulePanel(t)+(t.status==='COMPLETED'&&!state.details[t.id]?.data?.presentation?.history?.available?'<p class="circuit-footnote" role="status">Historical winning team, winning roster or placement information is unavailable in this record.</p>':'')+'<div class="circuit-detail-top"><section class="circuit-prizes"><h3>IN-GAME EARNINGS <small>PER PLAYER</small></h3>'+(t.kind==='official'&&t.status==='COMPLETED'?(recordedAwards?'<ol>'+recordedAwards+'</ol><p class="circuit-footnote">Recorded in-game earnings per participant.</p>':'<p class="circuit-footnote">Historical earnings information is unavailable in this record.</p>'):t.kind==='official'?'<ol>'+prizes.map((n,i)=>'<li><span>'+['1st','2nd','3rd','4th','5th','6th','7th','8th'][i]+'</span><strong>'+money(n)+'</strong></li>').join('')+'</ol><p class="circuit-footnote">Each participant receives the full award for their team’s placement.</p>':'<p class="circuit-custom-earnings">$0 <span>PER PLAYER</span></p><p class="circuit-footnote">Custom tournaments award no earnings or official progression.</p>')+'</section>'+registration(t,team,roster)+'</div><section class="circuit-roster"><h3>TEAM ROSTERS</h3><div class="circuit-teams">'+(t.teams.map(item=>'<article '+(item.id===team?.id?'data-your-team="true"':'')+'><strong>'+safe(item.name)+' <small>'+(item.id===team?.id?'YOUR TEAM · ':'')+'SEED '+safe(item.seed)+'</small></strong><ul>'+item.participants.map(p=>'<li>'+safe(p.name)+(p.id===account()?.id?' <b>YOU</b>':'')+'</li>').join('')+'</ul><span>'+item.participants.length+' / 5 PLAYERS'+(item.participants.length===5?' · READY':' · ROSTER INCOMPLETE')+'</span></article>').join('')||'<p class="circuit-footnote">'+(t.status==='COMPLETED'?'Historical roster information is unavailable in this record.':'No teams have registered yet.')+'</p>')+'</div>'+t.invites.filter(i=>i.teamId===team?.id).map(i=>'<p class="circuit-invite">'+safe(Object.values(roster).find(p=>p.id===i.botId)?.name||i.botId)+' · '+safe(i.state)+' · '+safe(i.reason)+'</p>').join('')+'</section>'+(t.placements.length?'<section class="circuit-results-section"><h3>FINAL PLACEMENTS <small>IN-GAME EARNINGS PER PLAYER</small></h3><div class="circuit-results">'+t.placements.slice().sort((a,b)=>a.placement-b.placement).map(p=>{const players=t.teams.find(item=>item.id===p.teamId)?.participants||[],award=t.earnings.find(e=>players.some(member=>member.id===e.participantId));return '<div><strong>'+p.placement+' · '+teamName(p.teamId)+'</strong><span>'+(award?money(award.amount):t.kind==='custom'?money(0):'Award unavailable')+' <small>PER PLAYER</small></span></div>';}).join('')+'</div></section>':'');
 }
 function bracketPanel(t,matches){
  const watch=matches.map(m=>'<button data-circuit-action="watch" data-match="'+safe(m.id)+'">WATCH LIVE MATCH</button>').join('');
  if(!t.series.length)return '<section class="circuit-bracket-section"><h3>BRACKET</h3><p class="circuit-footnote">'+(t.status==='COMPLETED'?'Historical bracket records are unavailable for this completed event.':'The bracket has not been allocated. Eight complete teams are required before the authoritative event starts.')+'</p></section>';
  const order={QF:4,SF:2,FINAL:1},complete=Object.entries(order).every(([round,n])=>t.series.filter(s=>s.round===round).length===n),roundName={QF:'Quarterfinals',SF:'Semifinals',FINAL:'Final'};
  return '<section class="circuit-bracket-section"><div class="circuit-section-heading"><h3>BRACKET</h3>'+watch+'</div>'+(t.status==='ACTIVE'&&!matches.length?'<p class="circuit-footnote">No live match is currently available to watch on this device. Series results update here.</p>':'')+(complete?'<div class="circuit-bracket-connected">'+Object.keys(order).map(round=>'<section class="circuit-bracket-round" data-round="'+round+'"><h4>'+roundName[round]+'</h4><div class="circuit-round-nodes">'+t.series.filter(s=>s.round===round).map((s,i)=>'<div class="circuit-bracket-node" data-node="'+i+'">'+seriesCard(t,s)+'</div>').join('')+'</div></section>').join('')+'</div>':'<p class="circuit-footnote">Showing all available saved series. The complete bracket is unavailable in this record.</p><div class="circuit-bracket">'+t.series.map(s=>seriesCard(t,s)).join('')+'</div>')+'</section>';
 }
 const statValue=(value,key)=>value==null?'—':key==='accuracy'?Number(value).toFixed(1)+'%':key==='kd'?(value===Infinity?'∞':Number(value).toFixed(2)):Number(value).toLocaleString([],{maximumFractionDigits:key==='damage'?0:2});
 function leaderboard(t,type){
  const entry=state.details[t.id],rows=entry?.data?.presentation?.[type==='teams'?'teamLeaderboard':'playerLeaderboard'],sort=state.sort[type];
  if(!rows)return '<p class="circuit-footnote" role="status">'+safe(entry?.error||(entry?.loaded?'Tournament-only statistics are unavailable in this record.':'Loading tournament-only statistics…'))+'</p>';
  if(!rows.length)return '<p class="circuit-footnote">No tournament statistics have been recorded yet.</p>';
  const fields=type==='teams'?[['name','Team / roster'],['round','Round'],['status','Status'],['games','Games'],['aggregateKills','Agg. kills'],['deaths','Deaths'],['assists','Assists'],['kd','K/D'],['damage','Damage'],['accuracy','Acc.'],['headshots','HS kills']]:[['name','Player / bot'],['teamName','Team'],['games','Games'],['kills','Kills'],['deaths','Deaths'],['assists','Assists'],['kd','K/D'],['damage','Damage'],['accuracy','Acc.'],['headshots','HS kills']];
  const sorted=rows.slice().sort((a,b)=>{const x=a[sort.key],y=b[sort.key];if(x==null&&y!=null)return 1;if(y==null&&x!=null)return -1;const result=typeof x==='number'&&typeof y==='number'?x-y:String(x??'').localeCompare(String(y??''),undefined,{numeric:true});return result*(sort.direction==='asc'?1:-1)||String(a.teamId||a.participantId).localeCompare(String(b.teamId||b.participantId));});
  return (entry.error?'<p class="circuit-notice" role="status">'+safe(entry.error)+' · Showing saved statistics.</p>':'')+'<p class="circuit-footnote">Tournament-only records · '+(type==='teams'?'Aggregate kills include recorded games and current live scores.':'Individual performance comes from recorded participant results.')+' — means unavailable.</p><div class="circuit-table-wrap" data-circuit-scroll="'+type+'"><table class="circuit-leaderboard" data-leaderboard="'+type+'"><thead><tr>'+fields.map(([key,label])=>'<th scope="col"'+(sort.key===key?' aria-sort="'+(sort.direction==='asc'?'ascending':'descending')+'"':'')+'><button data-circuit-action="sort-'+type+'" data-value="'+key+'">'+label+(sort.key===key?' <span aria-hidden="true">'+(sort.direction==='asc'?'↑':'↓')+'</span>':'')+'</button></th>').join('')+'</tr></thead><tbody>'+sorted.map(row=>'<tr data-participant="'+safe(row.participantId||'')+'" data-team="'+safe(row.teamId||'')+'">'+fields.map(([key])=>key==='name'?'<th scope="row">'+safe(row.name||'Identity unavailable')+(type==='teams'?'<small>'+(row.roster||[]).map(p=>safe(p.name||p.id)).join(', ')+'</small>':'<small>'+safe(row.kind==='bot'?'BOT':row.kind==='user'?'PLAYER':'Recorded participant')+(row.participantId===account()?.id?' · YOU':'')+'</small>')+'</th>':'<td>'+(['teamName','round','status'].includes(key)?safe(key==='teamName'?row[key]||'Team unavailable':publicState(row[key])):safe(key==='kd'&&row.zeroDeaths?'∞':statValue(row[key],key)))+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
 }
 function detail(t,{top=false}={}){
  if(!t){if(state.selected){modal('<button data-circuit-action="calendar">← BACK TO TOURNAMENTS</button><p role="status">'+safe(state.details[state.selected]?.error||'Loading tournament details…')+'</p>');return;}return board();}
  const history=state.details[t.id]?.data?.presentation?.history;if(!Array.isArray(t.placements))t={...t,placements:history?.placements||[]};
  state.selected=t.id;state.view='detail';const team=yours(t),roster=window.SAR?.getProfiles?.()||{},matches=liveMatches(t),tab=detailTabs.some(([id])=>id===state.detailTab)?state.detailTab:'overview';
  const panels={overview:overviewPanel(t,team,roster),bracket:bracketPanel(t,matches),teams:leaderboard(t,'teams'),players:leaderboard(t,'players')};
  modal('<div class="circuit-detail-nav"><button data-circuit-action="calendar">← BACK TO TOURNAMENTS</button><span>'+safe(t.kind==='official'?'OFFICIAL':'CUSTOM')+' · '+safe(statusLabel(t))+'</span><button data-circuit-action="refresh">REFRESH</button></div><h2 class="circuit-event-title">'+safe(title(t))+'</h2><div class="circuit-event-schedule"><time datetime="'+new Date(t.startsAt).toISOString()+'">'+safe(date(t.startsAt))+' · '+safe(zone())+'</time><strong data-circuit-clock="'+safe(t.id)+'">'+countdown(t)+'</strong></div>'+(state.lastXP?.owner===account()?.id&&state.lastXP.tournamentId===t.id?(window.SAR?.xpSummaryHtml?.(state.lastXP.receipt)||''):'')+'<div class="circuit-format"><span><b>'+t.teams.length+' / 8</b> TEAMS</span><span>5 PLAYERS PER TEAM</span><span>'+(aggregateAtStart(t)?'QUARTERFINALS / SEMIFINALS: 3-game aggregate kills · FINAL: 5-game aggregate kills':'HISTORICAL FORMAT · QUARTERFINALS / SEMIFINALS BO3 · FINAL BO5')+'</span></div>'+notice()+(state.details[t.id]?.error?'<p class="circuit-notice" role="status">'+safe(state.details[t.id].error)+'</p>':'')+'<div class="circuit-tabs" role="tablist" aria-label="Tournament sections">'+detailTabs.map(([id,label])=>'<button role="tab" id="circuit-tab-button-'+id+'" aria-controls="circuit-tab-'+id+'" aria-selected="'+(tab===id)+'" data-circuit-action="detail-tab" data-value="'+id+'">'+label+'</button>').join('')+'</div>'+detailTabs.map(([id])=>'<section role="tabpanel" id="circuit-tab-'+id+'" aria-labelledby="circuit-tab-button-'+id+'"'+(tab!==id?' hidden':'')+'>'+panels[id]+'</section>').join('')+(canDelete(t)?'<div class="circuit-delete"><button data-circuit-action="delete">'+(t.status==='ACTIVE'?'CANCEL / DELETE CUSTOM TOURNAMENT':'DELETE CUSTOM TOURNAMENT')+'</button></div>':''),{top});
 }
 function create(){state.selected=null;state.view='create';modal('<div class="circuit-detail-nav"><button data-circuit-action="calendar">← BACK TO TOURNAMENTS</button></div><div class="eyebrow">CUSTOM EVENT</div><h2>CREATE TOURNAMENT</h2><div class="circuit-create"><label>NAME<input id="circuitName" maxlength="80" value="Custom Circuit"></label><label>START<select id="circuitStartOption"><option value="now">WHEN TEAMS ARE READY</option><option value="scheduled">SCHEDULED TIME</option></select></label><label>LOCAL START TIME<input id="circuitTime" type="datetime-local" disabled></label><p>'+safe(zone())+' · Eight teams · five players per team<br>Quarterfinals / semifinals: 3-game aggregate kills<br>Final: 5-game aggregate kills<br>All scheduled games count; higher total team kills advances<br>No in-game earnings or official progression</p><button class="primary" data-circuit-action="save-custom">CREATE TOURNAMENT</button><p id="circuitError" role="status"></p></div>',{top:true});}
 document.addEventListener('change',event=>{if(event.target.id==='circuitStartOption')document.getElementById('circuitTime').disabled=event.target.value!=='scheduled';});
 document.addEventListener('click',async event=>{
  const selected=event.target.closest('[data-circuit-event]')?.dataset.circuitEvent;if(selected){await openEvent(selected);return;}
  const day=event.target.closest('[data-circuit-day]')?.dataset.circuitDay;if(day){state.selectedDate=state.selectedDate===day?null:day;board();return;}
  const button=event.target.closest('[data-circuit-action]');if(!button||button.disabled)return;const action=button.dataset.circuitAction;
  if(action==='calendar'){board({top:true});return;}if(action==='create'){create();return;}if(action==='clear-date'){state.selectedDate=null;board();return;}
  if(action==='filter-kind'||action==='filter-status'){const field=action.slice(7),values=field==='kind'?['all','official','custom']:['all','upcoming','live','completed','cancelled'];if(values.includes(button.dataset.value)){state[field]=button.dataset.value;state.selectedDate=null;}board();return;}
  if(action==='detail-tab'){if(detailTabs.some(([id])=>id===button.dataset.value)){state.detailTab=button.dataset.value;detail(state.events.find(t=>t.id===state.selected)||state.details[state.selected]?.data?.tournament);}return;}
  if(action==='sort-teams'||action==='sort-players'){const type=action.slice(5),sort=state.sort[type],key=button.dataset.value;state.sort[type]={key,direction:sort.key===key&&sort.direction==='desc'?'asc':'desc'};detail(state.events.find(t=>t.id===state.selected)||state.details[state.selected]?.data?.tournament);return;}
  if(action==='today'){const current=new Date(now());state.month=new Date(current.getFullYear(),current.getMonth(),1);state.selectedDate=null;board();return;}
  if(action==='previous'||action==='next'){state.month=new Date(state.month.getFullYear(),state.month.getMonth()+(action==='next'?1:-1),1);state.selectedDate=null;board();return;}
  if(action==='refresh'){await refresh();return;}
  if(state.mutating)return;const owner=account()?.id,epoch=state.epoch;state.mutating=true;button.disabled=true;
  try{
   const id=state.selected,current=state.events.find(e=>e.id===id);let data;
   if(action==='save-custom'){const name=document.getElementById('circuitName').value.trim(),startsAt=document.getElementById('circuitStartOption').value==='now'?now():new Date(document.getElementById('circuitTime').value).getTime();if(!name||!Number.isFinite(startsAt)||startsAt<now()-60000)throw new Error('Enter a name and a valid local start time.');data=await api('/tournaments',{name,startsAt});}
   else if(action==='delete'){if(!current||!canDelete(current))return;if(!confirm((current.status==='ACTIVE'?'Cancel all active games and delete ':'Delete ')+current.name+'? This cannot be undone.'))return;await window.SARCloud.api('/tournaments/'+id,{method:'DELETE',body:JSON.stringify({confirmedName:current.name})});if(owner!==account()?.id||epoch!==state.epoch)return;window.SAR?.cancelTournament?.(id);let pending;try{pending=JSON.parse(localStorage.getItem(pendingKey())||'null');}catch{}if(pending?.context?.tournamentId===id)localStorage.removeItem(pendingKey());state.events=state.events.filter(e=>e.id!==id);state.selected=null;state.view='board';cache();board();return;}
   else if(action==='join')data=await api('/tournaments/'+id+'/team',{name:account().username+' Circuit'});
   else if(action==='invite')data=await api('/tournaments/'+id+'/invite',{teamId:button.dataset.team,botId:document.getElementById('circuitBot').value});
   else if(action==='start')data=await api('/tournaments/'+id+'/start',{});
   else if(action==='check-in'){data=await api('/tournaments/'+id+'/check-in',{gameId:button.dataset.game});if(!data?.tournament){await refresh();return;}}
   else if(action==='scheduled-play'){await prepareScheduledGame(current,gameRows(current).find(g=>g.gameId===button.dataset.game),{manual:true});return;}
   else if(action==='play'){if(!current||!current.series.some(s=>s.teamIds.includes(yours(current)?.id)&&playable(current,s)))throw new Error('No scheduled game is ready for your team.');data=await api('/tournaments/'+id+'/play',{});if(owner===account()?.id&&epoch===state.epoch){if(window.SAR.beginTournamentEntry)await window.SAR.beginTournamentEntry(data.context,{cancel:()=>detail(current)});else window.SAR.startTournamentGame(data.context);}return;}
   else if(action==='watch'){const match=liveMatches(current).find(m=>String(m.id)===button.dataset.match);if(!match)throw new Error('That match is no longer available to watch.');if(!window.SARPhone?.openSpectate)throw new Error('Open Phone to view available matches.');await window.SARPhone.openSpectate({tournamentId:id,matchId:match.id});return;}
   if(owner!==account()?.id||epoch!==state.epoch)return;
   if(data?.tournament){const index=state.events.findIndex(t=>t.id===data.tournament.id);if(index>=0)state.events[index]=data.tournament;else state.events.push(data.tournament);state.error='';cache();detail(data.tournament,{top:action==='save-custom'});void refreshDetail(data.tournament.id,{force:true});autoEntry();}
  }catch(e){if(owner!==account()?.id||epoch!==state.epoch)return;state.error=e.message;const out=document.getElementById('circuitError');if(out)out.textContent=e.message;else if(state.selected)detail(state.events.find(t=>t.id===state.selected));else board();}
  finally{state.mutating=false;button.disabled=false;}
 });
 function acceptedResult(pending,tournament){
  const game=tournament?.series?.find(series=>series.id===pending.context.seriesId)?.games?.find(game=>game.id===pending.result.id);
  const stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])])):value;
  const fields=['id','matchId','mode','sessionType','eligible','aiRevision','balanceVersion','balanceFingerprint','winnerTeamId','score','duration','mapId','calibrationId','distanceUnit','stats'];
  if(!game||tournament.id!==pending.context.tournamentId||tournament.kind!=='official'||tournament.status==='CANCELLED'||fields.some(key=>JSON.stringify(stable(game[key]))!==JSON.stringify(stable(pending.result[key]))))throw Error('The service has not accepted this exact saved game. Its recovery copy is retained.');
  return game;
 }
 async function flushResult(){
  if(state.flushing||window.SARCloud?.state.tournamentResetBlocked)return;const owner=account()?.id,storageKey=pendingKey();let pending;try{pending=JSON.parse(localStorage.getItem(storageKey)||'null');}catch{return;}if(!pending)return;state.flushing=true;
  try{const data=await api('/tournaments/'+pending.context.tournamentId+'/result',{seriesId:pending.context.seriesId,result:pending.result,...(pending.context.leaseToken?{leaseToken:pending.context.leaseToken,clientId:pending.clientId||clientId()}: {})});if(owner!==account()?.id)return;if(pending.context.schedule&&pending.context.tournamentKind==='official'){const game=acceptedResult(pending,data.tournament);if(!window.SAR?.acceptTournamentXP)throw Error('Tournament progression is still loading.');const receipt=await window.SAR.acceptTournamentXP(pending.context,game,pending.rewardSnapshot);if(owner!==account()?.id)return;state.lastXP={owner,tournamentId:pending.context.tournamentId,receipt};}localStorage.removeItem(storageKey);window.SARStorage?.remove?.(checkpointKey(owner,pending.context.gameId));activeLease=null;state.events=state.events.filter(t=>t.id!==data.tournament.id).concat(data.tournament);state.error='';cache();if(viewing())detail(data.tournament);void refreshDetail(data.tournament.id,{force:true});}
  catch(e){if(owner!==account()?.id)return;if((e.status===410||e.status===404)&&!pending.context.schedule){localStorage.removeItem(storageKey);window.SAR?.cancelTournament?.(pending.context.tournamentId);state.selected=null;state.view='board';void refresh();return;}state.error='RESULT SAVED LOCALLY · '+e.message;if(viewing())detail(state.events.find(t=>t.id===pending.context.tournamentId));}
  finally{state.flushing=false;}
 }
 function loadCache(){if(window.SARCloud?.state.tournamentResetBlocked){state.events=[];state.details={};state.history=[];state.earnings=[];state.error='Tournament recovery is retained; cleanup will retry.';return;}state.error='';state.loaded=false;state.connection=window.SARCloud?.state.available===false?'offline':'loading';state.history=[];state.details={};try{const cached=JSON.parse(localStorage.getItem(key())||'null');if(cached){state.loaded=true;state.events=Array.isArray(cached.tournaments)?cached.tournaments:[];state.earnings=Array.isArray(cached.earnings)?cached.earnings:[];state.history=Array.isArray(cached.officialHistory)?cached.officialHistory:[];state.details=cached.details&&typeof cached.details==='object'?cached.details:{};for(const entry of Object.values(state.details))entry.loading=false;}else{state.events=[];state.earnings=[];}}catch{state.events=[];state.earnings=[];}if(state.connection==='offline')state.error=state.loaded?'Offline — showing saved tournament records.':'Offline — reconnect to load the tournament calendar.';window.SAR?.syncTournamentReservations?.(state.events);}
 function init(){const owner=account()?.id;if(!owner||state.owner===owner)return;state.owner=owner;state.epoch++;activeLease=null;entryAttempt=null;state.entrySuppressed=null;state.selected=null;state.selectedDate=null;state.view='board';state.detailTab='overview';if(!window.SARCloud?.state.tournamentResetBlocked)loadCache();else{state.events=[];state.details={};state.history=[];state.earnings=[];state.error='Tournament recovery is retained; cleanup will retry.';}if(window.SARCloud.state.available)void refresh();}
 function show(){state.epoch++;loadCache();board({top:true});void refresh();}
 window.SARTournaments={show,init,checkpoint,getState:()=>state,onAbandon:context=>{if(context?.schedule){state.entrySuppressed=context.gameId;activeLease=null;}show();state.error=context?.schedule?'Scheduled game left. Its saved recovery state is retained; the tournament schedule does not move.':'Game left. You can replay the uncompleted tournament game.';board();},onResult:(context,result,rewardSnapshot=null)=>{activeLease=null;state.lastXP={owner:account()?.id,tournamentId:context.tournamentId,receipt:result.xp};const previous=localStorage.getItem(pendingKey());if(previous){const saved=JSON.parse(previous);if(saved.result.id!==result.id)localStorage.setItem(pendingKey()+'.retained.'+saved.result.id,previous);}localStorage.setItem(pendingKey(),JSON.stringify({context,result,rewardSnapshot,clientId:clientId()}));state.selected=context.tournamentId;state.error='SAVING RESULT…';detail(state.events.find(t=>t.id===context.tournamentId));void flushResult();}};
 window.SARTournaments.resetForUpdate=()=>{
  state.epoch++;const active=window.SAR?.getActiveTournament?.();activeLease=null;entryAttempt=null;
  if(active){window.SARModeEntry?.cancel({restore:false});window.SAR?.cancelTournament?.(active);}
  state.events=[];state.history=[];state.details={};state.earnings=[];state.owner=null;
  state.selected=null;state.selectedDate=null;state.entrySuppressed=null;state.view='board';state.detailTab='overview';state.loaded=false;state.error='';state.lastRefresh=0;
  window.SAR?.syncTournamentReservations?.([]);if(viewing())board({top:true});
 };
 window.addEventListener?.('pagehide',()=>{void checkpoint().catch(error=>console.error('Tournament checkpoint:',error.message));});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)void checkpoint().catch(error=>console.error('Tournament checkpoint:',error.message));});
 setInterval(()=>{if(account()&&window.SARCloud?.state.available)void heartbeat();},1000);
 setInterval(()=>{if(viewing()&&!document.hidden){for(const el of document.querySelectorAll('[data-circuit-clock]')){const t=state.events.find(t=>t.id===el.dataset.circuitClock);if(t)el.textContent=countdown(t);}}if(account()&&window.SARCloud.state.available&&localStorage.getItem(pendingKey()))void flushResult();if(account()&&window.SAR&&window.SARCloud.state.available&&Date.now()-state.lastRefresh>=5000)void refresh();},5000);
})();
