'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto'),vm=require('node:vm');
const {engine}=require('./simulate.cjs'),root=path.resolve(__dirname,'..'),source=fs.readFileSync(path.join(root,'game.js'),'utf8');
const injected=source.replace('window.SAR = {','window.__SIX={updateBurst,makeWeaponState,startReload,updateHandlingAudio,finishReload,updatePresentation,footstepSurface,impactMaterial,launchPlayerMatch,weaponSheet,WEAPON_PATCH_NOTES};window.SAR = {');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'assets/audio/LICENSES.json'),'utf8')),checks=[];
const pass=name=>{checks.push(name);console.log('PASS '+name);},near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,a+' != '+b);
function game(){const e=engine({},injected),events=[];e.context.SARAudio={emit:event=>events.push(event),flush(){}};e.events=events;e.six=e.context.__SIX;return e;}
{
 const e=game(),names=Object.keys(e.context.SAR.getWeapons());assert.equal(names.length,15);assert.deepEqual(Object.keys(manifest.weapons),names);const licensed=new Set(manifest.sources.filter(s=>s.license==='CC0-1.0'&&s.filename&&s.source&&s.sourceURL&&s.licenseURL).map(s=>s.id));assert.equal(licensed.size,manifest.sources.length);
 for(const [id,a] of Object.entries(manifest.assets)){assert.ok(licensed.has(a.source),id);const bytes=fs.readFileSync(path.join(root,'assets/audio',a.file));assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),a.sha256,id);assert.ok(a.peak<.98&&a.peak>0&&a.duration>0,id);assert.ok(!a.file.startsWith('source/'));}
 for(const name of names){const w=manifest.weapons[name];assert.ok(w.fire.length>=2&&w.fire.length<=4,name);assert.equal(new Set(w.fire.map(id=>manifest.assets[id].sha256)).size,w.fire.length,name+' distinct recordings');assert.equal(w.pump,name==='Pump Shotgun');}
 pass('All 15 canonical weapons have four distinct, bounded-peak samples with verified CC0 provenance and exact asset hashes');
 const actor=e.dev.inspect().state.actors[0],state=e.dev.inspect().state;let lane;
 for(let y=100;y<2200&&!lane;y+=80)for(let x=100;x<3500&&!lane;x+=80)if(!e.dev.collides(x,y)&&e.dev.pathClear(x,y,x+220,y))lane={x,y};assert.ok(lane);Object.assign(actor,lane);actor.dead=false;
 for(const [name,w] of Object.entries(e.context.SAR.getWeapons())){actor.slots[0]=e.six.makeWeaponState(name);actor.currentSlot=0;state.projectiles=[];e.events.length=0;assert.equal(e.dev.fire(actor,0,e.dev.now()+5000),true);const rounds=w.burstCount||1;if(rounds>1){e.six.updateBurst(actor,e.dev.now()+5130);assert.deepEqual(e.events.filter(x=>x.type==='shot').map(x=>x.time),[e.dev.now()+5000,e.dev.now()+5065,e.dev.now()+5130]);assert.equal(state.projectiles.length,3);}else assert.equal(state.projectiles.length,w.pellets);
  assert.equal(e.events.filter(x=>x.type==='shot').length,rounds,name+' sound per real round/shell');
 }
 pass('Actual firing emits one sound per single round or shotgun shell and three SR-Aug events at 0/65/130 ms');
}
for(const human of [true,false]){
 const e=game(),{state,meta,SAVE}=e.dev.inspect(),owner=state.actors.find(a=>a.matchId===0&&a.team===0),victim=state.actors.find(a=>a.matchId===0&&a.team===1);for(const a of state.actors)if(a!==owner&&a!==victim)a.dead=true;
 let lane;for(let y=100;y<2200&&!lane;y+=80)for(let x=100;x<3500&&!lane;x+=80)if(!e.dev.collides(x,y)&&[-35,0,35].every(o=>e.dev.pathClear(x,y+o,x+200,y+o)))lane={x,y};assert.ok(lane);
 Object.assign(owner,{x:lane.x,y:lane.y,isPlayer:human,dead:false,currentSlot:0});Object.assign(victim,{x:lane.x+120,y:lane.y,dead:false,hp:250});assert.ok(e.dev.pathClear(lane.x,lane.y,lane.x+200,lane.y));owner.slots[0]=e.six.makeWeaponState('SPAS-12');state.projectiles=[];
 assert.equal(e.dev.fire(owner,0,e.dev.now()+1000),true);assert.equal(state.projectiles.length,12);const offsets=[0,0,0,0,12,12,12,-12,-12,-12,30,-30];
 for(let i=0;i<12;i++)Object.assign(state.projectiles[i],{x:lane.x+30,y:lane.y+offsets[i],vx:1000,vy:0,travel:30});
 const spas=e.context.SAR.getWeapons()['SPAS-12'],mixedDamage=(4*spas.head+6*spas.damage)/spas.pellets;
 e.dev.updateProjectiles(.14,e.dev.now()+1200);near(victim.hp,250-mixedDamage);near(meta['SPAS-12'].damage,mixedDamage);assert.equal(meta['SPAS-12'].shots,1);assert.equal(meta['SPAS-12'].hits,1);assert.equal(victim.dead,false);
 const hits=e.events.filter(x=>x.type==='resolved-hit');assert.equal(hits.length,human?10:0);if(human){assert.equal(hits.filter(x=>x.head).length,4);near(hits.reduce((n,h)=>n+h.damage,0),mixedDamage);}assert.equal(e.events.filter(x=>x.type==='shot').length,1);
 // Straight center/body/miss paths exercise existing physical head radius for both humans and bots.
 for(const [offset,damage,head] of [[0,42,true],[12,28,false],[30,0,false]]){state.projectiles=[];victim.dead=false;victim.hp=250;owner.slots[0]=e.six.makeWeaponState('AR-15');e.events.length=0;e.dev.fire(owner,0,e.dev.now()+3000);Object.assign(state.projectiles[0],{x:lane.x+30,y:lane.y+offset,vx:1000,vy:0,travel:30});e.dev.updateProjectiles(.14,e.dev.now()+3200);near(250-victim.hp,damage);if(human&&damage)assert.equal(e.events.find(x=>x.type==='resolved-hit').head,head);}
 victim.hp=4;victim.dead=false;state.projectiles=[];owner.slots[0]=e.six.makeWeaponState('AR-15');e.events.length=0;e.dev.fire(owner,0,e.dev.now()+4000);Object.assign(state.projectiles[0],{x:lane.x+30,y:lane.y+12,vx:1000,vy:0,travel:30});e.dev.updateProjectiles(.14,e.dev.now()+4200);assert.equal(victim.hp,0);if(human){const hit=e.events.find(x=>x.type==='resolved-hit');assert.equal(hit.damage,4);assert.equal(hit.killing,true);}
 assert.ok(SAVE.bots[owner.name].career.weaponUsage['SPAS-12']);
}
pass('Real head/body/miss collisions match damage for bots and humans; mixed SPAS pellets use authoritative damage, overkill feedback uses 4 HP');
{
 const e=game(),old=JSON.parse(JSON.stringify(e.context.SAR.getUniverse())),fixture=require('./fixtures/balance-5.0.json'),active=JSON.parse(JSON.stringify(old.patchState)),activeWeapons=JSON.parse(JSON.stringify(e.context.SAR.getWeapons()));
 old.patchState.weaponStats=fixture.balance;old.patchState.fingerprint=fixture.fingerprint;old.patchState.id=fixture.fingerprint+'-1';old.patchState.label='WEAPON BALANCE UPDATE 5.0';old.patchState.meta['AR-15'].kills=7;old.patchState.meta['AR-15'].damage=321;delete old.patchState.meta['SPAS-12'];old.meta=old.patchState.meta;old.bots.Ace.career.kills=123;old.bots.Ace.familiarity['AR-15']=.65;old.playerCareer.kills=42;old.playerCareer.weapons['AR-15'].k=19;
 const before=JSON.parse(JSON.stringify(old)),after=e.dev.normalizeSave(old);assert.equal(after.patchArchives.length,before.patchArchives.length+1);const archive=after.patchArchives.at(-1);for(const key of ['id','weaponStats','meta','perBot','skillStrata','completedMatches','observedSeconds'])assert.deepEqual(archive[key],before.patchState[key]);assert.equal(after.patchState.label,active.label);assert.equal(after.patchState.fingerprint,active.fingerprint);assert.deepEqual(JSON.parse(JSON.stringify(e.context.SAR.getWeapons())),activeWeapons,'audio routing and historical migration preserve current weapon constants');for(const m of Object.values(after.patchState.meta))assert.equal(m.shots+m.kills+m.deaths+m.damage+m.equippedTime,0);assert.deepEqual(after.playerCareer,before.playerCareer);for(const [name,b] of Object.entries(before.bots)){assert.deepEqual(after.bots[name].career,b.career);assert.deepEqual(after.bots[name].familiarity,b.familiarity);}assert.deepEqual(after.seasons,before.seasons);assert.deepEqual(after.playerSeasons,before.playerSeasons);assert.deepEqual(after.patchArchives.slice(0,-1),before.patchArchives);
 const historical=e.six.WEAPON_PATCH_NOTES.find(p=>p.version.endsWith('5.0'));assert.equal(historical.changes.length,13);assert.ok(historical.changes.find(c=>c.weapon==='SR-Aug').items.includes('Body / head damage 25 / 50'));near(e.six.weaponSheet('SR-Aug').bodyTtk,2.165);near(e.six.weaponSheet('SR-Aug').headTtk,1.40);near(e.six.weaponSheet('SPAS-12').bodyTtk,2);near(e.six.weaponSheet('SPAS-12').headTtk,1);
 pass('5.0 telemetry archives exactly, the current balance starts at zero, historical notes stay frozen, lifetime careers/familiarity/seasons persist, and TTK uses real cadence');
 const a=e.dev.inspect().state.actors[0];a.dead=false;a.currentSlot=0;for(const name of ['AR-15','SPAS-12','Pump Shotgun']){a.slots[0]=e.six.makeWeaponState(name);a.slots[0].ammo=0;e.events.length=0;e.six.startReload(a,10000);e.six.updateHandlingAudio(a,a.slots[0],10000+e.context.SAR.getWeapons()[name].reload*1000*.8);e.six.finishReload(a.slots[0],a);if(name==='AR-15')assert.deepEqual(e.events.map(x=>x.type),['mag-out','mag-in','reload-ready']);else{assert.equal(e.events.filter(x=>x.type==='shell-insert').length,name==='SPAS-12'?3:4);assert.ok(!e.events.some(x=>x.type==='mag-out'));}}
 assert.equal(e.six.impactMaterial({kind:'car'}),'metal');assert.equal(e.six.impactMaterial({kind:'fence'}),'wood');assert.equal(e.six.impactMaterial({kind:'building'}),'concrete');
 for(const [x,y,surface] of [[200,150,'grass'],[200,1400,'pavement'],[300,900,'indoor']]){Object.assign(a,{x,y});assert.equal(e.six.footstepSurface(a),surface);}
 pass('Reload phases use existing reload progress; SPAS shell inserts have no pump, and movement/impact categories use existing map materials');
}
async function manager(){
 const callbacks=new Map(),storage=new Map(),started=[],contexts=[];let requests=0;
 class Param{constructor(){this.value=0;}setTargetAtTime(value){this.value=value;}}
 class Node{constructor(){this.gain=new Param();this.pan=new Param();this.playbackRate=new Param();}connect(){}disconnect(){}start(){started.push(this);}stop(){this.onended?.();}}
 class Context{constructor(){this.state='suspended';this.currentTime=0;this.destination=new Node();contexts.push(this);}createGain(){return new Node();}createDynamicsCompressor(){const n=new Node();for(const p of ['threshold','knee','ratio','attack','release'])n[p]=new Param();return n;}createStereoPanner(){return new Node();}createBufferSource(){return new Node();}async decodeAudioData(){return {duration:.3};}async resume(){this.state='running';}async suspend(){this.state='suspended';}}
 const document={hidden:false,addEventListener(type,fn){callbacks.set(type,fn);}},window={AudioContext:Context,addEventListener(type,fn){callbacks.set(type,fn);},requestIdleCallback:fn=>setImmediate(fn)};const sandbox={window,document,console,crypto:crypto.webcrypto,setTimeout,Uint32Array,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},fetch:async url=>{requests++;return {ok:true,json:async()=>manifest,arrayBuffer:async()=>new ArrayBuffer(16)};}};
 vm.runInNewContext(fs.readFileSync(path.join(root,'audio.js'),'utf8'),sandbox);const audio=window.SARAudio;await audio.ready;assert.equal(audio.getDiagnostics().buffers,Object.values(manifest.assets).filter(a=>a.critical).length);assert.equal(audio.getDiagnostics().ambient,0);await callbacks.get('pointerdown')();audio.setView({active:true,matchId:0,x:0,y:0});await new Promise(r=>setImmediate(r));
 let at=started.length;for(let i=0;i<3;i++)audio.emit({type:'shot',weapon:'SPAS-12',matchId:0,x:250,y:0});assert.equal(started.length-at,3);assert.notEqual(started[at].buffer,undefined);const count=audio.getDiagnostics().played;audio.emit({type:'shot',weapon:'AR-15',matchId:1,x:0,y:0});assert.equal(audio.getDiagnostics().played,count);
 at=started.length;for(let i=0;i<12;i++)audio.emit({type:'resolved-hit',ownerId:999,feedbackId:101,targetId:3,head:i===3,killing:i===11});audio.flush();assert.equal(started.length-at,2,'one head cue + one kill for twelve pellets');audio.emit({type:'resolved-hit',ownerId:999,feedbackId:101,targetId:3,head:true,killing:true});audio.flush();assert.equal(started.length-at,2,'later frame does not replay same-shell feedback');
 for(let i=0;i<200;i++)audio.emit({type:'shot',weapon:'AR-15',matchId:0,x:i%2?-600:600,y:0});assert.ok(audio.getDiagnostics().maxVoices<=47);audio.setVolume('WEAPONS',0);at=started.length;audio.emit({type:'shot',weapon:'AR-15',matchId:0,x:0,y:0});assert.equal(started.length,at);assert.equal(JSON.parse(storage.get('sar.audio.volumes.v1')).WEAPONS,0);assert.match(audio.settingsHtml(),/data-audio-volume="MASTER"/);audio.setView({active:false,matchId:0,x:0,y:0});assert.equal(audio.getDiagnostics().ambient,0);document.hidden=true;await callbacks.get('visibilitychange')();assert.equal(contexts[0].state,'suspended');assert.equal(audio.getDiagnostics().failures.length,0);assert.ok(requests<=Object.keys(manifest.assets).length+1,'each buffer loads once');
 pass('Central mixer preloads only critical clips, caches decoding, coalesces pellets across frames, bounds voices, filters matches, persists mute, and suspends on focus loss');
 fs.writeFileSync(path.join(__dirname,'audio-results.json'),JSON.stringify({result:'PASS',checks,assets:Object.keys(manifest.assets).length,runtimeBytes:Object.values(manifest.assets).reduce((n,a)=>n+a.bytes,0),diagnostics:audio.getDiagnostics()},null,2));
}
for(const win of [true,false]){
 const e=game(),{state}=e.dev.inspect();e.six.launchPlayerMatch(3,state.actors.filter(a=>a.matchId===3));
 e.step(1.01);e.step(1);e.step(1);assert.deepEqual(e.events.filter(x=>['countdown','fight'].includes(x.type)).map(x=>x.type),['countdown','countdown','countdown','fight']);
 const human=state.actors.find(a=>a.isPlayer);e.dev.endMatch(state.matches[3],win?human.team:1-human.team);assert.equal(e.events.filter(x=>x.type===(win?'victory':'defeat')).length,1);
}
pass('Existing 3/2/1/FIGHT state transitions and actual match wins/losses emit exactly one corresponding cue');
manager().catch(error=>{console.error(error);process.exitCode=1;});
