/* Developer-only district / ADS checks. Executes the shipped code, with drawing/DOM stubbed. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {engine,migrationTests}=require('./simulate.cjs'),gamePath=path.resolve(__dirname,'../game.js'),source=fs.readFileSync(gamePath,'utf8'),checks=[];
const injected=source.replace('window.SAR = {',`window.__DISTRICT={floors,walls,solids,trees,roads,surfaces,doorZones,navigationCorridors,SPAWNS,outerWorld,MAP_REPORT,WORLD,WORLD_PAD,ACTOR_RADIUS,WEAPONS,state,input,CONFIG,collides,rectOverlap,objectBounds,findPath,buildNavigation,nav:()=>({NAV_WALKABLE,NAV_EDGES}),navigateToward,updateBot,obstacleSteer,smoothBotMove,moveWithCollision,resetBrain,buildingAt,updateBuildingContext,chooseBuildingExit,buildingExitGoal,decideBot,updateAds,botWantsAds,effectiveSpreadDeg,updateCamera,viewBounds,screenToWorld,worldToScreen,weaponSheet,weaponBars,weaponDescription,fire,tryDash,currentWeaponState,diagnostics,routeFailure(){findPath=()=>[];ROUTE_CACHE.clear();},advance(dt){simulationTime+=dt*1000;return simulationTime;},viewport(w,h){cssW=w;cssH=h;}};\nwindow.SAR = {`);
function pass(test,detail){checks.push({test,result:'PASS',detail});console.log('PASS',test,detail||'');}
const NEW_META_FIELDS=['engagementDistance','engagementDistanceN','classifiedKills','soloKills','finisherKills'];
function assertRetained(original,actual,label){for(const [key,value] of Object.entries(original)){if(value&&typeof value==='object'&&!Array.isArray(value))assertRetained(value,actual[key],label+'.'+key);else assert.deepEqual(actual[key],value,label+'.'+key);}}
function make(){const e=engine({},injected);return {e,d:e.context.__DISTRICT};}
const {e,d}=make();d.buildNavigation();
assert.equal(d.floors.length,12);assert.equal(d.roads.length,6);assert.equal(d.ACTOR_RADIUS,21);
for(const b of d.floors){for(const r of d.roads)assert.ok(!d.rectOverlap(b,r,54),b.label+' road clearance');assert.equal(b.exits.length,2);for(const ex of b.exits){assert.ok(!d.collides(ex.inside.x,ex.inside.y));assert.ok(!d.collides(ex.outside.x,ex.outside.y));assert.ok(!d.collides(ex.release.x,ex.release.y));assert.ok(d.findPath(ex.inside.x,ex.inside.y,ex.release.x,ex.release.y).length,b.label+' exit '+ex.id);}}
for(const prop of d.solids.filter(o=>!['building','perimeter','interior'].includes(o.kind))){const b=d.objectBounds(prop,true);for(const r of d.roads)assert.ok(!d.rectOverlap(b,r),prop.kind+' road overlap');for(const z of d.doorZones)assert.ok(!d.rectOverlap(b,z),prop.kind+' doorway overlap');for(const z of d.navigationCorridors)assert.ok(!d.rectOverlap(b,z),prop.kind+' corridor overlap');}
for(const p of d.SPAWNS)assert.ok(!d.collides(p.x,p.y),'spawn collision');
pass('Twelve buildings, 24 clear exits, six streets; no road/building/prop/doorway/corridor overlaps and all spawns clear',JSON.stringify({placed:d.MAP_REPORT.placed,rejected:d.MAP_REPORT.rejected,spawns:d.SPAWNS.length}));
for(const kind of ['tree','bush','crate','rock','utility','bench','car','fence'])assert.ok(d.solids.some(o=>o.kind===kind),'missing district prop '+kind);
const nav=d.nav(),walkable=nav.NAV_WALKABLE.reduce((n,v)=>n+v,0),start=nav.NAV_WALKABLE.indexOf(true),seen=new Set([start]),q=[start];for(let i=0;i<q.length;i++)for(const [j] of nav.NAV_EDGES[q[i]])if(!seen.has(j)){seen.add(j);q.push(j);}assert.equal(seen.size,walkable);pass('All intended walkable navigation regions connect',walkable+' grid cells');
const actor=d.state.actors.find(a=>!a.isPlayer&&a.matchId!==null);let maxExitTime=0,routes=0,maxRecoveries=0;
for(const b of d.floors)for(const exit of b.exits)for(const offset of [-45,0,45]){
 d.resetBrain(actor);actor.x=b.x+b.w/2+offset;actor.y=b.y+b.h/2;actor.vx=actor.vy=0;actor.target=null;actor.visibleEnemies=[];actor.visibleAllies=[];assert.ok(!d.collides(actor.x,actor.y));const dest=exit.release;let tick=0;
 for(;tick<600&&Math.hypot(actor.x-dest.x,actor.y-dest.y)>28;tick++){const now=d.advance(1/30),dir=d.navigateToward(actor,dest,now),steer=(dir.x||dir.y)?d.obstacleSteer(actor,dir.x,dir.y):dir;d.smoothBotMove(actor,steer.x,steer.y,255,1/30);assert.ok(!d.collides(actor.x,actor.y));maxRecoveries=Math.max(maxRecoveries,actor.stuckCount||0);}
 assert.ok(!d.buildingAt(actor.x,actor.y),b.label+' remained indoors');assert.ok(tick<600,b.label+' route timed out');maxExitTime=Math.max(maxExitTime,tick/30);routes++;
}
pass('Actual bot movement leaves every building through both exits from three interior positions',JSON.stringify({routes,maxExitTime,maxRecoveries}));
// Regression: a live simulation wedged Frost beside a fence / crate in an off-grid corner.
let cornerRoutes=0;
for(const dest of [{x:1954.3913523294032,y:656.3428070023656},{x:2160,y:1440},{x:340,y:1900},{x:900,y:1000}]){
 d.resetBrain(actor);actor.x=481.31090558439433;actor.y=1153.5235654039338;actor.vx=-51.929366079344796;actor.vy=251.73315998487283;actor.target=null;actor.visibleAllies=[];actor.visibleEnemies=[];
 const route=d.findPath(actor.x,actor.y,dest.x,dest.y);assert.ok(route.length);let from={x:actor.x,y:actor.y};for(const p of route){assert.ok(e.dev.pathClear(from.x,from.y,p.x,p.y,21),'unsafe route start/corner');from=p;}
 let tick=0;for(;tick<1800&&Math.hypot(actor.x-dest.x,actor.y-dest.y)>28;tick++){const dir=d.navigateToward(actor,dest,d.advance(1/30)),steer=d.obstacleSteer(actor,dir.x,dir.y);d.smoothBotMove(actor,steer.x,steer.y,255,1/30);assert.ok(!d.collides(actor.x,actor.y));assert.ok(actor.stuckCount<18);}
 assert.ok(tick<1800,'off-grid corner route did not recover');cornerRoutes++;
}
pass('Off-grid fence/crate regression uses verified local anchors and reaches four destinations',cornerRoutes+' actual movement routes');
let boundaryRoutes=0;for(const [x,y] of [[45,45],[4275,45],[45,2835],[4275,2835]]){
 d.resetBrain(actor);actor.x=x;actor.y=y;actor.vx=actor.vy=0;actor.target=null;actor.visibleEnemies=[];actor.visibleAllies=[];const dest=[...d.SPAWNS].sort((a,b)=>Math.hypot(a.x-x,a.y-y)-Math.hypot(b.x-x,b.y-y))[0];assert.ok(!d.collides(dest.x,dest.y));const route=d.findPath(x,y,dest.x,dest.y);assert.ok(route.length,'tangent perimeter route empty');let from={x,y};for(const p of route){assert.ok(e.dev.pathClear(from.x,from.y,p.x,p.y,21));from=p;}let tick=0;for(;tick<300&&Math.hypot(actor.x-dest.x,actor.y-dest.y)>28;tick++){const dir=d.navigateToward(actor,dest,d.advance(1/30)),steer=d.obstacleSteer(actor,dir.x,dir.y);d.smoothBotMove(actor,steer.x,steer.y,255,1/30);assert.ok(!d.collides(actor.x,actor.y));}assert.ok(tick<300,'corner route did not leave boundary '+JSON.stringify({x,y,dest,actor:{x:actor.x,y:actor.y},path:actor.navPath,destCollides:d.collides(dest.x,dest.y)}));boundaryRoutes++;
}
pass('Exact body tangency at all four perimeter corners remains navigable and actors move inward',boundaryRoutes+' actual movement routes');
// Preserve the exact old three-prop dogleg as a geometry fixture, independent of safer new placement.
const dogleg=injected.replace('const SOLID_CELL=', `for(let i=solids.length-1;i>=0;i--)if(!['building','perimeter'].includes(solids[i].kind)&&rectOverlap(objectBounds(solids[i]),{x:2990,y:600,w:360,h:260}))solids.splice(i,1);
mapRect(3051.2400141358376,672.7587605640292,70,70,'crate');mapRect(3178.447363078594,654.7772995755076,48,42,'utility');mapRect(3167.595861852169,736.4564703032374,74,24,'bench');
const SOLID_CELL=`),te=engine({},dogleg),td=te.context.__DISTRICT,ta=td.state.actors.find(a=>a.matchId!==null);for(const o of td.state.actors)if(o!==ta)o.dead=true;let doglegRoutes=0;
for(const start of [{x:3162.9264881553954,y:710.9230565937241},{x:3165.65033267202,y:715.5467855564702}])for(const dest of [{x:3340,y:650},{x:2160,y:1440}]){td.resetBrain(ta);Object.assign(ta,start);ta.vx=ta.vy=0;ta.target=null;ta.visibleEnemies=[];ta.visibleAllies=[];assert.ok(!td.collides(ta.x,ta.y));const connection=te.dev.navigationStart(ta.x,ta.y);assert.ok(connection.idx!==null&&connection.anchors.length>1,'fine local connection required');let tick=0;for(;tick<900&&Math.hypot(ta.x-dest.x,ta.y-dest.y)>28;tick++){const dir=td.navigateToward(ta,dest,td.advance(1/30)),steer=td.obstacleSteer(ta,dir.x,dir.y);td.smoothBotMove(ta,steer.x,steer.y,255,1/30);assert.ok(!td.collides(ta.x,ta.y));assert.ok(ta.stuckCount<18);}assert.ok(tick<900,'three-prop dogleg recovery failed');doglegRoutes++;}
pass('Exact Jett/Rune three-prop traps leave through a swept-safe fine local route',doglegRoutes+' actual movement routes');
// Healthy idle holding loses utility; healing/reloading remains meaningful.
const b=d.floors[1];d.resetBrain(actor);actor.x=b.x+b.w/2;actor.y=b.y+b.h/2;actor.hp=250;actor.slots[0].ammo=d.WEAPONS[actor.slots[0].name].mag;actor.slots[0].reloading=false;actor.target=null;actor.visibleEnemies=[];actor.visibleAllies=[];d.updateBuildingContext(actor,d.advance(.01));d.decideBot(actor,d.advance(9));assert.equal(actor.tactic,'EXIT');assert.ok(actor.exitPlan);
actor.hp=40;actor.regenActive=false;actor.exitPlan=null;d.decideBot(actor,d.advance(.5));assert.equal(actor.tactic,'REGEN_HIDE');actor.hp=250;actor.regenActive=false;d.updateBuildingContext(actor,d.advance(10));d.decideBot(actor,d.advance(10));assert.equal(actor.tactic,'EXIT');pass('Contextual holding decays while low-health recovery stays protected and ends when healed');
// Force immobility with movement intent: recovery must activate in a few seconds.
d.resetBrain(actor);actor.x=2160;actor.y=1440;const recoveryBefore=d.diagnostics.stuckRecoveries;const goal={x:3000,y:1440};for(let i=0;i<55;i++)d.navigateToward(actor,goal,d.advance(1/30));assert.ok(d.diagnostics.stuckRecoveries>recoveryBefore);assert.ok(d.diagnostics.maxStuckDetectionSeconds<1.6);pass('Movement-intent failure activates staged recovery within 1.6 seconds');
const isolated=make(),id=isolated.d,ia=id.state.actors.find(a=>a.matchId!==null);id.resetBrain(ia);ia.x=2160;ia.y=1440;ia.vx=ia.vy=0;ia.moveGoal={x:3000,y:1440};ia.navGoal={...ia.moveGoal};ia.navPath=[];ia.navIndex=0;ia.repathAt=1e12;ia.nextDecision=ia.nextThink=1e12;ia.target=null;ia.currentSlot=0;ia.slots[0].ammo=id.WEAPONS[ia.slots[0].name].mag;
id.routeFailure();const beforeEmpty=id.diagnostics.stuckRecoveries;for(let i=0;i<48;i++){id.updateBot(ia,1/30,id.advance(1/30));}assert.ok(id.diagnostics.stuckRecoveries>beforeEmpty);assert.ok(Math.hypot(ia.x-2160,ia.y-1440)>20);pass('Forced pathfinder failure retains movement intent, activates recovery and resumes actual movement');
const crowd=make(),cd=crowd.d,ca=cd.state.actors.find(a=>a.matchId!==null),friends=cd.state.actors.filter(a=>a!==ca&&a.matchId===ca.matchId&&a.team===ca.team).slice(0,2);assert.equal(friends.length,2);for(const a of cd.state.actors)if(a!==ca&&!friends.includes(a))a.dead=true;cd.resetBrain(ca);ca.x=2160;ca.y=1440;ca.vx=ca.vy=0;friends.forEach((a,i)=>{a.x=ca.x+(i?5:-5);a.y=ca.y-27;a.dead=false;});const crowded=cd.obstacleSteer(ca,0,-1);assert.ok(crowded.y<0);ca.stuckCount=2;const recovered=cd.obstacleSteer(ca,0,-1);assert.ok(recovered.y<0);const oldY=ca.y;for(let i=0;i<15;i++){const dir=cd.obstacleSteer(ca,0,-1);cd.smoothBotMove(ca,dir.x,dir.y,255,1/30);assert.ok(!cd.collides(ca.x,ca.y));}assert.ok(ca.y<oldY-60);pass('Crowded ally repulsion preserves forward progress before recovery and never crosses static geometry');
for(const [x,y,dx,dy] of [[60,60,-500,-500],[4260,60,500,-500],[60,2820,-500,500],[4260,2820,500,500]]){actor.x=x;actor.y=y;d.moveWithCollision(actor,dx,dy);assert.ok(actor.x>=45&&actor.y>=45&&actor.x<=d.WORLD.w-45&&actor.y<=d.WORLD.h-45);}assert.ok(d.outerWorld.length>100);assert.ok(d.outerWorld.every(o=>!d.solids.includes(o)));pass('Physical perimeter blocks all four corners; surrounding neighborhood stays visual-only',d.outerWorld.length+' outer objects');
actor.isPlayer=true;d.state.mode='play';d.state.playerMatchId=actor.matchId;for(const [width,height] of [[1440,900],[1920,1080],[3440,1440],[390,844]])for(const [x,y] of [[52,52],[4268,52],[52,2828],[4268,2828]]){d.viewport(width,height);actor.x=x;actor.y=y;actor.ads=false;actor.adsBlend=0;for(let i=0;i<120;i++)d.updateCamera(1/60);const v=d.viewBounds();assert.ok(v.x>=-d.WORLD_PAD-.1&&v.y>=-d.WORLD_PAD-.1&&v.x+v.w<=d.WORLD.w+d.WORLD_PAD+.1&&v.y+v.h<=d.WORLD.h+d.WORLD_PAD+.1);const s=d.worldToScreen(x,y),p=d.screenToWorld(s.x,s.y);assert.ok(Math.abs(p.x-x)<1e-6&&Math.abs(p.y-y)<1e-6);}pass('Camera corners stay within rendered surrounding world at four viewports; zoom coordinate conversion is reversible');
const adsTest=make(),ad=adsTest.d,a=ad.state.actors.find(a=>a.matchId!==null);a.x=2160;a.y=1440;a.currentSlot=0;a.slots[0].name='AR-15';a.vx=a.vy=0;a.spreadBloom=0;a.sprinting=false;a.dashUntil=0;a.dead=false;a.ads=false;a.adsBlend=0;const hip=ad.effectiveSpreadDeg(a);assert.equal(hip,2.7);ad.updateAds(a,true,2,ad.advance(2));const still=ad.effectiveSpreadDeg(a);assert.ok(Math.abs(still-1.5)<1e-6);a.vx=200;assert.ok(Math.abs(ad.effectiveSpreadDeg(a)-1.5)<1e-6);a.sprinting=true;ad.updateAds(a,true,2,ad.advance(2));assert.ok(!a.ads);assert.ok(Math.abs(ad.effectiveSpreadDeg(a)-3.6)<1e-6);a.sprinting=false;a.ads=true;a.adsBlend=1;assert.ok(ad.tryDash(a,1,0,ad.advance(5)));assert.ok(!a.ads);ad.updateAds(a,false,.1,ad.advance(.1));const dashSpread=ad.effectiveSpreadDeg(a);assert.ok(dashSpread>1.5&&dashSpread<3.6);pass('Four authoritative spreads replace old multipliers; ADS and sprint/dash cancel and interpolate through the shared projectile cone');
a.dashUntil=0;a.dashCooldownUntil=0;a.vx=a.vy=0;a.ads=true;a.adsBlend=1;a.slots[0].ammo=30;a.slots[0].reloading=false;a.slots[0].lastShot=-999;const shotSpread=ad.effectiveSpreadDeg(a),shotsBefore=ad.diagnostics.adsShots;assert.ok(ad.fire(a,0,ad.advance(1)));assert.equal(ad.diagnostics.adsShots,shotsBefore+1);assert.equal(ad.state.projectiles.length,1);assert.ok(Math.abs(Math.atan2(ad.state.projectiles[0].vy,ad.state.projectiles[0].vx))<=shotSpread*Math.PI/360);pass('Actual ADS projectiles use the displayed cone and preserve trigger-pull telemetry');
for(const name of Object.keys(ad.WEAPONS)){const sheet=ad.weaponSheet(name);assert.equal(sheet.bodyShots,Math.ceil(250/sheet.w.damage));assert.equal(sheet.headShots,Math.ceil(250/sheet.w.head));assert.ok(Number.isFinite(sheet.bodyTtk)&&Number.isFinite(sheet.headTtk));assert.equal(ad.weaponBars(name).length,7);assert.ok(ad.weaponDescription(name).length>30);}assert.equal(ad.weaponSheet('Pump Shotgun').bodyTtk,3);assert.equal(ad.weaponSheet('Pump Shotgun').headTtk,1.5);pass('All thirteen loadout sheets calculate real RPM/STK/TTK and seven descriptive bars');
// Load an actual preceding-build world and retain active data and all persistent identities.
const oldSource=fs.readFileSync(path.resolve(__dirname,'fixtures/game-1.3.0.js'),'utf8');const prior=engine({},oldSource);for(let i=0;i<800;i++)prior.step();prior.dev.saveTelemetry();const saved=JSON.parse(prior.data.get('sar-persistent-save'));saved.config.binds.reload='KeyQ';saved.futureWorld={retain:123};saved.bots.Ace.recentForm=5;saved.bots.Ace.familiarity.P90=46;saved.bots.Ace.profile.power=97;saved.patchArchives.push({id:'prior-archive',meta:{AK47:{kills:21}},future:{retained:true}});const data=Object.fromEntries(prior.data);data['sar-persistent-save']=JSON.stringify(saved);data['sar-local-accounts-v1']=JSON.stringify({test:{hash:'retain-hash',salt:'retain-salt',createdAt:91}});data['sar-local-session-v1']='test';const migrated=engine(data),save=migrated.dev.inspect().SAVE;assert.equal(save.schema,17);const pure=migrated.dev.normalizeSave(saved);
assertRetained(saved.bots,pure.bots,'normalized bots');assert.equal(save.patchArchives.length,saved.patchArchives.length+1);assert.deepEqual(save.patchArchives.slice(0,-1),saved.patchArchives);assert.deepEqual(save.patchArchives.at(-1).meta,saved.meta);assert.equal(save.patchArchives.at(-1).id,saved.patchState.id);assert.notEqual(save.patchState.id,saved.patchState.id);
for(const m of Object.values(pure.meta))for(const field of ['kills','deaths','shots','damage',...NEW_META_FIELDS])assert.equal(m[field],0,'new balance patch '+field);
for(const [name,b] of Object.entries(saved.bots)){assertRetained(b.profile,save.bots[name].profile,'profile '+name);assert.match(save.bots[name].profile.id,/^bot_/);assert.equal(save.bots[name].recentForm,b.recentForm);assertRetained(b.familiarity,save.bots[name].familiarity,'familiarity '+name);assert.equal(save.bots[name].familiarity['X-16 Auto'],0);for(const key of ['games','kills','deaths','wins','losses','damage','timeAlive'])assert.equal(save.bots[name].career[key],b.career[key]);}assert.deepEqual(save.seasons,saved.seasons);assert.equal(save.futureWorld.retain,123);assert.equal(save.config.binds.reload,'KeyQ');assert.equal(save.config.binds.ads,'MouseRight');assert.equal(save.config.adsSensitivity,.65);assert.equal(save.config.cameraAimBias,false);assert.equal(migrated.data.get('sar-local-accounts-v1'),data['sar-local-accounts-v1']);assert.equal(migrated.data.get('sar-local-session-v1'),'test');pass('Actual 1.3.0 schema-15 world migrates to17; old balance meta archives intact while seasons, profiles, careers, Form, familiarity, accounts and binds survive');
const oldWeapons=JSON.parse(fs.readFileSync(path.resolve(__dirname,'fixtures/balance-7.0.json'),'utf8')).weapons;for(const name of ['AK47','SMG-9','LR-762','LW Tundra','War Head LMG'])for(const field of ['type','auto','pellets','color','preferred','reserve','mag','falloffStart','falloff','role'])assert.equal(ad.WEAPONS[name][field],oldWeapons[name][field],name+' '+field);pass('Existing weapon identity and unchanged range/ammunition fields remain intact');
fs.writeFileSync(path.resolve(__dirname,'district-results.json'),JSON.stringify({result:'PASS',checks,migrations:migrationTests(),map:d.MAP_REPORT,buildingRoutes:{routes,maxExitTime,maxRecoveries},navigationCells:walkable,propCounts:d.solids.reduce((out,o)=>(out[o.kind]=(out[o.kind]||0)+1,out),{})},null,2));




