'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),os=require('os');
const XP=require('../progression.js'),{engine}=require('./simulate.cjs'),{validateWorld,writeWorld,readWorld,migrateLocalWorld}=require('../server/world.cjs'),{createDatabase}=require('../server/db.cjs'),Circuit=require('../server/tournaments.cjs'),Runtime=require('../server/tournament-runtime.cjs');
const clone=x=>JSON.parse(JSON.stringify(x)),checks=[],pass=s=>{checks.push(s);console.log('PASS '+s);};
function receipt(overrides={}){return {kind:'standard',mode:'tdm',at:Date.now(),stats:{kills:0,deaths:0,assists:0,headshots:0,damage:0,timeAlive:0},events:XP.events(),leaders:{kills:false,assists:false,alive:false},firstWeapons:[],won:null,winStreak:0,...overrides};}
const value=r=>XP.totals(r).units/100,key=(r,k)=>XP.breakdown(r).find(l=>l.key===k)?.units/100||0;
assert.equal(value(receipt({events:{...XP.events(),soloKills:6},won:true})),23);
assert.equal(value(receipt({stats:{...receipt().stats,assists:1},events:{...XP.events(),dashes:1},won:false})),3.2);
assert.equal(value(receipt({kind:'official',events:{...XP.events(),finishingKills:100}})),130);
assert.equal(value(receipt({kind:'official',events:{...XP.events(),dashes:1}})),.26);
for(const [family,field,tiers] of [['kills','kills',[[9,0],[10,20],[15,30],[20,50],[30,50]]],['damage','damage',[[1999,0],[2000,15],[3000,35],[4000,70]]],['headshots','headshots',[[9,0],[10,10],[20,10]]]])for(const [n,v]of tiers)assert.equal(key(receipt({stats:{...receipt().stats,[field]:n}}),family),v);
for(const [n,v]of [[2,0],[3,10],[5,15],[10,25]])assert.equal(key(receipt({events:{...XP.events(),bestStreak:n}}),'killStreak'),v);
for(const [n,v]of [[4,0],[5,15],[10,50]])assert.equal(key(receipt({stats:{...receipt().stats,kills:n,assists:n}}),'combo'),v);
for(const [n,v]of [[14,0],[15,25],[20,60]])assert.equal(key(receipt({stats:{...receipt().stats,kills:n,deaths:10}}),'kd'),v);
for(let n=1;n<=8;n++)assert.equal(key(receipt({won:true,winStreak:n}),'winStreak'),n===3?10:n===5?25:0);
assert.equal(key(receipt({won:false,winStreak:5}),'winStreak'),0);
pass('Exact 23 / 3.2 / 130 / 0.26 XP; every tier boundary, non-stacking milestones and win streak #3/#5');
let total=0;assert.equal(XP.requirements.length,50);assert.equal(XP.requirements[49],25000);for(let level=1;level<50;level++){assert.equal(XP.view(total).currentLevel,level);total+=XP.requirements[level-1]*100;assert.equal(XP.view(total-1).currentLevel,level);assert.equal(XP.view(total).currentLevel,level+1);}assert.equal(XP.view(total+90000000).currentLevel,50);assert.equal(XP.view(total+90000000).totalXP,(total+90000000)/100);assert.equal(XP.view(50000).currentLevel,5);assert.equal(XP.view(50000).currentXP,15);
pass('All 49 level boundaries, multi-level carry, cap50, lifetime overflow and reserved Level50 requirement');
const source=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8').replace('window.SAR = {','window.__XPTEST={renderPlayerProfile,renderDeathmatchProfile,updateProgressionUi,commitMatchXP};window.SAR = {');
function make(storage={}){return engine(storage,source);}
function prepare(e,mode='tdm'){if(mode==='tdm')e.dev.queueForMatch();else e.context.SAR.startDeathmatch();const m=e.dev.inspect().state.matches.find(m=>m?.hasPlayer),p=m.participants.find(a=>a.isPlayer);m.status="active";m.countdownUntil=0;for(const a of e.dev.inspect().state.actors){a.spawnFlash=0;a.dead=false;}return {m,p};}
const e=make(),before=e.context.SAR.getUniverse(),{m,p}=prepare(e);e.context.__XPTEST.updateProgressionUi();assert.match(e.ui.element('lobbyProgression').innerHTML,/LVL 1/);assert.equal(p.xpEvents.usedWeapons.length,0);e.dev.fire(p,0,10000);assert.equal(p.xpEvents.usedWeapons[0],p.slots[0].name);const used=p.slots[0].name;e.dev.tryDash(p,1,0,10000);e.dev.tryDash(p,1,0,10001);assert.equal(p.xpEvents.dashes,1);
const enemy=m.participants.find(a=>a.team!==p.team);e.dev.applyDamage(enemy,{owner:p,weapon:used,travel:1},250,false,11000);assert.equal(p.xpEvents.soloKills,1);e.dev.respawnActor(enemy);enemy.spawnFlash=0;const friend=m.participants.find(a=>a.team===p.team&&!a.isPlayer);e.dev.applyDamage(enemy,{owner:friend,weapon:'9mm',travel:1},200,false,12000);e.dev.applyDamage(enemy,{owner:p,weapon:used,travel:1},50,false,12001);assert.equal(p.xpEvents.finishingKills,1);e.dev.respawnActor(enemy);enemy.spawnFlash=0;e.dev.applyDamage(enemy,{owner:p,weapon:used,travel:1},50,false,13000);e.dev.applyDamage(enemy,{owner:friend,weapon:'9mm',travel:1},200,false,13001);assert.equal(p.stats.assists,1);e.dev.endMatch(m,p.team,'time');e.ui.flush();const after=e.context.SAR.getUniverse(),award=after.progression.awards[m.matchId];assert.ok(award.units>2500);assert.deepEqual(award.firstWeapons,[used]);assert.equal(award.events.soloKills,1);assert.equal(award.events.finishingKills,1);assert.equal(award.events.bestStreak,2);assert.equal(key(award,"assist"),.5);assert.deepEqual(m.result.xp,award);assert.match(e.ui.element("modalContent").innerHTML,/XP EARNED/);assert.match(e.context.SAR.xpSummaryHtml(award),new RegExp('\\+'+(award.units/100)));XP.validate(after.progression);validateWorld(after,{save:before});const fixed=clone(after.progression);e.dev.endMatch(m,1);e.context.__XPTEST.commitMatchXP(m);e.context.__XPTEST.renderPlayerProfile();assert.deepEqual(e.context.SAR.getUniverse().progression,fixed);assert.match(e.ui.element('modalContent').innerHTML,/LIFETIME XP/);
const resumed=make({'sar-persistent-save':JSON.stringify(after)});assert.deepEqual(resumed.context.SAR.getUniverse().progression,fixed);assert.deepEqual(migrateLocalWorld(after).progression,fixed);const again=prepare(resumed);resumed.dev.fire(again.p,0,20000);resumed.dev.endMatch(again.m,1-again.p.team,'time');assert.deepEqual(resumed.context.SAR.getUniverse().progression.awards[again.m.matchId].firstWeapons,[]);
pass('Real fire/dash/solo/finisher hooks, immutable result summary, duplicate finalization, profile, restart, migration and persistent first use');
for(const mode of ['tdm','deathmatch']){const f=make(),original=f.context.SAR.getUniverse().progression,cm=f.context.SAR.startCustomMatch({mode,bots:[]}),human=cm.participants.find(a=>a.isPlayer);cm.status="active";f.dev.fire(human,0,10000);f.dev.tryDash(human,1,0,10000);f.dev.endMatch(cm,mode==='tdm'?human.team:human.id,'time');assert.deepEqual(f.context.SAR.getUniverse().progression,original);assert.equal(cm.result.xp,null);}
const f=make(),fb=f.context.SAR.getUniverse(),dm=prepare(f,'deathmatch');f.dev.endMatch(dm.m,dm.p.id,'time');const dw=f.context.SAR.getUniverse(),dr=dw.progression.awards[dm.m.matchId];assert.equal(dr.won,null);assert.deepEqual(dr.leaders,{kills:true,assists:true,alive:true});assert.equal(dr.units,4000);assert.deepEqual(dw.playerCareer,fb.playerCareer);assert.deepEqual(dw.patchState,fb.patchState);validateWorld(dw,{save:fb});
pass('Custom/practice excluded without discovery consumption; Deathmatch XP separate from TDM career; tied leader rewards and draw result');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sar-xp-')),dbFile=path.join(dir,'test.sqlite');let db=createDatabase(dbFile);const user='progression-fixture',now=Date.now();try{
 db.prepare('INSERT INTO users(id,username,username_key,password_hash,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(user,'ProgressionFixture','progressionfixture','isolated-test-only',now,now);writeWorld(db,user,before,0);writeWorld(db,user,after,1);writeWorld(db,user,after,2);db.close();db=createDatabase(dbFile);assert.deepEqual(readWorld(db,user).save.progression,fixed);
 const changed=clone(after);changed.progression.totalXPUnits++;assert.throws(()=>writeWorld(db,user,changed,3),/progression|reconcile/);const removed=clone(after);delete removed.progression;assert.throws(()=>writeWorld(db,user,removed,3),/removed/);const replay=clone(after);replay.progression.awards['match:duplicate']=clone(award);assert.throws(()=>writeWorld(db,user,replay,3),/duplicated|reconcile/);
 for(const row of db.prepare('SELECT bot_id,personality_json FROM bot_social_profiles WHERE user_id=?').all(user)){const personality=JSON.parse(row.personality_json);personality.social={...personality.social,competitiveness:1,socialness:1,ego:1};db.prepare('UPDATE bot_social_profiles SET personality_json=? WHERE user_id=? AND bot_id=?').run(JSON.stringify(personality),user,row.bot_id);}db.prepare('UPDATE bots SET form=10 WHERE user_id=?').run(user);
 let official=Circuit.scheduleOfficial(db,user,after.seasons.current,now)[0],custom=Circuit.createCustom(db,user,{name:'No XP',startsAt:now},now);

 let current=clone(after),revision=3;
 for(const [t,kind]of [[custom,'custom'],[official,'official']]){const ids=[user,...after.activeBotNames.slice(0,39).map(n=>after.bots[n].profile.id)];for(let i=0;i<8;i++)Circuit.registerTeam(db,user,t.id,{name:'Team '+i,participantIds:ids.slice(i*5,i*5+5)},now);Circuit.startTournament(db,user,t.id,Math.max(now,t.startsAt));const context=Runtime.playContext(db,user,t.id,Math.max(now,t.startsAt));assert.equal(context.tournamentKind,kind);const g=make({'sar-persistent-save':JSON.stringify(current)}),tm=g.context.SAR.startTournamentGame(context),human=tm.participants.find(a=>a.isPlayer);tm.status="active";g.dev.fire(human,0,10000);g.dev.tryDash(human,1,0,10000);g.dev.endMatch(tm,human.team,'time');const world=g.context.SAR.getUniverse();if(kind==='custom'){assert.deepEqual(world.progression,current.progression);const forged=clone(world);XP.award(forged.progression,{matchId:context.gameId,...receipt({kind:'official',tournamentId:t.id,seriesId:context.seriesId})});assert.throws(()=>writeWorld(db,user,forged,revision),/official tournament/);Circuit.deleteCustom(db,user,t.id,t.name);}else{const r=world.progression.awards[context.gameId];assert.equal(r.units,r.baseUnits*13/10);assert.match(g.context.SAR.xpSummaryHtml(r),/BASE XP[\s\S]*×1.3[\s\S]*FINAL XP/);assert.deepEqual(world.playerCareer,current.playerCareer);Circuit.recordGame(db,user,t.id,context.seriesId,tm.tournamentResult,Math.max(now,t.startsAt));writeWorld(db,user,world,revision++);writeWorld(db,user,world,revision++);assert.deepEqual(readWorld(db,user).save.progression,world.progression);current=world;}}
 pass('SQLite restart and repeated sync; tampering rejected; registered official ×1.3; custom tournament rejection; tournament/career isolation');
}finally{db.close();assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(dir,{recursive:true,force:true});}
console.log(JSON.stringify({ok:true,groups:checks.length}));




