'use strict';
const crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {personalityFor,eventEligibility,dialogueIntent,buildSystemPrompt,EVENT_TYPES,PROFILES,STYLE_EXAMPLES}=require('./social-personalities.cjs');
const uuid=()=>crypto.randomUUID(),cleanText=v=>String(v??'').replace(/[\u0000-\u001f<>]/g,' ').trim(),fail=(status,message)=>Object.assign(new Error(message),{status});
const DEFAULTS={botMessages:true,botInitiated:true,playerReplies:true,developerMode:false,temperature:.7};
const runtimes=new WeakMap();let globalBusy=false;
const MOODS=['neutral','confident','happy','angry','frustrated','hyped','sarcastic','concerned','disappointed','amused','focused'],CATEGORIES=['balance','meta','season','rivalry','tournament','career','personal','weapon','map'];
const schema={type:'object',additionalProperties:false,required:['subject','body','mood','category','wantsReply','certainty'],properties:{subject:{type:'string',maxLength:100},body:{type:'string',maxLength:900},mood:{type:'string',enum:MOODS},category:{type:'string',enum:CATEGORIES},wantsReply:{type:'boolean'},certainty:{type:'number',minimum:0,maximum:1}}};
const transientProviderError=error=>/fetch failed|ECONN|abort|timeout|Model HTTP (?:408|429|5\d\d)/i.test(String(error?.message||error||''));
function validateOutput(value){
  if(!value||Array.isArray(value)||typeof value!=='object'||Object.keys(value).some(k=>!schema.required.includes(k)))throw Error('Invalid message fields');
  if(typeof value.subject!=='string'||!value.subject.trim()||value.subject.length>100||typeof value.body!=='string'||value.body.trim().length<2||value.body.length>900||!MOODS.includes(value.mood)||!CATEGORIES.includes(value.category)||typeof value.wantsReply!=='boolean'||!Number.isFinite(value.certainty)||value.certainty<0||value.certainty>1)throw Error('Invalid structured message');
  if(/as an ai|based on the information provided|i(?:'d| would) be happy to help|here are several considerations/i.test(value.body))throw Error('Assistant-style output rejected');
  if(/\b(?:json|payload|system prompt|system instructions?|repair instructions?|validation (?:failed|error)|reasoning tokens?|chain of thought|ollama|gpt[- ]?oss|api request|model (?:reasoning|output|response)|provided context|context (?:window|payload)|missing (?:context|fields|payload))\b|<\/?(?:think|analysis)>|```|["'](?:subject|wantsReply|certainty)["']\s*:/i.test(value.subject+' '+value.body))throw Error('Internal formatting or service details must not appear in character dialogue');
  if(/\b(?:bodyHits|headHits|bodyTTK|headTTK|fireIntervalSeconds|roundsPerMinute|intraBurstSeconds|currentPatchGlobal|currentPatchPersonal|authoritativeGameFacts|wantsReply)\b/.test(value.subject+' '+value.body))throw Error('Internal field names must not appear in character dialogue; use ordinary words');
  return {...value,subject:cleanText(value.subject),body:cleanText(value.body)};
}
function endpoint(){const base=process.env.SAR_OLLAMA_URL||'http://127.0.0.1:11434';const url=new URL(base);if(url.protocol!=='http:'||!['127.0.0.1','localhost','[::1]'].includes(url.hostname)||url.username||url.password)throw Error('Ollama must use a local loopback address');return base.replace(/\/$/,'');}
function preferences(db,userId){const row=db.prepare('SELECT settings_json FROM ai_preferences WHERE user_id=?').get(userId);return {...DEFAULTS,...(row?JSON.parse(row.settings_json):{})};}
function setPreferences(db,userId,changes){if(!changes||typeof changes!=='object'||Array.isArray(changes))throw fail(400,'AI preferences must be an object');const next=preferences(db,userId);for(const [key,value] of Object.entries(changes)){if(!Object.hasOwn(DEFAULTS,key))throw fail(400,'Unknown AI preference');if(key==='temperature'){if(!Number.isFinite(value)||value<.2||value>1)throw fail(400,'Temperature must be 0.2–1');}else if(typeof value!=='boolean')throw fail(400,'AI toggles must be Boolean');next[key]=value;}db.prepare('INSERT INTO ai_preferences(user_id,settings_json,updated_at) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET settings_json=excluded.settings_json,updated_at=excluded.updated_at').run(userId,JSON.stringify(next),Date.now());kick(db);return next;}
function initializeSocial(db){for(const b of db.prepare('SELECT user_id,bot_id,name FROM bots').all()){const p=personalityFor(b.name);if(p)db.prepare('INSERT OR IGNORE INTO bot_social_profiles(user_id,bot_id,personality_json,created_at) VALUES(?,?,?,?)').run(b.user_id,b.bot_id,JSON.stringify(p),Date.now());}}
function ranks(world){const rows=Object.values(world?.seasons?.current?.stats||{}).filter(r=>r.games>=10);const kd=r=>r.deaths?r.kills/r.deaths:r.kills?999:0;rows.sort((a,b)=>kd(b)-kd(a)||b.wins-a.wins||b.kills-a.kills||b.damage-a.damage||a.name.localeCompare(b.name));return Object.fromEntries(rows.map((r,i)=>[r.name,i+1]));}
function metaRank(patch,type){return require('./weapon-dialogue.cjs').ranking(patch,type).map(r=>r.name);}
function weaponMention(text,name){const aliases={'Pump Shotgun':['pump','pump shotgun'],'LW Tundra':['tundra','lw tundra'],'War Head LMG':['war head','warhead','lmg','war head lmg'],'AR-15':['ar15','ar 15'],'AK47':['ak47','ak 47'],'SMG-9':['smg9','smg 9'],'Auto 12':['auto12','auto 12'],'LR-762':['lr762','lr 762'],'X16':['x16','x 16'],'X-16 Auto':['x16 auto','x 16 auto','x16auto'],'SR-Aug':['sr aug','sraug'],'SPAS-12':['spas 12','spas12']};const normalized=String(text).toLowerCase().replace(/[^a-z0-9]+/g,' ');return (aliases[name]||[name.toLowerCase()]).some(alias=>new RegExp('(?:^| )'+alias.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?: |$)').test(normalized));}
function shotTime(w,index){const count=w.burstCount||1;return Math.floor(index/count)*w.hitSpeed+(index%count)*(w.burstSpacing||0);}
function measuredKd(stats,aliases=false){const kills=stats?.[aliases?'k':'kills'],deaths=stats?.[aliases?'d':'deaths'];return {kills:Number.isFinite(kills)?kills:null,deaths:Number.isFinite(deaths)?deaths:null,kd:Number.isFinite(kills)&&deaths>0?kills/deaths:null,winRate:null,winRateReason:'Kill/death counts do not provide wins or losses'};}
function tournamentFacts(db,userId,id,event){
  return db.prepare('SELECT id,name,status,kind,bracket_json,metadata_json FROM tournaments WHERE user_id=? AND deleted_at IS NULL ORDER BY CASE WHEN id=? THEN 0 ELSE 1 END,created_at DESC LIMIT 3').all(userId,event.tournamentId||null).map(t=>{
    const state=JSON.parse(t.bracket_json||'{}'),teams=state.teams||[],series=state.series||[],placements=state.placements||[],final=series.find(s=>s.round==='FINAL'),winner=teams.find(team=>team.id===final?.winnerTeamId),verifiedWinner=t.status==='COMPLETED'&&placements.some(p=>p.placement===1&&p.teamId===winner?.id)?winner:null;
    return {id:t.id,name:t.name,status:t.status,kind:t.kind,teams:teams.map(team=>({id:team.id,name:team.name,seed:team.seed,participants:team.participants||[]})),series:series.map(s=>({id:s.id,round:s.round,bestOf:s.bestOf,teamIds:s.teamIds,wins:s.wins,winnerTeamId:s.winnerTeamId||null})),placements,earnings:state.earnings||[],invites:state.invites||[],botTeamId:teams.find(team=>team.participants?.some(p=>p.id===id))?.id||null,results:verifiedWinner?{winnerTeamId:verifiedWinner.id,winnerTeamName:verifiedWinner.name,winnerParticipants:verifiedWinner.participants.map(p=>p.name)}:null};
  });
}
function verifiedTournamentEvent(context,event){
  if(!['TOURNAMENT_ACCEPT','TOURNAMENT_DECLINE','TOURNAMENT_BRACKET','TOURNAMENT_FINAL','TOURNAMENT_PLACEMENT','TOURNAMENT_ELIMINATION','TOURNAMENT_WIN'].includes(event.type))return true;
  const t=context.authoritativeGameFacts.tournaments.find(t=>t.id===event.tournamentId);if(!t||t.name!==event.name||t.kind!==event.kind)return false;
  const team=t.teams.find(team=>team.id===event.teamId||team.name===event.teamName),belongs=team?.participants.some(p=>p.id===context.botId),series=t.series.find(s=>s.id===event.seriesId);
  if(event.type==='TOURNAMENT_DECLINE')return t.invites.some(i=>i.botId===context.botId&&i.teamId===event.teamId&&i.state==='DECLINED'&&i.reason===event.reason)&&team?.name===event.teamName;
  if(!belongs||team.name!==event.teamName)return false;
  if(event.type==='TOURNAMENT_ACCEPT')return team.id===event.teamId;
  if(event.type==='TOURNAMENT_BRACKET')return team.id===event.teamId&&team.seed===event.seed&&t.series.length>0;
  if(event.type==='TOURNAMENT_FINAL')return series?.round==='SF'&&series.winnerTeamId===team.id;
  if(event.type==='TOURNAMENT_ELIMINATION')return !!series&&series.round===event.round&&series.teamIds.includes(team.id)&&series.winnerTeamId!==team.id&&series.winnerTeamId===event.winnerTeamId&&JSON.stringify(series.wins)===JSON.stringify(event.wins);
  return t.status==='COMPLETED'&&t.placements.some(p=>p.teamId===team.id&&p.placement===event.placement)&&t.earnings.some(e=>e.participantId===context.botId&&e.amount===event.amount)&&(event.type==='TOURNAMENT_WIN'?event.placement===1: event.placement>1);
}
function botContext(db,userId,id,event={}){
  const b=db.prepare('SELECT * FROM bots WHERE user_id=? AND bot_id=?').get(userId,id);if(!b)throw fail(404,'Bot not found');initializeSocial(db);
  const s=db.prepare('SELECT * FROM bot_social_profiles WHERE user_id=? AND bot_id=?').get(userId,id),world=JSON.parse(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(userId).save_json),bot=world.bots[b.name],current={...world.patchState,...world.patchState.aiSamples?.[world.aiRevision]},rank=ranks(world),weaponNames=Object.keys(current.weaponStats||{});
  const publicFacts=require('./dialogue-context.cjs').publicFacts(world,id,event),relevant=publicFacts.weapons.map(weapon=>weapon.name);
  const recent=db.prepare('SELECT direction,body,subject,type FROM messages WHERE user_id=? AND bot_id=? ORDER BY created_at DESC,id DESC LIMIT 8').all(userId,id).reverse();
  return {dialogueEvent:event,botId:id,name:b.name,power:b.power,playstyle:JSON.parse(s.personality_json).playstyle,form:b.form,socialProfile:JSON.parse(s.personality_json),relationship:{playerRespect:s.player_respect,playerTrust:s.player_trust,bots:db.prepare('SELECT other_bot_id AS botId,friendship,rivalry FROM bot_relationships WHERE user_id=? AND bot_id=? ORDER BY rivalry DESC,friendship DESC LIMIT 4').all(userId,id)},conversationSummary:db.prepare('SELECT summary FROM conversation_summaries WHERE user_id=? AND bot_id=?').get(userId,id)?.summary||'',importantMemories:JSON.parse(s.important_memories_json).slice(-12),opinions:JSON.parse(s.opinions_json).slice(-6),recentMessages:recent,authoritativeGameFacts:{maxHP:250,map:{name:'Brightfield Blocks',movementPlane:'Combat and movement remain on the existing flat world plane. Roofs are visual geometry, with no playable rooftops, upper floors, elevation advantage or vertical firing angles.',polish:'The current map detail pass is presentation only. Layout, routes, collision, cover and line-of-sight rules did not change.',cover:'Cover requires existing simulation collision or visibility geometry. Painted crosswalks, road markings, grass texture and decorative surface detail provide no cover. Existing physical house walls and other collision obstacles retain their original cover behavior.'},currentPatchId:current.id,aiRevision:world.aiRevision||'pre-tactical-instinct',currentPatchLabel:current.label,season:{number:world.seasons.current.number,rank:rank[b.name]||null,daysRemaining:Math.max(0,(world.seasons.current.endAt-Date.now())/86400000),record:world.seasons.current.stats[b.name]||null,winners:world.seasons.history.slice(0,3).map(s=>({season:s.number,winner:s.winner||null}))},career:(()=>{const career=JSON.parse(db.prepare('SELECT stats_json FROM bot_careers WHERE user_id=? AND bot_id=?').get(userId,id).stats_json);return {...career,weaponUsage:Object.fromEntries(Object.entries(career.weaponUsage||{}).filter(([name])=>relevant.slice(0,4).includes(name)))};})(),recentPerformance:bot.recentMatches.slice(-4),tournaments:tournamentFacts(db,userId,id,event),...publicFacts}};
}
function remember(db,userId,id,item){const row=db.prepare('SELECT important_memories_json FROM bot_social_profiles WHERE user_id=? AND bot_id=?').get(userId,id);if(!row)return;let list=JSON.parse(row.important_memories_json);if(!list.some(x=>x.id===item.id))list.push(item);list=list.slice(-12);db.prepare('UPDATE bot_social_profiles SET important_memories_json=? WHERE user_id=? AND bot_id=?').run(JSON.stringify(list),userId,id);}
function updateSummary(db,userId,id){const rows=db.prepare('SELECT direction,body,id,created_at FROM messages WHERE user_id=? AND bot_id=? ORDER BY created_at DESC,id DESC LIMIT 32').all(userId,id).reverse(),older=rows.slice(0,Math.max(0,rows.length-8));const summary=older.map(m=>`${m.direction}: ${m.body.slice(0,130)}`).join(' | ').slice(-2200);db.prepare('INSERT INTO conversation_summaries(user_id,bot_id,summary,last_message_at) VALUES(?,?,?,?) ON CONFLICT(user_id,bot_id) DO UPDATE SET summary=excluded.summary,last_message_at=excluded.last_message_at').run(userId,id,summary,Date.now());}
function messageRows(db,userId,limit=100,{botId=null,before=null}={}){const columns='id,bot_id AS botId,direction,type,event_id AS eventId,body,subject,mood,category,wants_reply AS wantsReply,certainty,generation_id AS generationId,created_at AS createdAt,read_at AS readAt,source';let sql=`SELECT ${columns} FROM messages WHERE user_id=?`,args=[userId];if(botId){sql+=' AND bot_id=?';args.push(botId);}if(before){const cursor=db.prepare('SELECT created_at,id FROM messages WHERE id=? AND user_id=?').get(before,userId);if(!cursor)throw fail(400,'Invalid message cursor');sql+=' AND (created_at<? OR (created_at=? AND id<?))';args.push(cursor.created_at,cursor.created_at,cursor.id);}sql+=' ORDER BY created_at DESC,id DESC LIMIT ?';args.push(Math.min(500,Math.max(1,limit)));return db.prepare(sql).all(...args).map(m=>({...m,wantsReply:!!m.wantsReply}));}
async function probe(db,force=false){const r=runtime(db);if(r.probing)return r.probing;if(!force&&Date.now()-r.lastCheckedAt<15000)return r;return r.probing=(async()=>{try{const res=await fetch(endpoint()+'/api/tags',{signal:AbortSignal.timeout(3000)});if(!res.ok)throw Error('Ollama status '+res.status);const tags=await res.json(),m=tags.models?.find(m=>(m.name||m.model)==='gpt-oss:20b');r.status=m?'CONNECTED':'MODEL_NOT_INSTALLED';r.modelVersion=m?.digest||null;r.error=m?'':'gpt-oss:20b was not found in the installed model list.';}catch(error){r.status='OLLAMA_OFFLINE';r.error=error.message;}r.lastCheckedAt=Date.now();r.probing=null;return r;})();}
function runtime(db){let r=runtimes.get(db);if(r)return r;initializeSocial(db);db.prepare("UPDATE ai_jobs SET status='QUEUED',updated_at=? WHERE status='RUNNING'").run(Date.now());for(const job of db.prepare("SELECT id,error FROM ai_jobs WHERE status='FAILED'").all()){if(transientProviderError(job.error))db.prepare("UPDATE ai_jobs SET status='QUEUED',next_attempt_at=?,updated_at=? WHERE id=?").run(Date.now()+30000,Date.now(),job.id);}r={db,status:'CHECKING',lastCheckedAt:0,error:'',timer:null,probing:null,busy:false,closed:false};runtimes.set(db,r);r.timer=setInterval(()=>kick(db),5000);r.timer.unref();void probe(db).then(()=>kick(db));return r;}
function dispose(db){const r=runtimes.get(db);if(r){r.closed=true;clearInterval(r.timer);r.abort?.abort();runtimes.delete(db);}}
async function status(db,userId){const r=await probe(db);const rows=db.prepare('SELECT status,COUNT(*) AS n FROM ai_jobs WHERE user_id=? GROUP BY status').all(userId),counts=Object.fromEntries(rows.map(x=>[x.status,x.n]));return {status:r.status,model:'gpt-oss:20b',modelVersion:r.modelVersion,preferences:preferences(db,userId),queue:{active:counts.RUNNING||0,pending:counts.QUEUED||0,failed:counts.FAILED||0,paused:r.status!=='CONNECTED'||!preferences(db,userId).botMessages&&!db.prepare("SELECT 1 FROM ai_jobs WHERE user_id=? AND kind!='event' AND status IN ('QUEUED','RUNNING') LIMIT 1").get(userId)},error:r.error,lastCheckedAt:r.lastCheckedAt};}
function enqueue(db,userId,id,event,kind='event'){const ctx=botContext(db,userId,id,event);event={...event,...dialogueIntent(ctx,event)};if(kind==='event'&&!verifiedTournamentEvent(ctx,event))throw fail(409,'Tournament dialogue facts do not match the recorded tournament');const jobId=uuid(),priority=kind!=='event'?0:eventEligibility(ctx,event).priority;db.prepare('INSERT OR IGNORE INTO ai_jobs(id,user_id,bot_id,event_id,kind,priority,status,request_json,created_at,updated_at) VALUES(?,?,?,?,?,?,\'QUEUED\',?,?,?)').run(jobId,userId,id,event.id||null,kind,priority,JSON.stringify({event,context:ctx}),Date.now(),Date.now());const row=event.id?db.prepare('SELECT id FROM ai_jobs WHERE user_id=? AND event_id=?').get(userId,event.id):{id:jobId};kick(db);return row.id;}
function collectPending(db,userId){const p=preferences(db,userId);if(!p.botMessages)return;for(const row of db.prepare('SELECT id,bot_id,type,payload_json,created_at FROM structured_events WHERE user_id=? AND messaged_at IS NULL ORDER BY created_at LIMIT 200').all(userId)){if(!row.bot_id)continue;const direct=['PLAYER_REPLY','PLAYER_MESSAGE'].includes(row.type);if(direct?!p.playerReplies:!p.botInitiated)continue;if(db.prepare('SELECT 1 FROM ai_jobs WHERE user_id=? AND event_id=?').get(userId,row.id))continue;const event={...JSON.parse(row.payload_json),id:row.id,type:row.type,occurredAt:row.created_at};
  // Eligibility needs social identity, form and trust only. Build the heavy,
  // authoritative world context once, only when a job can actually be queued.
  const bot=db.prepare('SELECT b.name,b.form,s.personality_json,s.player_trust FROM bots b JOIN bot_social_profiles s ON s.user_id=b.user_id AND s.bot_id=b.bot_id WHERE b.user_id=? AND b.bot_id=?').get(userId,row.bot_id);if(!bot)continue;
  const ctx={botId:row.bot_id,name:bot.name,form:bot.form,socialProfile:JSON.parse(bot.personality_json),relationship:{playerTrust:bot.player_trust}};
  Object.assign(event,dialogueIntent(ctx,event));const last=db.prepare("SELECT MAX(created_at) AS at FROM messages WHERE user_id=? AND bot_id=? AND direction='bot'").get(userId,row.bot_id).at||0,eligible=eventEligibility(ctx,event,last);if(!eligible.eligible){if(eligible.reason!=='personality cooldown'||event.type==='MATCH_CONVERSATION')db.prepare('UPDATE structured_events SET messaged_at=? WHERE id=?').run(Date.now(),row.id);continue;}if(!initiationBudget(db,userId,event,eligible.priority))continue;if(!topicAvailable(db,userId,row.bot_id,ctx,event,eligible)){db.prepare('UPDATE structured_events SET messaged_at=? WHERE id=?').run(Date.now(),row.id);continue;}try{enqueue(db,userId,row.bot_id,event);}catch(error){if(error.status!==409)throw error;db.prepare('UPDATE structured_events SET messaged_at=? WHERE id=?').run(Date.now(),row.id);}}}
async function processEvents(db,userId){runtime(db);collectPending(db,userId);kick(db);return {sent:0,pending:true};}
function cancelDeleted(db,userId,eventId){if(eventId)db.prepare("UPDATE ai_jobs SET status='CANCELLED',updated_at=? WHERE user_id=? AND event_id=? AND status IN ('QUEUED','RUNNING')").run(Date.now(),userId,eventId);}
function forgetDeleted(db,userId,id,messageId,eventId){
  const row=db.prepare('SELECT important_memories_json,opinions_json FROM bot_social_profiles WHERE user_id=? AND bot_id=?').get(userId,id);if(!row)return;
  const generationId=db.prepare('SELECT id FROM ai_generations WHERE user_id=? AND job_id IN (SELECT id FROM ai_jobs WHERE user_id=? AND event_id=?)').get(userId,userId,eventId)?.id;
  const memories=JSON.parse(row.important_memories_json).filter(m=>m.id!==messageId&&m.id!==eventId),opinions=JSON.parse(row.opinions_json).filter(m=>!generationId||m.generationId!==generationId);
  db.prepare('UPDATE bot_social_profiles SET important_memories_json=?,opinions_json=? WHERE user_id=? AND bot_id=?').run(JSON.stringify(memories),JSON.stringify(opinions),userId,id);
}
function initiationBudget(db,userId,event,priority){
  if(/^PLAYER/.test(event.type))return true;
  const rows=db.prepare("SELECT priority FROM ai_jobs WHERE user_id=? AND kind='event' AND status!='CANCELLED' AND created_at>? AND json_extract(request_json,'$.event.type') NOT LIKE 'PLAYER%' ").all(userId,Date.now()-3600000);
  return rows.length<(priority<=1?6:4);
}
function topicAvailable(db,userId,id,context,event,eligibility,now=Date.now()){
  if(/^PLAYER/.test(event.type))return true;
  const patch=event.currentPatch||event.patchId;
  if(patch&&/BALANCE|BUFF|NERF|NEW_WEAPON/.test(event.type)){
    const reserved=db.prepare("SELECT bot_id,request_json FROM ai_jobs WHERE user_id=? AND kind='event' AND status!='CANCELLED' AND (json_extract(request_json,'$.event.currentPatch')=? OR json_extract(request_json,'$.event.patchId')=?)").all(userId,patch,patch).filter(row=>/BALANCE|BUFF|NERF|NEW_WEAPON/.test(JSON.parse(row.request_json).event?.type));
    if(reserved.some(row=>row.bot_id===id)||new Set(reserved.map(row=>row.bot_id)).size>=2)return false;
  }
  const topicCooldown=eligibility.priority<=1?6*3600000:Math.max(12*3600000,eligibility.cooldownMs*3),recent=db.prepare("SELECT request_json,created_at FROM ai_jobs WHERE user_id=? AND bot_id=? AND kind='event' AND status!='CANCELLED' AND created_at>? ORDER BY created_at DESC LIMIT 100").all(userId,id,now-Math.max(topicCooldown,eligibility.cooldownMs));
  return !recent.some(row=>{const previous=JSON.parse(row.request_json).event||{},intent=dialogueIntent(context,previous);return !/^PLAYER/.test(previous.type)&&(intent.topic===event.topic&&now-row.created_at<topicCooldown||eligibility.priority>1&&now-row.created_at<eligibility.cooldownMs);});
}
function repetitionGuard(output,context){
  const normalized=text=>String(text).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),body=normalized(output.body),words=new Set(body.split(' ').filter(Boolean));
  for(const message of context.recentMessages||[]){if(message.direction!=='bot')continue;const previous=normalized(message.body),other=new Set(previous.split(' ').filter(Boolean)),intersection=[...words].filter(word=>other.has(word)).length,similarity=intersection/(words.size+other.size-intersection);
    if(previous===body||Math.min(words.size,other.size)>=8&&similarity>=.82)throw Error('Repeated recent bot dialogue. Choose a different supported point and wording for this event; do not paraphrase the previous message.');
  }
  return output;
}
function tournamentGuard(output,context){
  const facts=context.authoritativeGameFacts,event=context.dialogueEvent||{},tournaments=(facts.tournaments||[]).filter(t=>!event.tournamentId||t.id===event.tournamentId),body=output.body,hasTournament=/tournament/i.test(body)||/^TOURNAMENT/.test(event.type);
  if(!hasTournament)return output;
  const unknown=/unknown|don't know|do not know|not supplied|no .*result|can't|cannot|hasn't|has not|no winner|haven't|haven’t|didn't|did not|never won|not .*know|not .*champion|might|could|predict|hope|if /i;
  for(const sentence of body.split(/(?<=[.!?])\s+/)){
    if(unknown.test(sentence))continue;
    const winning=/\b(?:won|winner|champion|victor)\b/i.test(sentence),seriesClaim=/quarter|semi|round|series|game|match/i.test(sentence)&&!/champion|tournament winner|won (?:the |this )?tournament/i.test(sentence);
    if(winning){const records=seriesClaim?tournaments.flatMap(t=>(t.series||[]).filter(s=>s.winnerTeamId).map(s=>({winnerTeamName:t.teams.find(team=>team.id===s.winnerTeamId)?.name,winnerParticipants:t.teams.find(team=>team.id===s.winnerTeamId)?.participants.map(p=>p.name)||[]}))):tournaments.map(t=>t.results).filter(result=>result&&typeof result.winnerTeamName==='string'&&Array.isArray(result.winnerParticipants)),mock=context.developerScenario?.tournamentWinner;
      if(mock)records.push({winnerTeamName:typeof mock==='string'?mock:mock.name,winnerParticipants:[]});
      if(!records.length)throw Error('Unsupported tournament winner');
      const named=PROFILES.filter(p=>new RegExp('\\b'+p.name+'\\b','i').test(sentence)).map(p=>p.name),knownTeam=tournaments.flatMap(t=>t.teams||[]).filter(team=>sentence.toLowerCase().includes(team.name.toLowerCase())).map(team=>team.name),allowed=records.flatMap(result=>[result.winnerTeamName,...result.winnerParticipants]).filter(Boolean);
      if([...named,...knownTeam].some(name=>!allowed.includes(name))||/\b(?:we|i|our|my)\b/i.test(sentence)&&!allowed.includes(context.name))throw Error('Unsupported tournament winner identity');
    }
    if(/face|facing|opponent|against|eliminat|beat|defeat|lost to|final/i.test(sentence)&&/^TOURNAMENT/.test(event.type)){
      const allowed=tournaments.flatMap(t=>{const teamIds=new Set([t.botTeamId,...(t.series||[]).filter(s=>s.teamIds.includes(t.botTeamId)).flatMap(s=>s.teamIds)]);return t.teams.filter(team=>teamIds.has(team.id)).flatMap(team=>team.participants.map(p=>p.name));});
      if(PROFILES.some(p=>p.name!==context.name&&new RegExp('\\b'+p.name+'\\b','i').test(sentence)&&!allowed.includes(p.name)))throw Error('Unsupported tournament opponent: no recorded matchup supplies that player');
    }
  }
  return output;
}
function mapGeometryGuard(output){
  const normalized=output.body.replace(/[\u2010-\u2015]/g,'-').replace(/[’‘]/g,"'");
  for(const sentence of normalized.split(/(?<=[.!?])\s+/)){
    const denies=/\b(?:do not|does not|don't|doesn't|cannot|can't|not|no|without|never|aren't|isn't)\b/i.test(sentence);
    const roof=/\b(?:roofs?|rooftops?|rooflines?)\b/i.test(sentence)&&/\b(?:vertical|high[ -]ground|elevation|elevated|vantage|upper floors?|higher angles?|height advantage|shoot(?:ing)? down|climb(?:ing)?|stand(?:ing)? on)\b/i.test(sentence);
    const paint=/\b(?:crosswalks?|road markings?|painted (?:lines?|roads?|crossings?))\b/i.test(sentence)&&/\b(?:cover|protection|protects?|blocks? (?:shots?|bullets?|fire)|hiding|hide behind)\b/i.test(sentence);
    if(!denies&&(roof||paint))throw Error('Unsupported map geometry: Brightfield Blocks combat stays on its existing flat plane; roofs provide no playable height or vertical firing advantage, and painted crosswalks or road markings provide no cover. The visual detail pass changed no collision or sightline rules.');
  }
  return output;
}
function publicFactGuard(output,context){
  const facts=context.authoritativeGameFacts,query=facts.query||{},body=output.body.normalize('NFKC').replace(/[’‘]/g,"'").replace(/[\u2010-\u2015]/g,'-').replace(/\s+/g,' ').replace(/,/g,''),ranked=facts.ranked,board=facts.leaderboard;
  const rankNames=require('../progression.js').ranks.map(rank=>rank.name),titles=rankNames.filter(name=>new RegExp('\\b'+name+'\\b','i').test(body));
  const ratingClaims=[...body.matchAll(/\b(\d+(?:\.\d+)?)\s*-?\s*(?:elo|ranked points?)\b/gi),...body.matchAll(/\b(?:elo|rating)(?:\s+(?:is|of|at|sits at))?\s*[:=]?\s*(\d+(?:\.\d+)?)\b/gi)].map(match=>Number(match[1]));
  // These are the selected contact's facts, never the account's XP or Power.
  if(titles.length||ratingClaims.length){if(!ranked?.available)throw Error('Unsupported ranked claim: the selected bot has no available ranked record');if(titles.some(title=>title.toLowerCase()!==ranked.rankName.toLowerCase())||ratingClaims.some(value=>Math.abs(value-ranked.rating)>.0001))throw Error('Ranked identity/value mismatch: use '+context.name+"'s full rank "+ranked.rankName+' at '+ranked.rating+' ELO. Power, leaderboard position and account level are separate.');}
  if(query.kind==='ambiguous-rank'){
    if(!body.includes('?')||titles.length||ratingClaims.length||/\b\d+(?:st|nd|rd|th)\b|#\s*\d+/.test(body))throw Error('Ambiguous rank question: ask which leaderboard or ranked ladder is meant, without guessing a position');
  }
  if(query.kind==='ranked'&&ranked?.available){
    if(!titles.includes(ranked.rankName)||!ratingClaims.includes(ranked.rating))throw Error('Answer the ranked question directly using the selected bot\'s full rank title and exact ELO');
  }
  if(query.kind==='leaderboard'){
    if(/^tdm\b/i.test(board?.mode||''))for(const claim of body.matchAll(/\b(?:across|in|for|covering|combining|includes?)\s+(?:all|every|both)\s+(?:eligible\s+)?(?:game\s+)?modes\b|\ball[- ]modes?\s+(?:bot\s+)?leaderboard\b|\b(?:across|including)\s+(?:tdm|team deathmatch)\s+and\s+(?:deathmatch|ffa)\b/gi)){
      const before=body.slice(Math.max(0,claim.index-45),claim.index),after=body.slice(claim.index+claim[0].length).split(/[.!?]/,1)[0],deniedAfter=/^\s*(?:[,:;-]\s*)?(?:(?:is|are)\s+(?:unavailable|unsupported|missing)|(?:isn't|aren't|doesn't|don't|is not|are not|does not|do not)\s+(?:available|supported|provided|offered|exist|combine|cover))/i.test(after);if(!deniedAfter&&!/\b(?:not|no|doesn't|does not|cannot|can't)\b[^.!?]*$/i.test(before))throw Error('Leaderboard scope mismatch: the Bot Leaderboard covers lifetime TDM, including standard and ranked, not all modes or Deathmatch');
    }
    if(board?.sortMetric==='kd'&&Number.isFinite(board.metricValue)){
      if(/\bk\s*\/\s*d(?:\s+ratio)?\s+(?:is\s+|remains\s+|would be\s+)?(?:undefined|unknown|unavailable|not defined)\b/i.test(body))throw Error('Leaderboard metric mismatch: the shared table supplies '+board.metricValue+' K/D. Do not call that metric undefined or unavailable.');
      const claims=[...body.matchAll(/\b(\d+(?:\.\d+)?)\s*k\s*\/\s*d\b/gi),...body.matchAll(/\bk\s*\/\s*d(?:\s+ratio)?\s*(?:is|of|at|:|=)?\s*(\d+(?:\.\d+)?)/gi)];
      if(claims.some(claim=>Math.abs(Number(claim[1])-board.metricValue)>.0051))throw Error('Leaderboard K/D does not match the selected bot in the supplied table scope');
    }
    const positions=[...body.matchAll(/(?:#\s*|(?:rank|position|place|number|no\.)\s*(?:is\s*|at\s*|of\s*)?)(\d+)\b/gi),...body.matchAll(/\b(\d+)(?:st|nd|rd|th)\b/gi)].map(match=>Number(match[1]));
    const ordinals=['first','second','third','fourth','fifth','sixth','seventh','eighth','ninth','tenth','eleventh','twelfth','thirteenth','fourteenth','fifteenth','sixteenth','seventeenth','eighteenth','nineteenth','twentieth'];
    for(const [index,word] of ordinals.entries())if(new RegExp('\\b'+word+'\\b','i').test(body))positions.push(index+1);
    if(positions.some(position=>position!==board?.position)||!board?.available&&positions.length)throw Error('Unsupported leaderboard position: use only the selected bot\'s requested mode, cohort and sort scope');
    if(board?.available&&!positions.includes(board.position))throw Error('Answer the leaderboard question directly with the supplied position '+board.position+'; do not substitute ranked ELO, Power or XP level');
    if(titles.length||ratingClaims.length)throw Error('Leaderboard and ranked ladder were mixed: answer the requested leaderboard position');
  }
  return output;
}
function weaponNumericGuard(output,context){
  const facts=context.authoritativeGameFacts,body=output.body.replace(/[\u2010-\u2015]/g,'-');
  for(const claim of body.matchAll(/\b(?:one|two|three|four|five|\d+)[ -]hits?\s+(?:spread|dispersion|cone)\b/gi)){
    const before=body.slice(Math.max(0,claim.index-30),claim.index);if(!/\b(?:not|no|isn't|is not)\s+(?:an?\s+)?$/i.test(before))throw Error('Required hit count is not projectile spread or a compensating accuracy mechanic. Use the supplied dispersion values, or express only an own reaction.');
  }
  if(/\b(?:most|all|every|the majority of)\s+(?:players?|people|bots?|competitors?)\b.{0,90}\b(?:use|using|run|running|prefer|switch|choose|equip|love|hate)\b/i.test(body))throw Error('Unsupported population preference claim. Aggregate weapon telemetry does not identify what most players prefer or will use. State this competitor\'s own opinion.');
  for(const sentence of body.split(/(?<=[.!?])\s+/))if(/\b(?:the\s+)?meta\s+(?:(?:still|currently)\s+)?(?:values|favors|favours|prefers|rewards)\b/i.test(sentence)&&!/\b(?:I think|I reckon|to me|for me|my (?:view|opinion)|I['’]d say)\b/i.test(sentence))throw Error('Unsupported meta assessment: cohort statistics and Gun Score do not establish community preference or consensus. State supported measurements or clearly attribute a personal opinion.');
  for(const sentence of body.split(/(?<=[.!?])\s+/)){
    const named=facts.weapons.filter(weapon=>weaponMention(sentence,weapon.name)),weapon=named.length===1?named[0]:facts.weapons.length===1?facts.weapons[0]:null;
    if(!weapon||named.length>1)continue;
    const stats=weapon.stats,history=(facts.activeBalanceChanges?.changes||[]).filter(change=>change.weapon===weapon.name),historical=/\b(?:was|were|used to|previous|before|from|old|reduced|increased|dropped|raised)\b/i.test(sentence);
    for(const claim of sentence.matchAll(/\b(?:from\s+)?(\d+)\s*(?:to|→)\s*(\d+)\s+(?:body\s+)?hits\b/gi))if(Number(claim[2])!==weapon.mechanics.bodyHits&&[stats.damage,context.developerScenario?.currentBodyDamage].includes(Number(claim[2])))throw Error('Damage was mislabeled as hits. '+claim[2]+' is damage per body hit; the current body hit count is '+weapon.mechanics.bodyHits+'.');
    const checks=[
      ['damage',stats.damage,/(?:\bbody damage\s*(?:is|of|at|:|=)?\s*(\d+(?:\.\d+)?))|(?:(?<![\w-])(\d+(?:\.\d+)?)\s*(?:body damage|body dmg))/gi],
      ['head',stats.head,/(?:\bhead(?:shot)? damage\s*(?:is|of|at|:|=)?\s*(\d+(?:\.\d+)?))|(?:(?<![\w-])(\d+(?:\.\d+)?)\s*(?:headshot damage|head damage))/gi],
      ['reload',stats.reload,/(?:\breload(?: time)?\s*(?:is|of|at|:|=)?\s*(\d+(?:\.\d+)?)\s*(?:s\b|seconds?))|(?:(?<![\w-])(\d+(?:\.\d+)?)\s*(?:s\b|seconds?)[ -]*reload)/gi],
      ['rpm',weapon.mechanics.roundsPerMinute,/(?<![\w-])(\d+(?:\.\d+)?)\s*(?:rpm|rounds per minute)\b/gi],
      ['mag',stats.mag,/(?:\bmagazine(?: size)?\s*(?:is|of|at|:|=)?\s*(\d+))|(?:(?<![\w-])(\d+)\s*[- ](?:round|shell)\s+magazine)/gi]
    ];
    for(const [field,expected,pattern] of checks)for(const claim of sentence.matchAll(pattern)){
      const value=Number(claim[1]||claim[2]),allowed=[expected,...(historical?history.filter(change=>change.field===field).flatMap(change=>[change.before,change.after]):[]),...(historical&&field==='damage'&&context.developerScenario?.weapon===weapon.name?[context.developerScenario.previousBodyDamage]:[])];
      if(!allowed.some(fact=>Number.isFinite(fact)&&Math.abs(value-fact)<(field==='rpm'?1:.011)))throw Error('Unsupported '+weapon.name+' '+field+' value: use its supplied exact current constants or recorded before/after changes');
    }
  }
  for(const match of body.matchAll(/\bb-[a-f0-9]{8}(?:-\d+)?\b/gi))if(![facts.currentPatchId,facts.activeBalanceChanges?.from,facts.activeBalanceChanges?.to].includes(match[0]))throw Error('Unsupported patch identifier');
  for(const profile of PROFILES)if(profile.name!==context.name&&new RegExp("\\b(?:I am|I'm|my name is)\\s+"+profile.name+'\\b','i').test(body))throw Error('The response changed the selected contact identity');
  return output;
}
function mechanicalGuard(output,context){
  const body=output.body.replace(/[\u2010-\u2015]/g,'-'),facts=context.authoritativeGameFacts;
  const allNames=(facts.weaponRegistry||facts.weapons).map(weapon=>weapon.name);for(const name of allNames){if(weaponMention(body,name)&&!facts.weapons.some(w=>w.name===name)&&/\d.{0,30}(?:damage|dmg|hp|rpm|tiles|seconds|body hit|headshot|rounds|magazine)/i.test(body))throw Error('Unsupported mechanical claim for '+name+': no statistics for that weapon were supplied. Do not invent its damage, range, cadence or hit count.');}
  for(const sentence of body.split(/(?<=[.!?])\s+/))for(const name of allNames)if(weaponMention(sentence,name)&&!facts.weapons.some(weapon=>weapon.name===name)&&/\b(?:tighter|narrower|wider|faster|slower|higher|lower|longer|shorter|more|less)\s+(?:(?:hip|walking|sprint|ads|headshot|body|projectile)\s+)?(?:spread|dispersion|damage|range|reload|fire rate|cadence|speed|accuracy|magazine|capacity)\b(?!\s+(?:data|information|evidence|samples|testing)\b)/i.test(sentence))throw Error('Unsupported mechanical comparison for '+name+': its statistics were not supplied. A personal preference is allowed; do not invent tighter spread, faster reload or another physical advantage.');
  const aug=facts.weapons.find(w=>w.name==='SR-Aug');
  if(aug&&(facts.weapons.length===1||weaponMention(body,'SR-Aug'))){
    for(const claim of body.matchAll(/bursts?\s+(?:every|each|at)\s*(\d+(?:\.\d+)?)\s*(ms|milliseconds|s\b|seconds?)/gi)){
      const seconds=Number(claim[1])*(/^m/i.test(claim[2])?.001:1);
      if(Math.abs(seconds-aug.stats.hitSpeed)>.005)throw Error('SR-Aug burst STARTS repeat every '+aug.stats.hitSpeed+' seconds. Only the individual bullets WITHIN a burst are spaced 0.065 seconds apart. Do not confuse these intervals.');
    }
    if(/(?:three|3)\s+pellets|(?:three|3).{0,35}(?:simultaneous|at the same time)/i.test(body))throw Error('SR-Aug fires three independent bullets at 0, 0.065 and 0.130 seconds, not shotgun pellets or simultaneous hits.');
    const countWords={one:1,single:1,two:2,three:3,four:4,five:5},rounds=aug.mechanics.roundsPerBurst;
    for(const claim of body.matchAll(/\b(one|single|two|three|four|five|\d+)\s*[- ]\s*(?:individual\s+|independent\s+)?(?:bullets?|rounds?|projectiles?)\s+(?:per|in (?:a|each|one))\s+bursts?\b/gi)){
      const before=body.slice(Math.max(0,claim.index-45),claim.index);
      if(/(?:not|never|isn['’]?t|doesn['’]?t|instead of|rather than)\s+(?:(?:fire|shoot|contain|have|just|only)\s+){0,2}$/i.test(before))continue;
      const count=countWords[claim[1].toLowerCase()]??Number(claim[1]);
      if(count!==rounds)throw Error('SR-Aug fires '+rounds+' independent bullets PER BURST. Each trigger activation launches all '+rounds+' separate rounds with short spacing; one projectile does not mean one round per burst.');
    }
  }
  const pump=facts.weapons.find(w=>w.name==='Pump Shotgun'),scenario=context.developerScenario;
  if(pump?.mechanics.bodyHits===3&&(facts.weapons.length===1||/pump|125|124/i.test(body))){
    if(/(?:a )?headshot is (?:still )?required for a kill|(?:you |i |we )?(?:must|have to) (?:land|hit) a headshot to kill/i.test(body)&&!/one[ -]shot|single shot/i.test(body))throw Error('A headshot is optional: three full body blasts kill250HP. Do not claim a headshot is required for every kill.');
    if(/\b48\s*fps\b/i.test(body))throw Error('Pump projectile speed is48tiles/second (3360world units/second), not48FPS. Frame rate was not measured.');
    if(/(?:doesn['’]?t|does not|won['’]?t|will not) (?:affect|change) (?:the )?(?:kill|body|hit|two-shot|two-hit)|(?:required |body )?hit count (?:stays|remains)|break[ -]?point (?:stays|remains)|still (?:only )?(?:two|2)[ -]body[ -]hit/i.test(body))throw Error('Pump breakpoint changed: 125×2=250 killed in TWO blasts; 124×2=248 leaves 2 HP and requires THREE blasts. Body TTK doubles from 1.5 to 3.0 seconds.');
    if(/(?:a )?single body hit.{0,35}(?:only |just )?2[ -]?HP|two body hits.{0,35}2[ -]?HP.{0,20}instead of (?:3|three)|a body shot first.{0,100}(?:2|two)[ -]?HP|(?:one|1) hit less|(?:one|1) (?:less|fewer) (?:body )?(?:hit|blast|shot)/i.test(body))throw Error('Incorrect Pump arithmetic: one 124-damage hit leaves 126 HP, two leave 2 HP; the old 125-damage two-hit kill left ZERO HP. The new hit count is one MORE, not less.');
    const claims=body.split(/(?<=[.!?])\s+/);
    for(const claim of claims){const two=/\b(?:two|2)(?:[ -](?:body|shot|hit|blast|bodies|clean|full|body-hit|body-shot))*\b/i.test(claim);
      const denies=/no longer|not enough|cannot|can't|won't|wouldn't|doesn't|don’t|do not|don't|used to|before|previously|instead of two|needs? (?:a )?third|(?:three|3)[ -](?:body|hit|shot)|leaves? (?:them |someone |somebody |you |an? enemy |an? opponent )?(?:on |with |at )?2(?:[ -]?HP| health)|248/i.test(claim);
      if(two&&/still kills|still need two|remains? the same|(?:two|2) (?:hits|shots|blasts) (?:to )?(?:kill|finish)|(?:two|2)[ -](?:shot|hit)(?:[ -]kill)? (?:is|remains|stays|still)/i.test(claim)&&!denies)throw Error('Pump breakpoint contradiction: current 124×2=248 leaves 2 HP at 250 HP. Minimum is THREE body blasts, not two; head damage is '+pump.stats.head+'.');
    }
    if(/35[ -]?(?:damage|dmg)? head/i.test(body)&&!facts.weapons.some(w=>w.name==='P90'))throw Error('Mixed weapon mechanics: Pump head damage is '+pump.stats.head+', not 35. Use only this weapon’s supplied mechanics.');
    if(/\b(?:3|4)[ -]tile (?:burst|ammo|round)/i.test(body))throw Error('Invented weapon mechanic: tiles measure distance, not an ammunition or burst type.');
  }
  if(/\b(one[ -]?shot|single[ -]?(?:shot|hit))\b/i.test(body)&&/P90/i.test(body)&&!/(?:not|never|no|isn't|isn’t|cannot|can't|nowhere|far|requires|need|eight|8)/i.test(body))throw Error('Unsupported P90 one-shot claim: 35×7=245<250; eight base-damage head hits are required.');
  if(/\b70[ -]?(?:rpm|rounds per minute)\b/i.test(body)&&/P90/i.test(body)){const p90=facts.weapons.find(w=>w.name==='P90');throw Error('P90 speed70 is projectile speed, not RPM. Fire interval '+p90?.stats.hitSpeed+' seconds means approximately '+Math.round(60/p90?.stats.hitSpeed)+' rounds/minute.');}
  if(/\d+\s*%\s*(?:kill[ /-]?death|k\/?d)(?: ratio)?/i.test(body))throw Error('K/D is kills divided by deaths, not a percentage. 800 kills /400 deaths is2.0K/D, not50%.');
  if(/\b(?:\d+(?:\.\d+)?%|\d+\s*:\s*\d+)\s*win[ -]?rate/i.test(body)&&scenario&&!Number.isFinite(scenario.winRate)&&!Number.isFinite(scenario.wins)&&!Number.isFinite(scenario.personalCurrentPatch?.wins)&&!Number.isFinite(scenario.globalCurrentPatch?.wins))throw Error('Unsupported numeric win rate: kills/deaths establish K/D only; no wins or losses were supplied.24kills/8deaths is3.0K/D, not a3:1win rate.');
  if(/(?:high|great|strong|low|poor) win[ -]?rate/i.test(body)&&scenario&&!Number.isFinite(scenario.winRate)&&!Number.isFinite(scenario.wins)&&!facts.season.record?.games)throw Error('No win-rate evidence was supplied. Kills/deaths or Gun Score do not establish win rate.');
  if(/(?:advantage|better|improv|buff)/i.test(body)&&/\b2\s*HP\b/i.test(body)&&!/(?:not|loss|worse|nerf|harm|no longer)/i.test(body))throw Error('Incorrect damage-breakpoint consequence');
  mapGeometryGuard(output);publicFactGuard(output,context);weaponNumericGuard(output,context);return tournamentGuard(output,context);
}
function comparisonFacts(context,event){
  const scenario=context.developerScenario||{},weapon=scenario.weapon||event.weapon,change=event.changes?.damage||event.changes?.find?.(c=>c.weapon===weapon&&c.stat==='damage'),before=scenario.previousBodyDamage??change?.from,after=scenario.currentBodyDamage??change?.to;
  if(!Number.isFinite(before)||!Number.isFinite(after)||before<=0||after<=0)return scenario.globalCurrentPatch||scenario.personalCurrentPatch?{source:'explicitly mocked developer scenario',weapon,global:measuredKd(scenario.globalCurrentPatch),personal:measuredKd(scenario.personalCurrentPatch),meaning:'K/D is kills divided by deaths. A ratio is not a win rate; wins/losses were not supplied.'}:null;
  const current=context.authoritativeGameFacts.weapons.find(w=>w.name===weapon),hp=250,interval=current?.stats.hitSpeed;
  return {weapon,source:context.developerScenario?'explicitly mocked developer scenario':'recorded balance patch change',maxHP:hp,previous:{bodyDamage:before,twoBodyHitsDamage:before*2,remainingHPAfterTwoBodyHits:Math.max(0,hp-before*2),bodyHits:Math.ceil(hp/before),bodyTTK:interval*(Math.ceil(hp/before)-1)},current:{bodyDamage:after,oneBodyHitRemainingHP:Math.max(0,hp-after),twoBodyHitsDamage:after*2,remainingHPAfterTwoBodyHits:Math.max(0,hp-after*2),bodyHits:Math.ceil(hp/after),bodyTTK:interval*(Math.ceil(hp/after)-1)}};
}
function conversationBrief(context,event){
  const type=String(event.type||''),direct=/^PLAYER/.test(type),personalWeapon=/^PERSONAL_WEAPON_(?:BREAKOUT|COLLAPSE)$/.test(type),weapon=event.weapon||event.match?.primary||event.changes?.[0]?.weapon||context.developerScenario?.weapon;
  const purpose=direct?'Answer the latest player message directly. Continue their topic; avoid an automatic follow-up question. If they ask for your choice, give your own first-person stance instead of generic advice.':personalWeapon?'React to YOUR supplied weapon result or attachment to the weapon. State an own feeling, preference or choice first. This personal sample is the topic; background patch notes must not replace it with an unrelated balance question. Do not infer community dominance from your small sample.':/^TOURNAMENT/.test(type)?'React to this recorded tournament development. Discuss an actual commitment, opponent, outcome or next choice; do not send a generic attendance reminder.':/BALANCE|BUFF|NERF|NEW_WEAPON/.test(type)?'React personally to one actual change for this competitor. Give an own feeling or choice, not a mechanics walkthrough or patch report. Do not forecast what other players will use or invent a meta consensus.':type==='MATCH_CONVERSATION'?'Respond to one meaningful feature of this recorded match. Do not imply the human participated unless the event records it.':/META|WEAPON/.test(type)?'Discuss the supplied current-patch trend or loadout choice. Separate measured performance from a personal preference and acknowledge limited samples.':'React to this specific recorded milestone or change in character. Avoid generic motivation or status summaries.';
  const social=context.socialProfile?.social||{},voiceFocus=social.socialness<=.3?'A quiet, restrained own reaction; normally one brief sentence, without running commentary.':social.technicality<=.4?'A natural own reaction or joke, with at most one numeric detail if essential; avoid a mechanical explanation.':'A precise own reaction; choose the one useful detail instead of reciting all supplied statistics.';
  return {purpose,voiceFocus,weapon:weapon||null,act:personalWeapon?'reaction':event.act||'reaction',freshPointRequired:!direct,questionLimit:1,avoidRecentTopics:(context.recentMessages||[]).filter(row=>row.direction==='bot').slice(-3).map(row=>row.subject||row.body.slice(0,90))};
}
function conversationQualityGuard(output,context,event){
  const body=output.body.trim();
  if(STYLE_EXAMPLES.some(example=>example.line.toLowerCase()===body.toLowerCase()))throw Error('A style example was copied. Use the actual facts and this contact\'s own wording.');
  if(/^PERSONAL_WEAPON_(?:BREAKOUT|COLLAPSE)$/.test(event.type)&&(!/\b(?:I|me|my|mine)\b/i.test(body)||body.split(/(?<=[.!?])\s+/).every(sentence=>sentence.endsWith('?'))))throw Error('The personal weapon event needs this competitor\'s own reaction or choice about their supplied result, not a question-only detour into background patch notes.');
  const direct=/^PLAYER/.test(String(event.type||''));
  if(!direct&&(/^(?:hey[,.!]?\s*)?(?:just checking in|quick reminder|friendly reminder|don['’]t forget to|remember to check)\b/i.test(body)||/^(?:good luck(?: out there)?|keep (?:it up|practicing|grinding)|ready for (?:the next|another) (?:match|game)|let['’]s (?:go|get it)|what do you think)[?!. ]*$/i.test(body)))throw Error('Low-value reminder or filler. Make one specific, personality-led point about the supplied event; do not invent a result or reuse a recent point.');
  if(/\byou (?:should|need to|have to|must|could improve|can improve)\b.{0,65}\b(?:aim|shoot|use|equip|switch|practice|position|flank|reload|cover|burst|strafe|try|focus|weapon|loadout|movement)\b|\byour (?:aim|positioning|movement|accuracy|gameplay|playstyle)\s+(?:is|was|needs|looks|has)\b|(?:^|[.!?]\s+)(?:try (?:using|aiming|switching)|focus on (?:your|aim|position|cover)|practice (?:your|aim|shooting)|keep (?:practicing|improving)|remember to (?:reload|aim|use cover))\b/i.test(body))throw Error('Gameplay coaching rejected. Give this competitor\'s own reaction or preference, without evaluating or instructing the human.');
  if(/\b(?:if|when) you(?: ever)? (?:need|want|are looking for)\b[^.!?]{0,130}\b(?:I['’]d|I would|you (?:could|should))\s+(?:swap|switch|equip|use|try|pick|choose|recommend|go with)\b/i.test(body))throw Error('Conditional gameplay coaching rejected. State this competitor\'s own preference without prescribing a loadout for the human.');
  if(/\b(?:if|when) you(?:['’]re| are)\b[^.!?]{0,150}(?:\b(?:it|this|that)(?:['’]s| is) your (?:jam|(?:kind of )?(?:weapon|gun)|pick|best bet)\b|\b(?:perfect|ideal|a good fit|a great fit|well[ -]suited|right)\s+for you\b|\b(?:would|will|should)\s+suit you\b|\bsuits? your (?:playstyle|style|needs)\b|\byou['’]ll love (?:it|this|that)\b)/i.test(body))throw Error('Conditional gameplay coaching rejected. Do not prescribe a weapon for an assumed human playstyle; express only this competitor\'s own preference.');
  if(!direct&&/WEAPON|BUFF|NERF|BALANCE|META|MATCH/.test(event.type))for(const sentence of body.split(/(?<=[.!?])\s+/))if(/\byou (?:can|could)\s+(?:(?:just|still|even|always|easily)\s+)?(?:stack|fire|spray|shoot|burst|rush|flank|reload|aim|strafe|dash|take cover|swap|switch)\b/i.test(sentence)&&!/\b(?:shoot|fire)\s+(?:me\s+)?(?:an?\s+)?(?:message|question)\b/i.test(sentence))throw Error('Unsolicited gameplay coaching rejected. Describe the competitor\'s own reaction without directing the human\'s combat actions.');
  if(/\b(?:great|good|nice|excellent) (?:aim|positioning|accuracy)|\byou(?:'re| are| have been) (?:improving|getting better|playing (?:well|better))\b/i.test(body))throw Error('Performance praise-as-coaching rejected. Do not invent or evaluate the human\'s performance.');
  return output;
}
async function generate(context,event,prefs,r,repair=null){const prompt=[{role:'system',content:buildSystemPrompt(context)},{role:'user',content:JSON.stringify({bot:{botId:context.botId,name:context.name,power:context.power,playstyle:context.playstyle,form:context.form},authoritativeGameFacts:context.authoritativeGameFacts,verifiedArithmetic:comparisonFacts(context,event),relationship:context.relationship,conversationSummary:context.conversationSummary,importantMemories:context.importantMemories,opinions:context.opinions,recentMessages:context.recentMessages,conversationBrief:conversationBrief(context,event),event,...(context.developerScenario?{developerScenario:context.developerScenario,scenarioIsMock:true}:{})})}];if(repair)prompt.push({role:'assistant',content:repair.raw.slice(0,5000)},{role:'user',content:'Repair the JSON and factual reasoning. Validation failed: '+repair.error+'. Use only supplied facts. Return the required six fields.'});
  const truncated=repair?.truncated===true;
  r.abort=new AbortController();const signal=AbortSignal.any([r.abort.signal,AbortSignal.timeout(Number(process.env.SAR_OLLAMA_TIMEOUT_MS)||120000)]),response=await fetch(endpoint()+'/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:'gpt-oss:20b',stream:false,think:truncated?'low':'medium',format:schema,options:{temperature:repair?Math.min(.25,prefs.temperature):prefs.temperature,num_predict:truncated?4096:1200,num_ctx:8192},messages:prompt,keep_alive:'5m'}),signal});if(!response.ok)throw Error('Model HTTP '+response.status);const data=await response.json(),raw=data.message?.content||'';try{if(data.done_reason==='length'||!raw.trim())throw Object.assign(Error('GPT-OSS exhausted its reply budget before completing JSON.'),{truncated:true});return {raw,prompt,modelVersion:r.modelVersion,output:mechanicalGuard(validateOutput(JSON.parse(raw)),context)};}catch(error){error.truncated=error.truncated||/Unexpected end of JSON|Unterminated string/i.test(error.message);error.raw=raw;error.prompt=prompt;throw error;}
}
async function runJob(db,job,r){
  const p=preferences(db,job.user_id),request=JSON.parse(job.request_json),event=request.event;let ctx;
  db.prepare("UPDATE ai_jobs SET status='RUNNING',attempts=attempts+1,updated_at=? WHERE id=?").run(Date.now(),job.id);
  try{ctx=job.kind==='event'?botContext(db,job.user_id,job.bot_id,event):request.context;if(job.kind==='event')ctx.recentMessages=db.prepare('SELECT direction,body,subject,type FROM messages WHERE user_id=? AND bot_id=? ORDER BY created_at DESC,id DESC LIMIT 8').all(job.user_id,job.bot_id).reverse();}
  catch(error){db.prepare("UPDATE ai_jobs SET status='FAILED',error=?,updated_at=? WHERE id=?").run(('Dialogue facts unavailable: '+error.message).slice(0,300),Date.now(),job.id);r.status='MODEL_ERROR';r.error='The contact information could not be read. No message was published.';return;}
  let generated,raw='',prompt=[],error;
  for(let attempt=0;attempt<2;attempt++){try{const candidate=await generate(ctx,event,p,r,error?{raw,error:error.message,truncated:error.truncated}:null);raw=candidate.raw;prompt=candidate.prompt;conversationQualityGuard(candidate.output,ctx,event);if(job.kind==='event')repetitionGuard(candidate.output,ctx);generated=candidate;break;}catch(e){error=e;raw=e.raw||raw;prompt=e.prompt||prompt;if(r.closed)return;if(transientProviderError(e)){r.status='OLLAMA_OFFLINE';r.error=e.message;break;}}}
  if(r.closed)return;
  if(!generated){const transport=r.status==='OLLAMA_OFFLINE';db.prepare('UPDATE ai_jobs SET status=?,error=?,next_attempt_at=?,updated_at=? WHERE id=? AND status=\'RUNNING\'').run(transport?'QUEUED':'FAILED',String(error?.message||'Invalid model response').slice(0,300),Date.now()+Math.min(300000,30000*2**Math.min(job.attempts,4)),Date.now(),job.id);if(!transport){r.status='MODEL_ERROR';r.error='The model response failed validation. No message was published.';}return;}
  const still=db.prepare('SELECT status FROM ai_jobs WHERE id=?').get(job.id);if(still?.status!=='RUNNING')return;const latestPreferences=preferences(db,job.user_id);if(job.kind==='event'&&(!latestPreferences.botMessages||(/^PLAYER/.test(event.type)?!latestPreferences.playerReplies:!latestPreferences.botInitiated))){db.prepare("UPDATE ai_jobs SET status='QUEUED',updated_at=? WHERE id=?").run(Date.now(),job.id);return;}
  const genId=uuid(),now=Date.now(),out=generated.output,gameVersion=JSON.parse(fs.readFileSync(path.join(__dirname,'../version.json'))).version;db.exec('BEGIN IMMEDIATE');
  try{db.prepare('INSERT INTO ai_generations(id,user_id,job_id,bot_id,bot_name,context_json,prompt_json,raw_response,validated_json,model,model_version,game_version,balance_patch_id,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(genId,job.user_id,job.id,job.bot_id,ctx.name,JSON.stringify(ctx),JSON.stringify(generated.prompt),generated.raw,JSON.stringify(out),'gpt-oss:20b',generated.modelVersion,gameVersion,ctx.authoritativeGameFacts.currentPatchId,now);
    if(job.kind==='event'){db.prepare('INSERT OR IGNORE INTO messages(id,user_id,bot_id,direction,type,event_id,body,subject,mood,category,wants_reply,certainty,generation_id,created_at,source) VALUES(?,?,?,\'bot\',?,?,?,?,?,?,?,?,?,?,?)').run(uuid(),job.user_id,job.bot_id,event.type,job.event_id,out.body,out.subject,out.mood,out.category,Number(out.wantsReply),out.certainty,genId,now,'ollama:gpt-oss:20b');db.prepare('UPDATE structured_events SET messaged_at=? WHERE id=? AND user_id=?').run(now,job.event_id,job.user_id);remember(db,job.user_id,job.bot_id,{id:job.event_id,type:event.type,at:now,...(/^PLAYER/.test(event.type)?{speaker:'player',quote:cleanText(event.playerReply||'').slice(0,500),notVerifiedGameFact:true}:{fact:cleanText(JSON.stringify(event)).slice(0,500)})});const s=db.prepare('SELECT opinions_json FROM bot_social_profiles WHERE user_id=? AND bot_id=?').get(job.user_id,job.bot_id);const opinions=JSON.parse(s.opinions_json);opinions.push({at:now,generationId:genId,opinion:out.body,notVerifiedGameFact:true});db.prepare('UPDATE bot_social_profiles SET opinions_json=? WHERE user_id=? AND bot_id=?').run(JSON.stringify(opinions.slice(-6)),job.user_id,job.bot_id);updateSummary(db,job.user_id,job.bot_id);}
    db.prepare("UPDATE ai_jobs SET status='COMPLETED',result_json=?,completed_at=?,updated_at=?,error=NULL WHERE id=?").run(JSON.stringify({generationId:genId}),now,now,job.id);db.exec('COMMIT');r.status='CONNECTED';r.error='';
  }catch(e){db.exec('ROLLBACK');throw e;}
}
function kick(db){if(!db.isOpen){dispose(db);return;}const r=runtime(db);if(r.closed||r.busy)return;queueMicrotask(async()=>{if(r.closed||r.busy||globalBusy||!db.isOpen)return;r.busy=true;try{await probe(db);if(r.closed||r.status!=='CONNECTED'||globalBusy||!db.isOpen)return;for(const {user_id} of db.prepare('SELECT user_id FROM worlds').all())collectPending(db,user_id);const jobs=db.prepare("SELECT * FROM ai_jobs WHERE status='QUEUED' AND next_attempt_at<=? ORDER BY priority,created_at LIMIT 100").all(Date.now());const job=jobs.find(j=>{const p=preferences(db,j.user_id);return j.kind!=='event'||p.botMessages&&(/^PLAYER/.test(JSON.parse(j.request_json).event.type)?p.playerReplies:p.botInitiated);});if(job){globalBusy=true;try{await runJob(db,job,r);}finally{globalBusy=false;}}}catch(e){if(!r.closed&&db.isOpen){r.error=e.message;console.error('Local AI queue:',e.message);}}finally{r.busy=false;}});}
async function replyToBot(db,userId,id,text){if(typeof text!=='string'||!text.trim()||text.length>500)throw fail(400,'Reply must be 1–500 characters');const p=preferences(db,userId);if(!p.botMessages||!p.playerReplies)throw fail(409,'Player replies are switched off in Messaging settings');const existing=db.prepare("SELECT j.id,j.status,m.id AS messageId FROM ai_jobs j JOIN messages m ON m.user_id=j.user_id AND m.event_id=j.event_id AND m.direction='player' WHERE j.user_id=? AND j.bot_id=? AND j.kind='event' AND j.status IN ('QUEUED','RUNNING','FAILED') AND m.body=? ORDER BY j.created_at DESC LIMIT 1").get(userId,id,text);if(existing){if(existing.status==='FAILED')db.prepare("UPDATE ai_jobs SET status='QUEUED',error=NULL,next_attempt_at=0,updated_at=? WHERE id=?").run(Date.now(),existing.id);kick(db);return {messageId:existing.messageId,jobId:existing.id,pending:true,generated:false,reused:true};}const ctx=botContext(db,userId,id),messageId=uuid(),eventId=userId+':reply:'+messageId,now=Date.now(),event={id:eventId,type:'PLAYER_MESSAGE',playerReply:text,occurredAt:now};db.prepare('INSERT INTO messages(id,user_id,bot_id,direction,type,event_id,body,created_at,source) VALUES(?,?,?,\'player\',\'PLAYER_MESSAGE\',?,?,?,\'player\')').run(messageId,userId,id,eventId,text,now);db.prepare('INSERT INTO structured_events(id,user_id,bot_id,type,payload_json,created_at) VALUES(?,?,?,?,?,?)').run(eventId,userId,id,event.type,JSON.stringify(event),now);remember(db,userId,id,{id:messageId,type:'player_conversation',at:now,quote:text});db.prepare('UPDATE bot_social_profiles SET player_respect=MIN(100,player_respect+0.1),player_trust=MIN(100,player_trust+0.1) WHERE user_id=? AND bot_id=?').run(userId,id);updateSummary(db,userId,id);const jobId=enqueue(db,userId,id,event);return {messageId,jobId,pending:true,generated:false};}
function developer(db,userId){if(!preferences(db,userId).developerMode)throw fail(403,'Enable Developer Mode in AI settings');}
function applyDeveloperScenario(ctx,mock){
  const w=ctx.authoritativeGameFacts.weapons.find(w=>weaponMention(mock.weapon||'',w.name));if(!w)return;
  if(mock.globalCurrentPatch&&typeof mock.globalCurrentPatch==='object'){w.currentPatchGlobal={...mock.globalCurrentPatch};w.computedTelemetry.global=measuredKd(mock.globalCurrentPatch);}
  if(mock.personalCurrentPatch&&typeof mock.personalCurrentPatch==='object'){w.currentPatchPersonal={...mock.personalCurrentPatch,k:mock.personalCurrentPatch.kills,d:mock.personalCurrentPatch.deaths};w.computedTelemetry.personal=measuredKd(mock.personalCurrentPatch);}
  if(mock.globalCurrentPatch||mock.personalCurrentPatch||Number.isFinite(mock.completedGames)){
    w.sampleMatches=mock.globalCurrentPatch?.games??mock.completedGames??null;w.categoryRank=Number.isFinite(mock.globalRank)?mock.globalRank:null;w.gunScore=Number.isFinite(mock.globalGunScore)?mock.globalGunScore:null;w.confidence=null;w.rankMethod='Developer scenario: ranking, Gun Score and confidence are unknown unless supplied. Interpret mock K/D and sample counts only.';
    if(Number.isFinite(mock.reportedKd))w.computedTelemetry.global.kd=mock.reportedKd;
  }
  if(Number.isFinite(mock.familiarity))w.familiarity=Math.max(0,Math.min(100,mock.familiarity));
  ctx.authoritativeGameFacts.developerScenarioNotice='This generation is a developer test. Supplied weapon sample fields above are mocked and replace the real sample for this scenario only. Missing mock score, ranking, wins or losses are unknown. The real stored game is unchanged.';
}
function lab(db,userId,body,test=false){if(!test)developer(db,userId);const id=body.botId||db.prepare('SELECT bot_id FROM bots WHERE user_id=? ORDER BY power DESC LIMIT 1').get(userId)?.bot_id;if(!id)throw fail(409,'Open your game world first');const type=test?'MODEL_TEST':String(body.eventType);if(!test&&!EVENT_TYPES.includes(type))throw fail(400,'Unsupported lab event');const mock=body.mockContext||{};if(typeof mock!=='object'||Array.isArray(mock)||JSON.stringify(mock).length>12000)throw fail(400,'Invalid mock context');const event={type,reason:test?'Local model connection test':'Developer personality scenario',mockContext:mock,scenarioIsMock:true};const ctx=botContext(db,userId,id,event);Object.assign(event,dialogueIntent(ctx,event));ctx.developerScenario=mock;applyDeveloperScenario(ctx,mock);const jobId=uuid();db.prepare('INSERT INTO ai_jobs(id,user_id,bot_id,kind,priority,status,request_json,created_at,updated_at) VALUES(?,?,?, ?,0,\'QUEUED\',?,?,?)').run(jobId,userId,id,test?'test':'lab',JSON.stringify({event,context:ctx}),Date.now(),Date.now());kick(db);return {jobId};}
function jobResult(db,userId,id){const job=db.prepare('SELECT id,kind,status,error,created_at AS createdAt,completed_at AS completedAt FROM ai_jobs WHERE id=? AND user_id=?').get(id,userId);if(!job)throw fail(404,'Job not found');const g=db.prepare('SELECT id,bot_name AS botName,validated_json FROM ai_generations WHERE job_id=? AND user_id=? ORDER BY created_at DESC LIMIT 1').get(id,userId);return {job,generation:g?{id:g.id,botName:g.botName,validatedMessage:JSON.parse(g.validated_json)}:null};}
function feedback(db,userId,body){developer(db,userId);if(!['GOOD','BAD','EDIT'].includes(body.rating))throw fail(400,'Invalid training rating');const g=db.prepare('SELECT id FROM ai_generations WHERE id=? AND user_id=?').get(body.generationId,userId);if(!g)throw fail(404,'Generation not found');const corrected=body.rating==='EDIT'?validateOutput(body.correctedOutput):null;db.prepare('INSERT INTO ai_training_feedback(generation_id,user_id,rating,corrected_output_json,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(generation_id) DO UPDATE SET rating=excluded.rating,corrected_output_json=excluded.corrected_output_json,updated_at=excluded.updated_at').run(g.id,userId,body.rating,corrected?JSON.stringify(corrected):null,Date.now());return {ok:true};}
function exportTraining(db,userId){developer(db,userId);return db.prepare('SELECT g.*,f.rating,f.corrected_output_json,f.updated_at AS rated_at FROM ai_generations g JOIN ai_training_feedback f ON f.generation_id=g.id AND f.user_id=g.user_id WHERE g.user_id=? ORDER BY g.created_at').all(userId).map(g=>{const ctx=JSON.parse(g.context_json),prompt=JSON.parse(g.prompt_json),preferred=g.rating==='EDIT'?JSON.parse(g.corrected_output_json):JSON.parse(g.validated_json);return JSON.stringify({timestamp:g.created_at,botId:g.bot_id,botName:g.bot_name,personality:ctx.socialProfile,socialProfile:ctx.socialProfile.social,playstyle:ctx.playstyle,event:JSON.parse(db.prepare('SELECT request_json FROM ai_jobs WHERE id=?').get(g.job_id).request_json).event,relevantGameContext:ctx.authoritativeGameFacts,conversationSummary:ctx.conversationSummary,importantMemories:ctx.importantMemories,recentMessages:ctx.recentMessages,prompt,rawModelResponse:g.raw_response,validatedMessage:JSON.parse(g.validated_json),rating:g.rating,...(g.rating==='EDIT'?{correctedOutput:preferred}:{}),model:g.model,modelVersion:g.model_version,gameVersion:g.game_version,balancePatchId:g.balance_patch_id,...(g.rating==='BAD'?{rejected:JSON.parse(g.validated_json)}:{messages:[...prompt,{role:'assistant',content:JSON.stringify(preferred)}]})});}).join('\n')+'\n';}
function messageData(db,userId){initializeSocial(db);const world=JSON.parse(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(userId)?.save_json||'null'),rank=ranks(world);return {messages:messageRows(db,userId,500),preferences:preferences(db,userId),unread:db.prepare("SELECT count(*) AS n FROM messages WHERE user_id=? AND direction='bot' AND read_at IS NULL").get(userId).n,bots:db.prepare('SELECT b.bot_id AS id,b.name,b.power,b.form,s.personality_json FROM bots b LEFT JOIN bot_social_profiles s ON s.user_id=b.user_id AND s.bot_id=b.bot_id WHERE b.user_id=? ORDER BY b.power_rank').all(userId).map(b=>({id:b.id,name:b.name,power:b.power,form:b.form,seasonRank:rank[b.name]||null,playstyle:b.personality_json?JSON.parse(b.personality_json).playstyle:b.playstyle}))};}
module.exports={runtime,dispose,status,probe,kick,preferences,setPreferences,botContext,messageRows,messageData,processEvents,replyToBot,lab,jobResult,feedback,exportTraining,validateOutput,mechanicalGuard,mapGeometryGuard,publicFactGuard,verifiedTournamentEvent,repetitionGuard,conversationBrief,conversationQualityGuard,remember,updateSummary,cancelDeleted,forgetDeleted,cleanText,llmConfigured:()=>true,ranks,metaRank};
