'use strict';
const {botId}=require('./db.cjs');
const {ranks,metaRank,remember}=require('./local-ai.cjs');
const {personalityFor,dialogueIntent}=require('./social-personalities.cjs');
const XP=require('../progression.js');
// A patch is one conversational topic, not fifty copied patch reports. Prefer
// actual familiarity/favorites, with stable tie-breaking across repeated syncs.
function selectPatchContacts(world,changedWeapons,patchId){
  const changed=new Set(changedWeapons),hash=name=>require('node:crypto').createHash('sha256').update(patchId+'|'+name).digest().readUInt32LE(0);
  return (world.activeBotNames||[]).map(name=>{const bot=world.bots[name],favorite=bot.profile.personality?.favoriteWeapon;return {name,score:(changed.has(favorite)?100:0)+Math.max(0,...[...changed].map(w=>bot.familiarity?.[w]||0))};}).filter(row=>row.score>0).sort((a,b)=>b.score-a.score||hash(a.name)-hash(b.name)).slice(0,2).map(row=>row.name);
}
function recordSocialEvents(db,userId,oldWorld,world,now){
  const add=(name,type,key,payload)=>{const b=world.bots[name];if(!b)return;const id=botId(name,b),eventId=`${userId}:social:${type}:${key}:${id}`;db.prepare('INSERT OR IGNORE INTO structured_events(id,user_id,bot_id,type,payload_json,created_at) VALUES(?,?,?,?,?,?)').run(eventId,userId,id,type,JSON.stringify(payload),now);remember(db,userId,id,{id:eventId,type,at:now,fact:JSON.stringify(payload).slice(0,500)});};
  if(!oldWorld){for(const name of ['Ace','Vex','Sage','Jinx'])add(name,'MAP_FEEDBACK','brightfield-1.5.2',{map:'Brightfield Blocks',reason:'This bot is participating in the existing Brightfield Blocks league. The current installed map has pitched house roofs, cutaway interiors, sidewalks, crosswalks and neighborhood props.',noMatchResultImplied:true});return;}
  const view=w=>({...w,patchState:{...w.patchState,...w.patchState.aiSamples?.[w.aiRevision]}});oldWorld=view(oldWorld);world=view(world);
  const before=ranks(oldWorld),after=ranks(world),season=world.seasons.current,previousSeason=oldWorld.seasons.current;
  const oldPrimary=metaRank(oldWorld.patchState,'primary').slice(0,3),newPrimary=metaRank(world.patchState,'primary').slice(0,3),oldSide=metaRank(oldWorld.patchState,'sidearm').slice(0,3),newSide=metaRank(world.patchState,'sidearm').slice(0,3);
  const patchChanges=Object.entries(world.patchState.weaponStats).flatMap(([weapon,stats])=>{const prior=oldWorld.patchState.weaponStats[weapon];return Object.entries(stats).filter(([key,value])=>prior?.[key]!==value).map(([field,after])=>({weapon,field,before:prior?.[field]??null,after}));}),patchContacts=new Set(selectPatchContacts(world,patchChanges.map(c=>c.weapon),world.patchState.id));
  for(const name of world.activeBotNames){const old=oldWorld.bots[name],next=world.bots[name],id=botId(name,next);if(!old)continue;
    for(const threshold of [500,1000,2500])if(old.career.kills<threshold&&next.career.kills>=threshold)add(name,'CAREER_'+threshold+'_KILLS',threshold,{threshold,actualCareerKills:next.career.kills});
    const oldBest=Math.max(0,...old.recentMatches.map(r=>r.kills)),fresh=next.recentMatches.filter(r=>!old.recentMatches.some(o=>o.at===r.at&&o.kills===r.kills&&o.deaths===r.deaths));for(const match of fresh)if(match.kills>oldBest&&old.career.games>0)add(name,'CAREER_BEST_GAME',match.at,{previousObservedBest:oldBest,match,observationWindow:'retained recent completed games'});
    for(const [limit,type,reverse] of [[6,'HOT_STREAK',false],[-6,'SLUMP',true]])if(reverse?old.recentForm>limit&&next.recentForm<=limit:old.recentForm<limit&&next.recentForm>=limit)add(name,type,`${season.number}:${next.career.games}`,{form:next.recentForm,recentCompletedMatches:next.recentMatches.slice(-4)});
    if(fresh.length&&previousSeason.number===season.number&&before[name]&&after[name]&&before[name]!==after[name]&&(Math.abs(before[name]-after[name])>=3||Math.min(before[name],after[name])===1)){add(name,after[name]<before[name]?'SEASON_RANK_UP':'SEASON_RANK_DOWN',`${season.number}:${next.career.games}`,{season:season.number,previousRank:before[name],rank:after[name],record:season.stats[name],scope:'season, qualified bots, K/D descending'});if(after[name]===1)add(name,'SEASON_LEAD',`${season.number}:${next.career.games}`,{season:season.number,rank:1,record:season.stats[name]});if(before[name]===1)add(name,'SEASON_LOST_LEAD',`${season.number}:${next.career.games}`,{season:season.number,rank:after[name]});}
    const social=personalityFor(name)?.social||{},cadence=social.socialness>=.75?3:social.socialness>=.35?6:12;
    for(const [index,match] of fresh.entries()){
      const games=next.career.games-fresh.length+index+1;
      if(games>0&&games%cadence===Number(id.slice(-4))%cadence){const event={id:`${id}:${match.social?.matchId||match.at}`,type:'MATCH_CONVERSATION',match};add(name,event.type,match.social?.matchId||match.at,{match,observedCareerGames:games,...dialogueIntent({name,socialProfile:personalityFor(name)},event)});}
    }
    const oldFavorite=old.profile.personality?.favoriteWeapon,favorite=next.profile.personality?.favoriteWeapon;if(oldFavorite!==favorite)add(name,'FAVORITE_WEAPON_CHANGED',`${world.patchState.id}:${favorite}`,{previous:oldFavorite,weapon:favorite});
    if(world.patchState.id!==oldWorld.patchState.id&&patchContacts.has(name)&&patchChanges.length){const relevant=patchChanges.filter(c=>c.weapon===favorite||(next.familiarity?.[c.weapon]||0)>0),changed=[...new Set(relevant.map(c=>c.weapon))],weapon=changed.includes(favorite)?favorite:changed[0];add(name,oldWorld.patchState.weaponStats[weapon]?'BALANCE_FEEDBACK':'NEW_WEAPON',world.patchState.id,{weapon,changes:relevant,currentPatch:world.patchState.id,previousPatch:oldWorld.patchState.id,reason:'Changed a weapon this bot prefers or has actually used'});}
    if(world.patchState.id===oldWorld.patchState.id&&world.aiRevision===oldWorld.aiRevision){const [oldTop,newTop]=world.patchState.weaponStats[favorite]?.type==='sidearm'?[oldSide,newSide]:[oldPrimary,newPrimary];if(fresh.length&&oldTop.length===3&&newTop.length===3&&JSON.stringify(oldTop)!==JSON.stringify(newTop)){if(!oldTop.includes(favorite)&&newTop.includes(favorite))add(name,'WEAPON_ENTERED_TOP_3',`${world.patchState.id}:${world.patchState.completedMatches}`,{weapon:favorite,top3:newTop,rankMethod:'current Weapon Meta Gun Score within category'});if(oldTop.includes(favorite)&&!newTop.includes(favorite))add(name,'WEAPON_LEFT_TOP_3',`${world.patchState.id}:${world.patchState.completedMatches}`,{weapon:favorite,top3:newTop,rankMethod:'current Weapon Meta Gun Score within category'});}
      for(const [weapon,p] of Object.entries(world.patchState.perBot?.[name]||{})){const o=oldWorld.patchState.perBot?.[name]?.[weapon];if(!o||p.k+p.d<30||o.k+o.d<20||p.k===o.k&&p.d===o.d)continue;const kd=p.k/(p.d||1),priorKd=o.k/(o.d||1);if(priorKd<1.5&&kd>=1.5)add(name,'PERSONAL_WEAPON_BREAKOUT',`${world.patchState.id}:${weapon}:${Math.floor(p.k/10)}`,{weapon,priorKd,kd,currentPatch:world.patchState.id,sample:p});if(priorKd>.6&&kd<=.6)add(name,'PERSONAL_WEAPON_COLLAPSE',`${world.patchState.id}:${weapon}:${Math.floor(p.d/10)}`,{weapon,priorKd,kd,currentPatch:world.patchState.id,sample:p});}
      // Routine standings refreshes and sample counters do not initiate chat.
    }
    for(const [matchId,receipt] of Object.entries(world.ranked?.participants?.[id]?.awards||{})){
      if(oldWorld.ranked?.participants?.[id]?.awards?.[matchId]||receipt.participantId!==id||!world.rankedResults?.[matchId]?.rows?.some(r=>r.participantId===id&&r.type==='bot'))continue;
      const from=XP.rankView(receipt.beforeUnits),to=XP.rankView(receipt.afterUnits),type=from.rankIndex===to.rankIndex?'RANKED_RESULT':to.rankIndex>from.rankIndex?'RANKED_RANK_UP':'RANKED_RANK_DOWN';
      // Rank changes and streak milestones are meaningful. Ordinary results
      // retain the existing personality cadence instead of messaging each game.
      if(type==='RANKED_RESULT'&&![3,5].includes(receipt.winStreak)&&next.career.games%cadence!==Number(id.slice(-4))%cadence)continue;
      add(name,type,matchId,{matchId,participantId:id,won:receipt.won,previousRank:from.rankName,rank:to.rankName,elo:to.rating,calculatedElo:receipt.calculatedUnits/100,appliedElo:receipt.appliedUnits/100,rankedWinStreak:receipt.winStreak,mode:'ranked-tdm',currentPatch:world.patchState.id,rulesVersion:receipt.rulesVersion,at:receipt.at});
    }
    for(const match of fresh){if(!match.social)continue;for(const other of match.social.teammates){const otherBot=world.bots[other],peer=otherBot?.recentMatches.find(m=>m.social?.matchId===match.social.matchId);if(!peer||peer.social.team!==match.social.team||peer.won!==match.won)continue;db.prepare('INSERT INTO bot_relationships(user_id,bot_id,other_bot_id,friendship,updated_at) VALUES(?,?,?, ?,?) ON CONFLICT(user_id,bot_id,other_bot_id) DO UPDATE SET friendship=MIN(100,bot_relationships.friendship+excluded.friendship),updated_at=excluded.updated_at').run(userId,id,botId(other,otherBot),match.won?.2:.05,now);}}
    // Real, qualified season competition slowly creates rivalry. Model output
    // never supplies or changes these scores. Distinct rank crossings are facts.
    if(before[name]&&after[name]&&fresh.length){for(const other of world.activeBotNames.filter(n=>n!==name&&after[n]&&Math.abs(after[n]-after[name])<=1).slice(0,2)){const otherId=botId(other,world.bots[other]);db.prepare('INSERT INTO bot_relationships(user_id,bot_id,other_bot_id,rivalry,updated_at) VALUES(?,?,?,0.2,?) ON CONFLICT(user_id,bot_id,other_bot_id) DO UPDATE SET rivalry=MIN(100,bot_relationships.rivalry+0.2),updated_at=excluded.updated_at').run(userId,id,otherId,now);if(before[other]&&before[name]>before[other]&&after[name]<after[other])add(name,'BOT_BEAT_RIVAL',`${season.number}:${next.career.games}:${otherId}`,{reason:'Passed established nearby season competitor in standings',otherBot:other,previousRank:before[name],currentRank:after[name]});if(before[other]&&before[name]<before[other]&&after[name]>after[other])add(name,'RIVAL_BEAT_BOT',`${season.number}:${next.career.games}:${otherId}`,{reason:'Established nearby season competitor passed this bot in standings',otherBot:other,previousRank:before[name],currentRank:after[name]});}}
    const history=new Set(oldWorld.seasons.history.map(s=>s.number));for(const s of world.seasons.history)if(!history.has(s.number)&&s.winner)add(name,s.winner.name===name?'SEASON_WIN':'SEASON_LOSS',s.number,{season:s.number,winner:s.winner,record:s.stats[name]});
  }
}
module.exports={recordSocialEvents,selectPatchContacts};
