'use strict';
const {botId}=require('./db.cjs');
const {ranks,metaRank,remember}=require('./local-ai.cjs');
const {personalityFor,dialogueIntent}=require('./social-personalities.cjs');
function recordSocialEvents(db,userId,oldWorld,world,now){
  const add=(name,type,key,payload)=>{const b=world.bots[name];if(!b)return;const id=botId(name,b),eventId=`${userId}:social:${type}:${key}:${id}`;db.prepare('INSERT OR IGNORE INTO structured_events(id,user_id,bot_id,type,payload_json,created_at) VALUES(?,?,?,?,?,?)').run(eventId,userId,id,type,JSON.stringify(payload),now);remember(db,userId,id,{id:eventId,type,at:now,fact:JSON.stringify(payload).slice(0,500)});};
  if(!oldWorld){for(const name of ['Ace','Vex','Sage','Jinx'])add(name,'MAP_FEEDBACK','brightfield-1.5.2',{map:'Brightfield Blocks',reason:'This bot is participating in the existing Brightfield Blocks league. The current installed map has pitched house roofs, cutaway interiors, sidewalks, crosswalks and neighborhood props.',noMatchResultImplied:true});return;}
  const view=w=>({...w,patchState:{...w.patchState,...w.patchState.aiSamples?.[w.aiRevision]}});oldWorld=view(oldWorld);world=view(world);
  const before=ranks(oldWorld),after=ranks(world),season=world.seasons.current,previousSeason=oldWorld.seasons.current;
  const oldPrimary=metaRank(oldWorld.patchState,'primary').slice(0,3),newPrimary=metaRank(world.patchState,'primary').slice(0,3),oldSide=metaRank(oldWorld.patchState,'sidearm').slice(0,3),newSide=metaRank(world.patchState,'sidearm').slice(0,3);
  for(const name of world.activeBotNames){const old=oldWorld.bots[name],next=world.bots[name],id=botId(name,next);if(!old)continue;
    for(const threshold of [500,1000,2500])if(old.career.kills<threshold&&next.career.kills>=threshold)add(name,'CAREER_'+threshold+'_KILLS',threshold,{threshold,actualCareerKills:next.career.kills});
    const oldBest=Math.max(0,...old.recentMatches.map(r=>r.kills)),fresh=next.recentMatches.filter(r=>!old.recentMatches.some(o=>o.at===r.at&&o.kills===r.kills&&o.deaths===r.deaths));for(const match of fresh)if(match.kills>oldBest&&old.career.games>0)add(name,'CAREER_BEST_GAME',match.at,{previousObservedBest:oldBest,match,observationWindow:'retained recent completed games'});
    for(const [limit,type,reverse] of [[6,'HOT_STREAK',false],[-6,'SLUMP',true]])if(reverse?old.recentForm>limit&&next.recentForm<=limit:old.recentForm<limit&&next.recentForm>=limit)add(name,type,`${season.number}:${next.career.games}`,{form:next.recentForm,recentCompletedMatches:next.recentMatches.slice(-4)});
    if(previousSeason.number===season.number&&before[name]&&after[name]&&before[name]!==after[name]){add(name,after[name]<before[name]?'SEASON_RANK_UP':'SEASON_RANK_DOWN',`${season.number}:${next.career.games}`,{season:season.number,previousRank:before[name],rank:after[name],record:season.stats[name]});if(after[name]===1)add(name,'SEASON_LEAD',`${season.number}:${next.career.games}`,{season:season.number,rank:1,record:season.stats[name]});if(before[name]===1)add(name,'SEASON_LOST_LEAD',`${season.number}:${next.career.games}`,{season:season.number,rank:after[name]});}
    const social=personalityFor(name)?.social||{},cadence=social.socialness>=.75?3:social.socialness>=.35?6:12;
    for(const [index,match] of fresh.entries()){
      const games=next.career.games-fresh.length+index+1;
      if(games>0&&games%cadence===Number(id.slice(-4))%cadence){const event={id:`${id}:${match.social?.matchId||match.at}`,type:'MATCH_CONVERSATION',match};add(name,event.type,match.social?.matchId||match.at,{match,observedCareerGames:games,...dialogueIntent({name,socialProfile:personalityFor(name)},event)});}
    }
    const oldFavorite=old.profile.personality?.favoriteWeapon,favorite=next.profile.personality?.favoriteWeapon;if(oldFavorite!==favorite)add(name,'FAVORITE_WEAPON_CHANGED',`${world.patchState.id}:${favorite}`,{previous:oldFavorite,weapon:favorite});
    if(world.patchState.id!==oldWorld.patchState.id){const changes=[];for(const [weapon,stats] of Object.entries(world.patchState.weaponStats)){const prior=oldWorld.patchState.weaponStats[weapon];if(!prior)add(name,'NEW_WEAPON',world.patchState.id+weapon,{weapon,stats});else{const delta=Object.fromEntries(Object.keys(stats).filter(k=>prior[k]!==stats[k]).map(k=>[k,{from:prior[k],to:stats[k]}]));if(Object.keys(delta).length){changes.push({weapon,changes:delta});const buff=stats.damage>prior.damage||stats.head>prior.head||stats.hitSpeed<prior.hitSpeed,nerf=stats.damage<prior.damage||stats.head<prior.head||stats.hitSpeed>prior.hitSpeed;if(weapon===favorite||['Ace','Quill','Sage'].includes(name))add(name,buff&&!nerf?'BUFF_REACTION':nerf&&!buff?'NERF_REACTION':'BALANCE_FEEDBACK',world.patchState.id+weapon,{weapon,changes:delta,currentPatch:world.patchState.id,previousPatch:oldWorld.patchState.id});}}}if(changes.length)add(name,'BALANCE_FEEDBACK',world.patchState.id,{changes});}
    if(world.patchState.id===oldWorld.patchState.id&&world.aiRevision===oldWorld.aiRevision){const [oldTop,newTop]=world.patchState.weaponStats[favorite]?.type==='sidearm'?[oldSide,newSide]:[oldPrimary,newPrimary];if(oldTop.length===3&&newTop.length===3&&JSON.stringify(oldTop)!==JSON.stringify(newTop)){add(name,'META_SHIFT',`${world.patchState.id}:${world.patchState.completedMatches}`,{previousTop3:oldTop,currentTop3:newTop,rankMethod:'current Weapon Meta Gun Score within category',currentPatch:world.patchState.id});if(!oldTop.includes(favorite)&&newTop.includes(favorite))add(name,'WEAPON_ENTERED_TOP_3',`${world.patchState.id}:${world.patchState.completedMatches}`,{weapon:favorite,top3:newTop,rankMethod:'current Weapon Meta Gun Score within category'});if(oldTop.includes(favorite)&&!newTop.includes(favorite))add(name,'WEAPON_LEFT_TOP_3',`${world.patchState.id}:${world.patchState.completedMatches}`,{weapon:favorite,top3:newTop,rankMethod:'current Weapon Meta Gun Score within category'});}
      for(const [weapon,p] of Object.entries(world.patchState.perBot?.[name]||{})){const o=oldWorld.patchState.perBot?.[name]?.[weapon];if(!o||p.k+p.d<30||o.k+o.d<20||p.k===o.k&&p.d===o.d)continue;const kd=p.k/(p.d||1),priorKd=o.k/(o.d||1);if(priorKd<1.5&&kd>=1.5)add(name,'PERSONAL_WEAPON_BREAKOUT',`${world.patchState.id}:${weapon}:${Math.floor(p.k/10)}`,{weapon,priorKd,kd,currentPatch:world.patchState.id,sample:p});if(priorKd>.6&&kd<=.6)add(name,'PERSONAL_WEAPON_COLLAPSE',`${world.patchState.id}:${weapon}:${Math.floor(p.d/10)}`,{weapon,priorKd,kd,currentPatch:world.patchState.id,sample:p});}
      if(world.patchState.completedMatches>=12&&Math.floor(world.patchState.completedMatches/20)>Math.floor(oldWorld.patchState.completedMatches/20))add(name,'META_OPINION',`${world.patchState.id}:${Math.floor(world.patchState.completedMatches/20)}`,{weapon:favorite,currentPatch:world.patchState.id,completedMatches:world.patchState.completedMatches});
    }
    for(const match of fresh){if(!match.social)continue;for(const other of match.social.teammates){const otherBot=world.bots[other],peer=otherBot?.recentMatches.find(m=>m.social?.matchId===match.social.matchId);if(!peer||peer.social.team!==match.social.team||peer.won!==match.won)continue;db.prepare('INSERT INTO bot_relationships(user_id,bot_id,other_bot_id,friendship,updated_at) VALUES(?,?,?, ?,?) ON CONFLICT(user_id,bot_id,other_bot_id) DO UPDATE SET friendship=MIN(100,bot_relationships.friendship+excluded.friendship),updated_at=excluded.updated_at').run(userId,id,botId(other,otherBot),match.won?.2:.05,now);}}
    // Real, qualified season competition slowly creates rivalry. Model output
    // never supplies or changes these scores. Distinct rank crossings are facts.
    if(before[name]&&after[name]&&fresh.length){for(const other of world.activeBotNames.filter(n=>n!==name&&after[n]&&Math.abs(after[n]-after[name])<=1).slice(0,2)){const otherId=botId(other,world.bots[other]);db.prepare('INSERT INTO bot_relationships(user_id,bot_id,other_bot_id,rivalry,updated_at) VALUES(?,?,?,0.2,?) ON CONFLICT(user_id,bot_id,other_bot_id) DO UPDATE SET rivalry=MIN(100,bot_relationships.rivalry+0.2),updated_at=excluded.updated_at').run(userId,id,otherId,now);if(before[other]&&before[name]>before[other]&&after[name]<after[other])add(name,'BOT_BEAT_RIVAL',`${season.number}:${next.career.games}:${otherId}`,{reason:'Passed established nearby season competitor in standings',otherBot:other,previousRank:before[name],currentRank:after[name]});if(before[other]&&before[name]<before[other]&&after[name]>after[other])add(name,'RIVAL_BEAT_BOT',`${season.number}:${next.career.games}:${otherId}`,{reason:'Established nearby season competitor passed this bot in standings',otherBot:other,previousRank:before[name],currentRank:after[name]});}}
    const history=new Set(oldWorld.seasons.history.map(s=>s.number));for(const s of world.seasons.history)if(!history.has(s.number)&&s.winner)add(name,s.winner.name===name?'SEASON_WIN':'SEASON_LOSS',s.number,{season:s.number,winner:s.winner,record:s.stats[name]});
  }
}
module.exports={recordSocialEvents};
