'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {spawnSync} = require('node:child_process');
const root = path.resolve(__dirname, '..');
const config = JSON.parse(fs.readFileSync(path.join(root, 'src-tauri/tauri.conf.json'), 'utf8'));
assert.equal(config.version, JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version);
assert.equal(config.identifier, 'com.skirmisharena.launcher');
assert.equal(config.bundle.createUpdaterArtifacts, true);
assert.equal(config.plugins.updater.requireSignedVersion, true);
const key = Buffer.from(config.plugins.updater.pubkey, 'base64').toString('utf8');
assert.match(key, /^untrusted comment: /);
assert.equal(config.app.security.csp.includes("'unsafe-eval'"), false);
const capabilities = JSON.parse(fs.readFileSync(path.join(root, 'src-tauri/capabilities/launcher.json'), 'utf8'));
assert.deepEqual(capabilities.windows, ['main']);
assert.equal(capabilities.remote, undefined);
const checkpoint = JSON.parse(fs.readFileSync(path.join(root, 'src-tauri/capabilities/game-checkpoint.json'), 'utf8'));
assert.deepEqual(checkpoint.windows, ['game']);
assert.deepEqual(checkpoint.permissions, ['allow-finish-game-checkpoint', 'allow-game-fullscreen-state', 'allow-set-game-fullscreen', 'allow-check-local-backend', 'allow-offline-local-api', 'allow-quit-game']);
const native = fs.readFileSync(path.join(root, 'src-tauri/src/main.rs'), 'utf8');
assert.match(native, /\.fullscreen\(true\)/);
assert.match(native, /fn game_fullscreen_state[\s\S]*?require_game\(&app, &window\)/);
assert.match(native, /fn set_game_fullscreen[\s\S]*?require_game\(&app, &window\)/);
const requireGame=native.match(/fn require_game\([\s\S]*?\n\}/)?.[0];
assert.ok(requireGame,'One shared native game-window authorization helper');
assert.match(requireGame,/window\.label\(\) != "game" \|\| window\.url\(\)\.map_err\(err\)\?\.origin\(\) != origin\(app\)\?\.origin\(\)/,'Both current game label and exact configured origin are required');
const quit=native.match(/fn quit_game\([\s\S]*?\n\}/)?.[0];
assert.ok(quit,'Native quit command exists');
assert.ok(quit.indexOf('require_game(&app, &window)?')<quit.indexOf('app.exit(0)'),'Exit authorization runs before closing');
assert.match(quit,/busy\.load\(Ordering::SeqCst\)/,'Exit cannot interrupt an installation');
assert.doesNotMatch(quit,/\.kill\(|taskkill|Command::new|backend::prepare_update/,'Quit cannot terminate shared services');
assert.match(fs.readFileSync(path.join(root,'src-tauri/build.rs'),'utf8'),/"quit_game"/,'Native ACL includes the declared command');
const result = spawnSync(process.execPath, ['--check', path.join(root, 'ui/launcher.js')], {stdio: 'inherit'});
assert.equal(result.status, 0);
console.log('PASS launcher config, restricted native capability, signed-version enforcement, UI syntax.');
