'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {spawnSync} = require('node:child_process');
const root = path.resolve(__dirname, '..');
const config = JSON.parse(fs.readFileSync(path.join(root, 'src-tauri/tauri.conf.json'), 'utf8'));
assert.equal(config.version, JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version);
assert.equal(config.identifier, 'com.skirmisharena.launcher');
assert.equal(config.bundle.createUpdaterArtifacts, true);
assert.equal(config.plugins.updater.requireSignedVersion, true);
const key = Buffer.from(config.plugins.updater.pubkey, 'base64').toString('utf8');
assert.match(key, /^untrusted comment: /);
assert.equal(config.app.security.csp.includes("'unsafe-eval'"), false);
const capabilities = JSON.parse(fs.readFileSync(path.join(root, 'src-tauri/capabilities/launcher.json'), 'utf8'));
assert.deepEqual(capabilities.windows, ['main']);
assert.equal(capabilities.remote, undefined);
const checkpoint = JSON.parse(fs.readFileSync(path.join(root, 'src-tauri/capabilities/game-checkpoint.json'), 'utf8'));
assert.deepEqual(checkpoint.windows, ['game']);
assert.deepEqual(checkpoint.permissions, ['allow-finish-game-checkpoint', 'allow-game-fullscreen-state', 'allow-set-game-fullscreen', 'allow-check-local-backend', 'allow-quit-game', 'allow-open-sandbox-checkout']);
const native = fs.readFileSync(path.join(root, 'src-tauri/src/main.rs'), 'utf8');
const backend = fs.readFileSync(path.join(root, 'src-tauri/src/backend.rs'), 'utf8');
const release=path.resolve(root,'..'),stage=fs.readFileSync(path.join(root,'scripts/stage-backend.cjs'),'utf8'),worker=fs.readFileSync(path.join(release,'sw.js'),'utf8');
assert.match(stage,/'mode-entry\.js'/,'Installed shell includes the match-entry controller');
assert.match(worker,/'\.\/mode-entry\.js'/,'Offline essential shell includes the match-entry controller');
assert.match(stage,/'profile-stats\.js'/,'Installed shell includes the shared profile projection');
assert.match(worker,/'\.\/profile-stats\.js'/,'Offline essential shell includes the shared profile projection');
assert.ok(fs.readFileSync(path.join(release,'index.html'),'utf8').includes('src="profile-stats.js"'),'Game page loads the shared profile projection');
assert.match(stage,/'distance-units\.js'/,'Installed shell includes map calibration');
assert.match(worker,/'\.\/distance-units\.js'/,'Offline essential shell includes map calibration');
assert.ok(fs.readFileSync(path.join(release,'index.html'),'utf8').includes('src="distance-units.js"'),'Game page loads map calibration');
assert.ok(fs.readFileSync(path.join(release,'index.html'),'utf8').indexOf('src="mode-entry.js"')>=0,'Game page loads the match-entry controller');
assert.doesNotMatch(native+backend,/offline_local_api|offline_request|offline-bridge\.cjs|local-ai\.cjs/,'Native runtime must not start or expose the retired message worker');
assert.match(backend,/fn shell_fallback\(/,'Authenticated cached worlds retain the independent offline shell');
assert.match(backend,/fn backend_ownership_lock\(/,'Account backend retains its database ownership guard');
assert.match(native, /\.fullscreen\(true\)/);
assert.match(native, /fn game_fullscreen_state[\s\S]*?require_game\(&app, &window\)/);
assert.match(native, /fn set_game_fullscreen[\s\S]*?require_game\(&app, &window\)/);
const requireGame=native.match(/fn require_game\([\s\S]*?\n\}/)?.[0];
assert.ok(requireGame,'One shared native game-window authorization helper');
assert.match(requireGame,/window\.label\(\) != "game" \|\| window\.url\(\)\.map_err\(err\)\?\.origin\(\) != origin\(app\)\?\.origin\(\)/,'Both current game label and exact configured origin are required');
const quit=native.match(/fn quit_game\([\s\S]*?\n\}/)?.[0];
assert.ok(quit,'Native quit command exists');
assert.ok(quit.indexOf('require_game(&app, &window)?')<quit.indexOf('app.exit(0)'),'Exit authorization runs before closing');
assert.match(quit,/busy\.load\(Ordering::SeqCst\)/,'Exit cannot interrupt an installation');
assert.doesNotMatch(quit,/\.kill\(|taskkill|Command::new|backend::prepare_update/,'Quit cannot terminate shared services');
assert.match(fs.readFileSync(path.join(root,'src-tauri/build.rs'),'utf8'),/"quit_game"/,'Native ACL includes the declared command');
const checkout=native.match(/fn open_sandbox_checkout\([\s\S]*?\n\}/)?.[0];
assert.ok(checkout,'Dedicated Sandbox checkout command exists');
assert.ok(checkout.indexOf('require_game(&app, &window)?')<checkout.indexOf('checked_sandbox_checkout(&url)?'),'Exact game origin checked before URL');
assert.match(checkout,/ShellExecuteW/,'Windows opens the validated URL directly');
assert.doesNotMatch(checkout,/Command::new|cmd\.exe|powershell|\.args\(/,'No command interpreter or arbitrary process arguments');
const result = spawnSync(process.execPath, ['--check', path.join(root, 'ui/launcher.js')], {stdio: 'inherit'});
assert.equal(result.status, 0);
assert.equal(spawnSync(process.execPath,['--check',path.join(release,'mode-entry.js')],{stdio:'inherit'}).status,0);
console.log('PASS launcher config, restricted native capability, signed-version enforcement, UI syntax.');
