'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),v8=require('node:v8'),zlib=require('node:zlib');
const {createDatabase}=require('../db.cjs'),{writeWorld}=require('../world.cjs'),{engine}=require('../../dev/simulate.cjs'),Circuit=require('../tournaments.cjs'),Runtime=require('../tournament-runtime.cjs'),Progression=require('../progression.cjs'),{snapshot}=require('../../dev/live-circuit-tournament-check.cjs');
function fixture({human=false,official=false}={}){
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'sar-audit6-runtime-')),file=path.join(directory,'isolated.sqlite'),db=createDatabase(file),owner='runtime-owner',world=engine().context.SAR.getUniverse(),now=world.seasons.current.startAt+3600000;
 db.prepare('INSERT INTO users(id,username,username_key,password_hash,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(owner,owner,owner,'isolated-not-a-password',now,now);writeWorld(db,owner,world,0);
 let t=official?Circuit.scheduleOfficial(db,owner,world.seasons.current,now)[0]:Circuit.createCustom(db,owner,{name:'Aggregate Runtime Fixture',startsAt:now},now);
 // These fixtures exercise pre-schedule persisted series; absolute-clock games
 // have separate lifecycle/runtime fixtures. Keep their historical timing.
 if(official){const metadata=JSON.parse(db.prepare('SELECT metadata_json FROM tournaments WHERE id=?').get(t.id).metadata_json);delete metadata.schedulePolicy;delete metadata.scheduling;db.prepare('UPDATE tournaments SET metadata_json=? WHERE id=?').run(JSON.stringify(metadata),t.id);t=Circuit.getTournament(db,owner,t.id);}
 const at=official?t.startsAt:now;if(human)Circuit.registerTeam(db,owner,t.id,{name:'Player Team',participantIds:[owner,'bot_0001','bot_0002','bot_0003','bot_0004']},at);t=Runtime.fillBots(db,owner,Circuit.getTournament(db,owner,t.id),at);t=Circuit.startTournament(db,owner,t.id,at);
 return {db,directory,file,owner,t,now:at,before:snapshot(db),close(){if(db.isOpen)db.close();assert.ok(path.resolve(directory).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(directory,{recursive:true,force:true});}};
}
function checkpoint(db,tournamentId,gameId){const record=JSON.parse(db.prepare('SELECT metadata_json FROM tournaments WHERE id=?').get(tournamentId).metadata_json).runtimeGames[gameId];return {record,payload:v8.deserialize(zlib.inflateSync(Buffer.from(record.data,'base64')))};}
function resolved(t,s,score){
 const stats=s.teamIds.flatMap((teamId,team)=>t.teams.find(t=>t.id===teamId).participants.map((p,i)=>{const split=(n)=>Math.floor(n/5)+(i<n%5?1:0),kills=split(score[team]),deaths=split(score[1-team]);return {participantId:p.id,kills,deaths,assists:0,damage:kills*250,shots:kills*10,hits:kills*8,headshots:0,timeAlive:120,weaponStats:{'AR-15':{kills,deaths,damage:kills*250,shots:kills*10,hits:kills*8}}};}));
 return {id:s.id+':game'+(s.games.length+1),winnerTeamId:s.teamIds[score[0]>score[1]?0:1],score,duration:120,stats};
}
test('real headless game checkpoint resumes exact positions, projectiles, clocks, RNG and kill accounting after restart',()=>{
 const f=fixture();let resumed;try{Runtime.advance(f.db,{now:f.now,budget:300});const before=Runtime.activeGames(f.db)[0];assert.equal(before.status,'active');assert.equal(before.steps,300);
  const saved=checkpoint(f.db,f.t.id,before.gameId),m=saved.payload.snapshot.state.matches.find(m=>m?.context?.gameId===before.gameId);assert.equal(m.limit,50,'Preserve the actual existing tournament kill target');assert.equal(m.durationMs,300000);assert.ok(saved.payload.snapshot.simulationTime-m.countdownStartedAt>9999&&saved.payload.snapshot.simulationTime-m.countdownStartedAt<10001,'The controlled engine advances ten seconds including preparation');assert.ok(m.startedAt-m.countdownStartedAt>=3000,'Combat elapsed time must exclude the full pre-match countdown');assert.equal(before.elapsedMs,saved.payload.snapshot.simulationTime-m.startedAt);assert.ok(m.participants.every(a=>a.damageLedger instanceof Map&&a.memory instanceof Map));assert.ok(saved.payload.snapshot.state.projectiles.every(p=>m.participants.includes(p.owner)),'Projectile ownership retains actual actor references');assert.deepEqual(snapshot(f.db),f.before);
  const cloneFile=path.join(f.directory,'restarted.sqlite');f.db.prepare('VACUUM INTO ?').run(cloneFile);resumed=createDatabase(cloneFile);Runtime.advance(resumed,{now:f.now+5000,budget:0});const restored=Runtime.activeGames(resumed)[0];assert.deepEqual({...restored,resumed:false},before);assert.equal(restored.resumed,true);
  const restoredPayload=checkpoint(resumed,f.t.id,before.gameId).payload;assert.deepEqual(restoredPayload,saved.payload,'No lost score, timers, target references, damage ledgers or equipped time on rehydration');
  Runtime.advance(f.db,{now:f.now+6000,budget:90});Runtime.advance(resumed,{now:f.now+6000,budget:90});assert.deepEqual(checkpoint(resumed,f.t.id,before.gameId).payload,checkpoint(f.db,f.t.id,before.gameId).payload,'Resumed simulation equals the uninterrupted real engine after another 90 ticks');assert.deepEqual(snapshot(resumed),f.before);assert.deepEqual(snapshot(f.db),f.before);
 }finally{resumed?.close();f.close();}
});
test('first headless tournament countdown persists and resumes without combat or duplicate allocation',()=>{
 const f=fixture();let resumed;try{
  Runtime.advance(f.db,{now:f.now,budget:0});const initial=Runtime.activeGames(f.db)[0];assert.equal(initial.status,'countdown');assert.equal(initial.steps,0);
  const first=checkpoint(f.db,f.t.id,initial.gameId).payload,match=first.snapshot.state.matches.find(m=>m?.context?.gameId===initial.gameId);assert.equal(match.countdownUntil-match.countdownStartedAt,3000);
  const actors=match.participants.map(a=>({id:a.id,x:a.x,y:a.y,hp:a.hp,shots:a.stats.shots,kills:a.stats.kills,damage:a.stats.damage}));
  Runtime.advance(f.db,{now:f.now+1500,budget:45});const half=checkpoint(f.db,f.t.id,initial.gameId).payload,halfMatch=half.snapshot.state.matches.find(m=>m?.context?.gameId===initial.gameId);assert.equal(halfMatch.status,'countdown');assert.deepEqual(halfMatch.participants.map(a=>({id:a.id,x:a.x,y:a.y,hp:a.hp,shots:a.stats.shots,kills:a.stats.kills,damage:a.stats.damage})),actors);assert.equal(half.snapshot.state.projectiles.length,0);assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_matches WHERE tournament_id=?').get(f.t.id).n,0);
  const copy=path.join(f.directory,'countdown-restarted.sqlite');f.db.prepare('VACUUM INTO ?').run(copy);resumed=createDatabase(copy);Runtime.advance(resumed,{now:f.now+10000,budget:0});assert.equal(Runtime.activeGames(resumed).length,1);assert.equal(Runtime.activeGames(resumed)[0].resumed,true);assert.deepEqual(checkpoint(resumed,f.t.id,initial.gameId).payload,half,'Reconnect recovers the actual remaining countdown instead of firing an old entry event');
  Runtime.advance(resumed,{now:f.now+11000,budget:50});const active=Runtime.activeGames(resumed)[0],complete=checkpoint(resumed,f.t.id,initial.gameId).payload,completeMatch=complete.snapshot.state.matches.find(m=>m?.context?.gameId===initial.gameId);assert.equal(active.status,'active');assert.equal(active.gameId,initial.gameId);assert.equal(active.steps,95);assert.ok(completeMatch.startedAt-completeMatch.countdownStartedAt>=3000);assert.equal(Runtime.activeGames(resumed).length,1);assert.deepEqual(snapshot(resumed),f.before);assert.deepEqual(snapshot(f.db),f.before);
 }finally{resumed?.close();f.close();}
});
test('an unacknowledged resolved game survives restart and the finalizer adds its score only once',()=>{
 const f=fixture();let restarted;const realRecord=Circuit.recordGame;try{let blocked;Circuit.recordGame=(...args)=>{blocked=args[4];throw new Error('isolated result-delivery interruption');};assert.throws(()=>Runtime.advance(f.db,{now:f.now,budget:12000}),/result-delivery interruption/);assert.ok(blocked?.stats.some(s=>s.damage>0));assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_matches').get().n,0);const old=checkpoint(f.db,f.t.id,blocked.id);assert.equal(old.payload.snapshot.state.matches.find(m=>m?.context?.gameId===blocked.id).status,'ended');Circuit.recordGame=realRecord;
  const cloneFile=path.join(f.directory,'resolved-restarted.sqlite');f.db.prepare('VACUUM INTO ?').run(cloneFile);restarted=createDatabase(cloneFile);Runtime.advance(restarted,{now:f.now+1000,budget:0});let t=Circuit.getTournament(restarted,f.owner,f.t.id),s=t.series.find(s=>s.id===blocked.id.split(':game')[0]);assert.equal(s.games.length,1);assert.deepEqual(s.games[0].score,blocked.score);assert.deepEqual(s.aggregateKills,blocked.score);assert.equal(s.remainingGames,2);assert.equal(restarted.prepare('SELECT count(*) n FROM tournament_matches WHERE id=?').get(blocked.id).n,1);
  realRecord(restarted,f.owner,t.id,s.id,{...blocked,score:[0,0]},f.now+2000);assert.deepEqual(Circuit.getTournament(restarted,f.owner,t.id).series,t.series,'Mutated late callback cannot replace a finalized game');assert.deepEqual(snapshot(restarted),f.before);assert.equal(JSON.parse(restarted.prepare('SELECT metadata_json FROM tournaments WHERE id=?').get(t.id).metadata_json).runtimeGames,undefined);
 }finally{Circuit.recordGame=realRecord;restarted?.close();f.close();}
});
test('two individual wins still schedule game three and preserve the standard per-game rules',()=>{
 const f=fixture();try{let t=f.t,s=t.series[0];for(let i=0;i<2;i++){const game=resolved(t,s,[45,20]);t=Circuit.recordGame(f.db,f.owner,t.id,s.id,game,f.now+i);s=t.series.find(x=>x.id===s.id);}assert.equal(s.winnerTeamId,null);assert.deepEqual(s.wins,[2,0]);assert.equal(s.remainingGames,1);assert.deepEqual(s.aggregateKills,[90,40]);Runtime.advance(f.db,{now:f.now+2000,budget:0});const active=Runtime.activeGames(f.db).find(g=>g.gameId===s.id+':game3');assert.ok(active,'The third required game must actually be allocated despite two wins');const current=checkpoint(f.db,t.id,active.gameId).payload.snapshot.state.matches.find(m=>m?.context?.gameId===active.gameId);assert.equal(current.limit,50);assert.equal(current.durationMs,300000);assert.deepEqual(snapshot(f.db),f.before);
 }finally{f.close();}
});
test('aggregate tie prevents an extra player game, extra XP and scheduler overtime while resolved game XP remains valid',()=>{
 const f=fixture({human:true,official:true});try{let t=f.t,s=t.series.find(s=>s.teamIds.some(id=>t.teams.find(t=>t.id===id).participants.some(p=>p.id===f.owner))),last;for(const score of [[40,20],[20,30],[10,20]]){last=resolved(t,s,score);t=Circuit.recordGame(f.db,f.owner,t.id,s.id,last,f.now);s=t.series.find(x=>x.id===s.id);}assert.deepEqual(s.aggregateKills,[70,70]);assert.equal(s.status,'awaiting-tie-policy');assert.equal(s.remainingGames,0);assert.throws(()=>Runtime.playContext(f.db,f.owner,t.id),e=>e.status===409&&/tie policy/.test(e.message));Runtime.advance(f.db,{now:f.now,budget:0});assert.ok(Runtime.activeGames(f.db).every(g=>!g.gameId.startsWith(s.id+':')));
  const receipt={kind:'official',tournamentId:t.id,seriesId:s.id,stats:last.stats.find(p=>p.participantId===f.owner),won:last.winnerTeamId===t.teams.find(t=>t.participants.some(p=>p.id===f.owner)).id};const prior={progression:{awards:{}}};assert.throws(()=>Progression.validateTournamentProgression(f.db,f.owner,{progression:{awards:{[s.id+':game4']:receipt}}},prior),/registered game/);assert.doesNotThrow(()=>Progression.validateTournamentProgression(f.db,f.owner,{progression:{awards:{[last.id]:receipt}}},prior));assert.deepEqual(snapshot(f.db),f.before);
 }finally{f.close();}
});
test('final allocates game five after four individual wins and commits one complete championship',()=>{
 const f=fixture();try{let t=f.t;for(const round of ['QF','SF'])for(const original of t.series.filter(s=>s.round===round)){let s=t.series.find(s=>s.id===original.id);for(let i=0;i<3;i++){t=Circuit.recordGame(f.db,f.owner,t.id,s.id,resolved(t,s,[45,20]),f.now);s=t.series.find(x=>x.id===s.id);}}let final=t.series.find(s=>s.round==='FINAL');for(let i=0;i<4;i++){t=Circuit.recordGame(f.db,f.owner,t.id,final.id,resolved(t,final,[45,20]),f.now);final=t.series.find(s=>s.id===final.id);}assert.equal(final.winnerTeamId,null);assert.deepEqual(final.wins,[4,0]);assert.equal(final.completedGames,4);assert.equal(final.remainingGames,1);assert.equal(t.status,'ACTIVE');Runtime.advance(f.db,{now:f.now,budget:0});const active=Runtime.activeGames(f.db).find(g=>g.gameId===final.id+':game5');assert.ok(active);const result=resolved(t,final,[45,20]);t=Circuit.recordGame(f.db,f.owner,t.id,final.id,result,f.now);final=t.series.find(s=>s.id===final.id);assert.equal(final.games.length,5);assert.deepEqual(final.aggregateKills,[225,100]);assert.equal(final.winnerTeamId,final.teamIds[0]);assert.equal(t.status,'COMPLETED');const completed=JSON.parse(JSON.stringify(t));Runtime.advance(f.db,{now:f.now+1000,budget:12000});assert.deepEqual(Circuit.getTournament(f.db,f.owner,t.id),completed);assert.equal(Runtime.activeGames(f.db).length,0);assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_matches WHERE series_id=?').get(final.id).n,5);assert.deepEqual(snapshot(f.db),f.before);
 }finally{f.close();}
});
test('corrupt persisted checkpoint fails visibly without discarding or restarting the partially played game',()=>{
 const f=fixture();let restarted;try{Runtime.advance(f.db,{now:f.now,budget:90});const active=Runtime.activeGames(f.db)[0],metadata=JSON.parse(f.db.prepare('SELECT metadata_json FROM tournaments WHERE id=?').get(f.t.id).metadata_json);metadata.runtimeGames[active.gameId].sourceHash='wrong-source-hash';const corrupt=JSON.stringify(metadata);f.db.prepare('UPDATE tournaments SET metadata_json=? WHERE id=?').run(corrupt,f.t.id);const copy=path.join(f.directory,'corrupt.sqlite');f.db.prepare('VACUUM INTO ?').run(copy);restarted=createDatabase(copy);assert.throws(()=>Runtime.advance(restarted,{now:f.now+1000,budget:90}),/checkpoint identity/);assert.equal(restarted.prepare('SELECT metadata_json FROM tournaments WHERE id=?').get(f.t.id).metadata_json,corrupt);assert.equal(Runtime.activeGames(restarted).length,0);assert.equal(restarted.prepare('SELECT count(*) n FROM tournament_matches WHERE tournament_id=?').get(f.t.id).n,0);assert.deepEqual(snapshot(restarted),f.before);
 }finally{restarted?.close();f.close();}
});
test('runtime start is idempotent and stopping/restarting the same database resumes one existing game',()=>{
 const f=fixture();let stop;try{Runtime.advance(f.db,{now:f.now,budget:90});const prior=Runtime.activeGames(f.db)[0];stop=Runtime.start(f.db);assert.equal(Runtime.start(f.db),stop,'One scheduler timer per database');stop();assert.equal(Runtime.activeGames(f.db).length,0);stop=Runtime.start(f.db);Runtime.advance(f.db,{now:f.now+1000,budget:0});const current=Runtime.activeGames(f.db)[0];assert.equal(current.gameId,prior.gameId);assert.equal(current.elapsedMs,prior.elapsedMs);assert.equal(current.steps,prior.steps);assert.equal(current.resumed,true);assert.equal(Runtime.activeGames(f.db).length,1);assert.deepEqual(snapshot(f.db),f.before);
 }finally{stop?.();f.close();}
});
test('unsupported checkpoint dependency or binding changes retain the saved game instead of silently using different gameplay',()=>{
 const f=fixture();let restarted;try{Runtime.advance(f.db,{now:f.now,budget:90});const active=Runtime.activeGames(f.db)[0],original=JSON.parse(f.db.prepare('SELECT metadata_json FROM tournaments WHERE id=?').get(f.t.id).metadata_json);for(const variant of ['dependency','binding','size']){const metadata=JSON.parse(JSON.stringify(original));if(variant==='dependency')metadata.runtimeGames[active.gameId].dependencies['tactical-instinct.js']='different-tactical-source';else if(variant==='binding')metadata.runtimeGames[active.gameId].bindingVersion=999;else metadata.runtimeGames[active.gameId].bytes=32*1024*1024;const recorded=JSON.stringify(metadata);f.db.prepare('UPDATE tournaments SET metadata_json=? WHERE id=?').run(recorded,f.t.id);const copy=path.join(f.directory,variant+'.sqlite');f.db.prepare('VACUUM INTO ?').run(copy);restarted=createDatabase(copy);assert.throws(()=>Runtime.advance(restarted,{now:f.now+1000,budget:90}),variant==='dependency'?/engine dependencies changed.*saved game retained/:/Unsupported tournament checkpoint/);assert.equal(restarted.prepare('SELECT metadata_json FROM tournaments WHERE id=?').get(f.t.id).metadata_json,recorded);assert.equal(Runtime.activeGames(restarted).length,0);assert.deepEqual(snapshot(restarted),f.before);restarted.close();restarted=null;}
 }finally{restarted?.close();f.close();}
});
test('legacy active tournaments retain best-of advancement and deterministic game IDs without relabeling historical results',()=>{
 const f=fixture({human:true});try{const t=f.t;delete t.rulesetId;for(const s of t.series){for(const key of ['rulesetId','requiredGames','aggregateKills','completedGames','remainingGames','status','advancement'])delete s[key];f.db.prepare('UPDATE tournament_series SET state_json=? WHERE id=?').run(JSON.stringify(s),s.id);}const state=JSON.parse(f.db.prepare('SELECT bracket_json FROM tournaments WHERE id=?').get(t.id).bracket_json);delete state.rulesetId;state.series=t.series;f.db.prepare('UPDATE tournaments SET bracket_json=? WHERE id=?').run(JSON.stringify(state),t.id);let current=Circuit.getTournament(f.db,f.owner,t.id),s=current.series[0],id=s.teamIds[0];for(let i=0;i<2;i++){const context=Runtime.playContext(f.db,f.owner,t.id);assert.equal(context.gameId,s.id+':game'+(i+1));assert.equal(context.rulesetId,undefined);current=Circuit.recordGame(f.db,f.owner,t.id,s.id,resolved(current,s,[45,20]),f.now);s=current.series.find(x=>x.id===s.id);}assert.equal(s.games.length,2);assert.equal(s.winnerTeamId,id);assert.equal(s.aggregateKills,undefined);assert.deepEqual(snapshot(f.db),f.before);
 }finally{f.close();}
});
