'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),v8=require('node:v8'),zlib=require('node:zlib');
const {fixture}=require('../../dev/live-circuit-tournament-check.cjs'),{createDatabase}=require('../db.cjs'),Circuit=require('../tournaments.cjs'),Runtime=require('../tournament-runtime.cjs'),Presentation=require('../tournament-presentation.cjs'),{createServer}=require('../index.cjs'),Progression=require('../progression.cjs');
const USER='live-circuit-fixture';
function event(f,human=false){const t=Circuit.scheduleOfficial(f.db,USER,f.season,Date.now()).filter(t=>t.startsAt>Date.now())[0];assert.ok(t);if(human)Circuit.registerTeam(f.db,USER,t.id,{name:'Checked-in team',participantIds:[USER]},t.startsAt-1000);return t;}
function payload(db,eventId,gameId){const m=JSON.parse(db.prepare('SELECT metadata_json FROM tournaments WHERE id=?').get(eventId).metadata_json);return v8.deserialize(zlib.inflateSync(Buffer.from(m.runtimeGames[gameId].data,'base64')));}
function worldRows(db){return Object.fromEntries(['worlds','user_career_stats','bot_careers','weapon_patch_stats','tournament_earnings'].map(t=>[t,db.prepare('SELECT * FROM '+t).all()]));}
test('four scheduled quarterfinals run together on elapsed wall time and restore exact checkpoints',()=>{
 const f=fixture();let restarted;try{const t=event(f),at=t.startsAt,before=worldRows(f.db);
  Runtime.advance(f.db,{now:at,budget:10000});assert.equal(Runtime.activeGames(f.db).length,0);assert.equal(Circuit.getTournament(f.db,USER,t.id).scheduling.reservations.length,40);
  Runtime.advance(f.db,{now:at+90000,budget:10000});let games=Runtime.activeGames(f.db);assert.equal(games.length,4);assert.ok(games.every(g=>g.steps===0));
  const allPeople=games.flatMap(g=>payload(f.db,t.id,g.gameId).snapshot.state.matches.find(m=>m?.context?.gameId===g.gameId).participants.map(a=>a.participantId));assert.equal(new Set(allPeople).size,40);
  Runtime.advance(f.db,{now:at+117000,budget:10000});games=Runtime.activeGames(f.db);assert.ok(games.every(g=>g.status==='countdown'&&g.steps===810));
  for(const g of games){const p=payload(f.db,t.id,g.gameId),m=p.snapshot.state.matches.find(m=>m?.context?.gameId===g.gameId);assert.ok(m.participants.every(a=>a.stats.shots===0));assert.ok(Math.abs(m.countdownUntil-p.snapshot.simulationTime-3000)<.01);}
  Runtime.advance(f.db,{now:at+120100,budget:10000});games=Runtime.activeGames(f.db);assert.ok(games.every(g=>g.status==='active'));const stepCounts=games.map(g=>g.steps);Runtime.advance(f.db,{now:at+120100,budget:10000});assert.deepEqual(Runtime.activeGames(f.db).map(g=>g.steps),stepCounts,'Repeated scheduler calls never invent time');
  Runtime.advance(f.db,{now:at+125000,budget:10000});games=Runtime.activeGames(f.db);const key=games[0].gameId,saved=payload(f.db,t.id,key),copy=path.join(f.directory,'scheduled-restart.sqlite');f.db.prepare('VACUUM INTO ?').run(copy);restarted=createDatabase(copy);Runtime.advance(restarted,{now:at+125000,budget:0});assert.equal(Runtime.activeGames(restarted).length,4);assert.deepEqual(payload(restarted,t.id,key),saved);Runtime.advance(restarted,{now:at+126000,budget:10000});Runtime.advance(f.db,{now:at+126000,budget:10000});assert.deepEqual(payload(restarted,t.id,key),payload(f.db,t.id,key));
  assert.deepEqual(worldRows(f.db),before,'Tournament combat cannot change normal careers, XP, meta or earnings');
 }finally{restarted?.close();f.close();}
});
test('an early finalized game waits for its fixed next block and offline missed events cancel without invented results',()=>{
 const f=fixture();try{const t=event(f),at=t.startsAt;Runtime.advance(f.db,{now:at,budget:0});Runtime.advance(f.db,{now:at+90000,budget:0});Runtime.advance(f.db,{now:at+120000,budget:1000});let current=Circuit.getTournament(f.db,USER,t.id),s=current.series[0],gameId=s.id+':game1',roster=current.scheduling.games[gameId].teams;
  const result={id:gameId,winnerTeamId:s.teamIds[0],score:[50,20],duration:30,stats:roster.flatMap((team,index)=>team.participants.map((p,i)=>({participantId:p.id,kills:index?4:10,deaths:index?10:4,assists:0,damage:index?1000:2500,shots:100,hits:50,headshots:0,timeAlive:30})))};Circuit.recordGame(f.db,USER,t.id,s.id,result,at+150000);
  Runtime.advance(f.db,{now:at+151000,budget:0});assert.ok(Runtime.activeGames(f.db).every(g=>g.gameId!==s.id+':game2'));current=Circuit.getTournament(f.db,USER,t.id);assert.equal(current.scheduling.games[s.id+':game2'].checkInOpenAt,at+480000);const before=f.db.prepare('SELECT count(*) n FROM tournament_matches').get().n;
  Runtime.advance(f.db,{now:at+10*60000,budget:0});assert.equal(Circuit.getTournament(f.db,USER,t.id).status,'CANCELLED');assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_matches').get().n,before);assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_earnings').get().n,0);
 }finally{f.close();}
});
test('authorized check-in, safe preparation, private leases and unique human results use the actual API',async()=>{
 const f=fixture(),realNow=Date.now;let app;try{const t=event(f,true);let now=t.startsAt;Date.now=()=>now;const token=crypto.randomBytes(32).toString('base64url'),cookie='sar_session='+token;f.db.prepare('INSERT INTO sessions(token_hash,user_id,created_at,expires_at,last_seen_at) VALUES(?,?,?,?,?)').run(crypto.createHash('sha256').update(token).digest('hex'),USER,now,now+86400000,now);
  Runtime.advance(f.db,{now,budget:0});let current=Circuit.getTournament(f.db,USER,t.id),s=current.series.find(s=>s.teamIds.some(id=>current.teams.find(t=>t.id===id).participants.some(p=>p.id===USER))),gameId=s.id+':game1';app=createServer({db:f.db});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+app.server.address().port+'/api/tournaments/'+t.id;
  const call=async(action,body={},auth=true)=>{const r=await fetch(base+(action?'/'+action:''),{method:action?'POST':'GET',headers:{'content-type':'application/json',...(auth?{cookie}:{})},...(action?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};};
  assert.equal((await call('check-in',{gameId},false)).status,401);assert.equal((await call('check-in',{gameId})).status,200);assert.equal((await call('check-in',{gameId})).status,200);assert.equal((await call('play',{gameId,clientId:'fixture-tab-1'})).status,409);
  now=t.startsAt+90000;Runtime.advance(f.db,{now,budget:0});const entered=await call('play',{gameId,clientId:'fixture-tab-1'});assert.equal(entered.status,200,JSON.stringify(entered.body));const context=entered.body.context;assert.ok(context.leaseToken);const body={gameId,clientId:'fixture-tab-1',leaseToken:context.leaseToken};assert.equal((await call('play',{gameId,clientId:'fixture-tab-2'})).status,409);const detail=await call('');assert.equal(detail.status,200);assert.equal(detail.body.tournament.scheduling.games[gameId].lease.token,undefined);assert.equal(detail.body.tournament.scheduling.games[gameId].lease.clientId,undefined);
  now+=4000;assert.equal((await call('ready',body)).status,200);for(now=t.startsAt+104000;now<t.startsAt+120000;now+=10000)assert.equal((await call('heartbeat',body)).status,200);
  now=t.startsAt+120000;assert.equal((await call('heartbeat',body)).status,200);current=Circuit.getTournament(f.db,USER,t.id);assert.equal(current.scheduling.games[gameId].startedAt,now);assert.equal((await call('play',{...body,resume:false})).status,409);assert.equal((await call('play',{...body,resume:true})).status,200);
  now+=16000;const resumed=await call('play',{gameId,clientId:'reopened-tab',resume:true});assert.equal(resumed.status,200,JSON.stringify(resumed.body));assert.notEqual(resumed.body.context.leaseToken,body.leaseToken);assert.equal((await call('heartbeat',body)).status,409,'The old window loses its lease on resume');Object.assign(body,{clientId:'reopened-tab',leaseToken:resumed.body.context.leaseToken,resume:true});assert.equal((await call('ready',body)).status,200,'Actual saved-game recovery does not reset preparation');
  const result={id:gameId,winnerTeamId:s.teamIds[0],score:[50,20],duration:30,stats:context.teams.flatMap((team,index)=>team.participants.map(p=>({participantId:p.id,kills:index?4:10,deaths:index?10:4,assists:0,damage:index?1000:2500,shots:100,hits:50,headshots:0,timeAlive:30})))};now+=30000;assert.equal((await call('result',{seriesId:s.id,result,...body,leaseToken:'wrong'})).status,409);assert.equal((await call('result',{seriesId:s.id,result,...body})).status,200);assert.equal((await call('result',{seriesId:s.id,result,...body})).status,200);assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_matches WHERE id=?').get(gameId).n,1);
  const xp={kind:'official',tournamentId:t.id,seriesId:s.id,stats:result.stats.find(p=>p.participantId===USER),won:result.winnerTeamId===context.teams.find(team=>team.participants.some(p=>p.id===USER)).id};assert.doesNotThrow(()=>Progression.validateTournamentProgression(f.db,USER,{progression:{awards:{[gameId]:xp}}},{progression:{awards:{}}}));assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_earnings').get().n,0);
 }finally{Date.now=realNow;if(app?.server.listening)await new Promise(resolve=>app.server.close(resolve));f.close();}
});
