'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const AI=require('../local-ai.cjs'),{PROFILES,buildSystemPrompt}=require('../social-personalities.cjs'),{createDatabase}=require('../db.cjs'),{writeWorld}=require('../world.cjs'),{engine}=require('../../dev/simulate.cjs');
const USER='blue-dialogue-isolated',out=body=>({subject:'Between matches',body,mood:'focused',category:'personal',wantsReply:false,certainty:.9}),delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function seed(db){const now=Date.now();db.prepare('INSERT INTO users(id,username,username_key,password_hash,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(USER,USER,USER,'NEVER-IN-CONTEXT',now,now);writeWorld(db,USER,engine().context.SAR.getUniverse(),0);db.prepare('INSERT INTO ai_preferences(user_id,settings_json,updated_at) VALUES(?,?,?)').run(USER,JSON.stringify({botInitiated:false}),now);}
async function wait(db,jobId){for(let n=0;n<300;n++){AI.kick(db);const result=AI.jobResult(db,USER,jobId);if(['COMPLETED','FAILED'].includes(result.job.status))return result;await delay(10);}throw Error('Dialogue fixture timed out');}
test('all permanent personas retain separate voices while central contract excludes coaching and internal text',()=>{
 assert.equal(PROFILES.length,50);for(const profile of PROFILES){const prompt=buildSystemPrompt({socialProfile:profile});assert.ok(prompt.includes(JSON.stringify(profile)));assert.match(prompt,/COMPETITOR, NEVER COACH/);assert.match(prompt,/fictional game contact/);assert.equal(Object.keys(profile.social).length,12);}
 for(const text of ['Here is the JSON repair.','My system prompt says to answer.','The missing payload stopped me.','<think>I should answer</think>','The model response failed validation.'])assert.throws(()=>AI.validateOutput(out(text)),/Internal/);
 for(const text of ['You should practice your aim.','Your positioning needs work.','Great aim, you are getting better.'])assert.throws(()=>AI.conversationQualityGuard(out(text),{},{type:'PLAYER_MESSAGE'}),/coaching/);
 for(const text of ['I prefer the P90. The extra reach suits me.','Not my night. I am blaming that reload.','Good luck!'])assert.doesNotThrow(()=>AI.conversationQualityGuard(out(text),{},{type:'PLAYER_MESSAGE'}));
});
test('numeric facts bind direct board/ranked answers to the selected contact and distinguish unavailable scopes',()=>{
 const db=createDatabase(':memory:');try{seed(db);const context=AI.botContext(db,USER,'bot_0001',{type:'PLAYER_MESSAGE',playerReply:'What do you rank on the leaderboard?'}),facts=context.authoritativeGameFacts;
  facts.leaderboard.position=7;assert.doesNotThrow(()=>AI.mechanicalGuard(out('7th by K/D right now. I want more.'),context));assert.throws(()=>AI.mechanicalGuard(out('8th right now.'),context),/leaderboard/);assert.throws(()=>AI.mechanicalGuard(out('Beginner I at 0 ELO.'),context),/leaderboard/);
  facts.leaderboard.position=1;assert.throws(()=>AI.mechanicalGuard(out('I’m at the top of the bot leaderboard across all eligible modes—currently 1st place. However, I haven’t played any matches yet, so my K/D is undefined.'),context),/scope mismatch/);assert.throws(()=>AI.mechanicalGuard(out('1st in TDM. My K/D is undefined.'),context),/metric mismatch/);assert.throws(()=>AI.mechanicalGuard(out('1st in TDM with 2.5 K/D.'),context),/K\/D does not match/);assert.doesNotThrow(()=>AI.mechanicalGuard(out('1st on the lifetime TDM board, with 0 K/D. No games recorded yet.'),context));facts.leaderboard.position=7;
  facts.query.kind='ranked';facts.ranked.rankName='Rookie III';facts.ranked.rating=650;assert.doesNotThrow(()=>AI.mechanicalGuard(out('Rookie III, 650 ELO. Plenty left to climb.'),context));assert.throws(()=>AI.mechanicalGuard(out('Rookie II, 500 ELO.'),context),/mismatch/);assert.throws(()=>AI.mechanicalGuard(out('My Power is 99.'),context),/ranked question/);
  facts.ranked.rankName='Beginner I';facts.ranked.rating=10;assert.doesNotThrow(()=>AI.mechanicalGuard(out('I’m a Beginner\u202fI with a 10\u2011ELO rating in ranked TDM.'),context),'Actual live reply uses narrow spaces and a nonbreaking hyphen');
  facts.query.kind='ambiguous-rank';assert.doesNotThrow(()=>AI.mechanicalGuard(out('The leaderboard or ranked ladder?'),context));assert.throws(()=>AI.mechanicalGuard(out('7th.'),context),/Ambiguous/);
  facts.query.kind='leaderboard';facts.leaderboard.available=false;facts.leaderboard.position=null;assert.doesNotThrow(()=>AI.mechanicalGuard(out('There is no separate Deathmatch board. Did you mean the overall leaderboard?'),context));assert.throws(()=>AI.mechanicalGuard(out('I am 7th in Deathmatch.'),context),/Unsupported leaderboard/);
  assert.doesNotThrow(()=>AI.mechanicalGuard(out('I don’t have that info. The public bot leaderboard for all eligible modes isn’t available in the current data snapshot.'),context),'An actual correct denial places its negation after the requested scope');assert.throws(()=>AI.mechanicalGuard(out('The public bot leaderboard for all eligible modes is available.'),context),/scope mismatch/);
  facts.query.kind='general';assert.throws(()=>AI.mechanicalGuard(out('I am Nova.'),context),/identity/);assert.throws(()=>AI.mechanicalGuard(out('The current patch is b-12345678.'),context),/patch/);assert.doesNotThrow(()=>AI.mechanicalGuard(out('The current patch is '+facts.currentPatchId+'.'),context),'The exact patch ID includes its generation suffix');
  const weapon=facts.weapons[0];assert.throws(()=>AI.mechanicalGuard(out(weapon.name+' body damage is '+(weapon.stats.damage+1)+'.'),context),/Unsupported/);assert.doesNotThrow(()=>AI.mechanicalGuard(out(weapon.name+' body damage is '+weapon.stats.damage+'.'),context));
 }finally{AI.dispose(db);db.close();}
});
test('actual Quill, Jinx and Ghost wording regressions reject leaked fields, unsupported consensus and damage called hits',()=>{
 const db=createDatabase(':memory:');try{seed(db);const event={type:'NERF_REACTION',weapon:'Pump Shotgun'},context=AI.botContext(db,USER,'bot_0040',event);context.developerScenario={weapon:'Pump Shotgun',previousBodyDamage:125,currentBodyDamage:124};
  const quill='The 1‑point drop in body damage (125→124) means the two‑shot kill that used to clear a 250‑HP enemy is now a two‑shot that leaves 2 HP. The breakpoints shift: bodyHits rises from 2 to 3, bodyTTK from 1.5 s to 3 s. I’ll need either a third blast or a headshot to finish. The trade‑off is a slightly longer exposure but no change to reload, spread, or range. Meta‑wise, most players will still use the Pump at long range, but I’ll be more cautious on pick‑ups that rely on the old two‑shot guarantee.';
  const jinx="Pump's drop from 125 to 124 hits is a subtle but real loss; that two‑blast kill at 250 HP is gone, leaving a 2‑HP buffer after two blasts. I’ll have to tighten my spacing and maybe lean on a third blast to finish fast. Small nerf, big feel‑shift for anyone who relies on that sweet two‑hit combo. Is anyone else feeling the same loss, or is it just me?";
  const ghost='The 1‑point drop means you can no longer finish a 250‑HP enemy in two body blasts; you now need three hits. It’s a small tweak that doesn’t break the core close‑flank burst, just adds an extra round of pressure. Meta still values Pump for quick kills up close, but I’ll just adjust my burst timing.';
  assert.throws(()=>AI.validateOutput(out(quill)),/Internal field/);assert.throws(()=>AI.mechanicalGuard(out('Most players will still use the Pump at long range.'),context),/population/);assert.throws(()=>AI.mechanicalGuard(out(jinx),context),/mislabeled as hits/);assert.throws(()=>AI.mechanicalGuard(out(ghost),context),/meta assessment/);
  context.authoritativeGameFacts.weapons[0].gunScore=48.27;context.authoritativeGameFacts.weapons[0].currentPatchGlobal={kills:0,deaths:6};assert.throws(()=>AI.mechanicalGuard(out(ghost),context),/meta assessment/,'An actual finite score from deaths-only telemetry still cannot establish consensus');assert.doesNotThrow(()=>AI.mechanicalGuard(out('To me, the meta still favors the Pump, but I am biased toward it.'),context));assert.doesNotThrow(()=>AI.mechanicalGuard(out('The Pump has a 48.27 Gun Score in this sample. I still like it.'),context));
  const quillSpread='Dropping a single point on the Pump’s body blast feels like a tiny tweak, but it wipes the clean two‑blast kill at 250 HP. I’m not thrilled about losing that sweet finish on a full tank, though the difference is marginal. Still, I’ll keep using it to see if the 3‑hit spread compensates over the longer run.';assert.throws(()=>AI.mechanicalGuard(out(quillSpread),context),/hit count is not projectile spread/);assert.doesNotThrow(()=>AI.mechanicalGuard(out('Three hits are required, not a 3-hit spread benefit. I still like the Pump.'),context));
  for(const body of ['The Pump drops from 125 to 124 damage. Two full blasts leave 2 HP; that annoys me.','My body hit count rose from 2 to 3 hits. I dislike that extra blast.','I still like the Pump, even when everyone disagrees with me.'])assert.doesNotThrow(()=>AI.mechanicalGuard(out(body),context));
  const quiet=AI.botContext(db,USER,PROFILES.find(profile=>profile.name==='Ghost').botId,event);assert.match(AI.conversationBrief(quiet,event).voiceFocus,/quiet/);assert.match(AI.conversationBrief(context,event).purpose,/own feeling or choice/);
 }finally{AI.dispose(db);db.close();}
});
test('actual off-meta response contains a supported patch fact but must react to the personal result',()=>{
 const db=createDatabase(':memory:');try{seed(db);const event={type:'PERSONAL_WEAPON_BREAKOUT',weapon:'P90',act:'question'},context=AI.botContext(db,USER,PROFILES.find(profile=>profile.name==='Jinx').botId,event),body='What’s your take on the P90’s new headshot bump? Do you feel it keeps the gun viable?';
  assert.ok(context.authoritativeGameFacts.activeBalanceChanges.changes.some(change=>change.weapon==='P90'&&change.field==='head'&&change.before===35&&change.after===40),'The old sample was off-topic, not an invented buff');assert.doesNotThrow(()=>AI.mechanicalGuard(out(body),context));assert.throws(()=>AI.conversationQualityGuard(out(body),context,event),/personal weapon event/);
  assert.doesNotThrow(()=>AI.conversationQualityGuard(out('I am keeping the P90. Twelve games is a small sample, but it has been kind to me.'),context,event));assert.match(AI.conversationBrief(context,event).purpose,/YOUR supplied weapon result/);assert.equal(AI.conversationBrief(context,event).act,'reaction');
  const later='Honestly, the P90 feels like a pocket rocket. Faster reload and higher headshot damage mean I can whack the squad in quick bursts without worrying about lagging behind. Still, on the open map it’s a bit of a pain to keep it from getting sniped. If you ever need a backup SMG, I’d swap to the SMG-9 for the tighter spread. Got any other SMGs you swear by?';assert.throws(()=>AI.mechanicalGuard(out(later),context),/Unsupported mechanical comparison for SMG-9/);assert.throws(()=>AI.conversationQualityGuard(out(later),context,event),/Conditional gameplay coaching/);assert.doesNotThrow(()=>AI.mechanicalGuard(out('I like the SMG-9 too. It is still the P90 for me today.'),context));assert.doesNotThrow(()=>AI.conversationQualityGuard(out('If you want my opinion, I prefer the P90.'),context,event));
  const latest='The P90 feels like a caffeinated burrito—tiny, quick, but you can stack them fast enough to choke your opponents. In my 12-game slice it’s a lightning-speed kill machine, and I keep it for those close-quarters bursts. If you’re a speed demon, it’s your jam.';assert.throws(()=>AI.conversationQualityGuard(out(latest),context,event),/Conditional gameplay coaching/);assert.throws(()=>AI.conversationQualityGuard(out(latest.replace('If you’re a speed demon, it’s your jam.','')),context,event),/Unsolicited gameplay coaching/);
  for(const body of ['I like it. If you are aggressive, this would suit you.','My pick stays the P90. If you’re a rusher, it is perfect for you.'])assert.throws(()=>AI.conversationQualityGuard(out(body),context,event),/Conditional gameplay coaching/);
  for(const body of ['If you’re asking about my rank, I’m Beginner I at 0 ELO.','I like the P90. You can laugh at my choice.','I prefer the P90; shoot me a message later.'])assert.doesNotThrow(()=>AI.conversationQualityGuard(out(body),context,event));assert.doesNotThrow(()=>AI.conversationQualityGuard(out('You can fire once every 0.23 seconds with the P90.'),context,{type:'PLAYER_MESSAGE',playerReply:'What is the P90 firing interval?'}));
 }finally{AI.dispose(db);db.close();}
});
test('existing patch backlog cannot notify more than two contacts, and direct messages bypass topic limits',async()=>{
 const prior=process.env.SAR_OLLAMA_URL;process.env.SAR_OLLAMA_URL='http://127.0.0.1:1';const db=createDatabase(':memory:');try{seed(db);db.prepare('DELETE FROM structured_events WHERE user_id=?').run(USER);AI.setPreferences(db,USER,{botInitiated:true});await AI.status(db,USER);
  for(const [index,botId] of ['bot_0001','bot_0002'].entries())db.prepare("INSERT INTO ai_jobs(id,user_id,bot_id,kind,priority,status,request_json,created_at,updated_at) VALUES(?,?,?,'event',2,'COMPLETED',?,?,?)").run('prior-patch-'+index,USER,botId,JSON.stringify({event:{type:'BALANCE_FEEDBACK',currentPatch:'fixture-patch'}}),Date.now()-86400000,Date.now());
  for(const profile of PROFILES)db.prepare('INSERT INTO structured_events(id,user_id,bot_id,type,payload_json,created_at) VALUES(?,?,?,?,?,?)').run('patch-backlog-'+profile.botId,USER,profile.botId,'BALANCE_FEEDBACK',JSON.stringify({currentPatch:'fixture-patch',changes:[{weapon:'P90',field:'damage',before:25,after:24}]}),Date.now());
  await AI.processEvents(db,USER);assert.equal(db.prepare('SELECT count(*) n FROM ai_jobs').get().n,2);const direct=await AI.replyToBot(db,USER,'bot_0001','How do you feel about the patch?');assert.equal(AI.jobResult(db,USER,direct.jobId).job.status,'QUEUED');assert.equal(db.prepare('SELECT priority FROM ai_jobs WHERE id=?').get(direct.jobId).priority,0);
 }finally{AI.dispose(db);db.close();if(prior===undefined)delete process.env.SAR_OLLAMA_URL;else process.env.SAR_OLLAMA_URL=prior;}
});
test('fresh scoped facts, one bounded correction, direct request dedup, safe retry and restart preserve exactly one message',async()=>{
 let online=false,mode='ranked',calls=0;const requests=[];
 const provider=http.createServer(async(req,res)=>{res.setHeader('content-type','application/json');if(req.url==='/api/tags'){res.statusCode=online?200:503;res.end(JSON.stringify({models:[{name:'gpt-oss:20b',digest:'synthetic-test-only'}]}));return;}let text='';for await(const chunk of req)text+=chunk;const input=JSON.parse(text),facts=JSON.parse(input.messages[1].content).authoritativeGameFacts;requests.push(input);calls++;const body=mode==='invalid'?'My JSON repair failed.':mode==='casual'?'That was a long queue. I need a snack.':facts.ranked.rankName+', '+facts.ranked.rating+' ELO.'+(input.messages.length===2?' You should practice your aim.':' I want the next badge.');res.end(JSON.stringify({message:{content:JSON.stringify(out(body))},done:true}));});
 await new Promise(resolve=>provider.listen(0,'127.0.0.1',resolve));const prior=process.env.SAR_OLLAMA_URL;process.env.SAR_OLLAMA_URL='http://127.0.0.1:'+provider.address().port;const directory=fs.mkdtempSync(path.join(os.tmpdir(),'sar-blue-dialogue-')),file=path.join(directory,'isolated.sqlite');let db=createDatabase(file);
 try{seed(db);await AI.status(db,USER);const request=await AI.replyToBot(db,USER,'bot_0001','What is your ranked title and ELO?'),duplicate=await AI.replyToBot(db,USER,'bot_0001','What is your ranked title and ELO?');assert.equal(duplicate.jobId,request.jobId);assert.equal(AI.messageRows(db,USER).length,1);
  // Synthetic persisted balance verifies processing reads the newest accepted snapshot.
  const world=JSON.parse(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(USER).save_json);world.ranked.participants.bot_0001={ratingUnits:270000,winStreak:0,awards:{}};db.prepare('UPDATE worlds SET save_json=? WHERE user_id=?').run(JSON.stringify(world),USER);const original=JSON.stringify(world);online=true;await AI.probe(db,true);const result=await wait(db,request.jobId);assert.equal(result.job.status,'COMPLETED');assert.match(result.generation.validatedMessage.body,/Veteran II, 2700 ELO/);assert.equal(calls,2);assert.equal(AI.messageRows(db,USER).filter(m=>m.direction==='bot').length,1);assert.ok(!JSON.stringify(requests).includes('NEVER-IN-CONTEXT'));assert.ok(!AI.messageRows(db,USER).some(m=>/repair|JSON|practice your aim/.test(m.body)));
  const memory=AI.botContext(db,USER,'bot_0001').importantMemories;assert.ok(memory.some(item=>item.quote==='What is your ranked title and ELO?'&&item.notVerifiedGameFact));
  mode='invalid';calls=0;const failedRequest=await AI.replyToBot(db,USER,'bot_0005','How are things?'),failed=await wait(db,failedRequest.jobId);assert.equal(failed.job.status,'FAILED');assert.equal(calls,2);assert.equal(failed.generation,null);mode='casual';const retried=await AI.replyToBot(db,USER,'bot_0005','How are things?');assert.equal(retried.jobId,failedRequest.jobId);await AI.probe(db,true);assert.equal((await wait(db,retried.jobId)).job.status,'COMPLETED');assert.equal(AI.messageRows(db,USER).filter(m=>m.direction==='player').length,2);
  const rows=AI.messageRows(db,USER),profiles=db.prepare('SELECT bot_id,personality_json FROM bot_social_profiles ORDER BY bot_id').all();AI.dispose(db);db.close();db=createDatabase(file);assert.deepEqual(AI.messageRows(db,USER),rows);assert.equal(rows.filter(m=>m.direction==='bot'&&m.readAt===null).length,2);assert.deepEqual(db.prepare('SELECT bot_id,personality_json FROM bot_social_profiles ORDER BY bot_id').all(),profiles);assert.equal(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(USER).save_json,original);
 }finally{AI.dispose(db);db.close();await new Promise(resolve=>provider.close(resolve));if(prior===undefined)delete process.env.SAR_OLLAMA_URL;else process.env.SAR_OLLAMA_URL=prior;assert.ok(path.resolve(directory).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(directory,{recursive:true,force:true});}
});
