'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {DatabaseSync}=require('node:sqlite'),{createDatabase}=require('../db.cjs');
const Circuit=require('../tournaments.cjs'),Schedule=require('../tournament-schedule.cjs'),Lifecycle=require('../tournament-lifecycle.cjs'),Presentation=require('../tournament-presentation.cjs'),Reset=require('../tournament-reset.cjs');
const {fixture,snapshot}=require('../../dev/live-circuit-tournament-check.cjs'),{game}=require('../../dev/arena-refined-tournament-series-check.cjs');
const USER='live-circuit-fixture',clone=value=>JSON.parse(JSON.stringify(value));
function official(f){return Circuit.scheduleOfficial(f.db,USER,f.season,f.season.startAt).find(t=>t.status==='REGISTRATION');}
function humanRoster(f,t,count){
 for(let n=0;n<count;n++){const id=n===0?USER:'human-fixture-'+n;if(n)f.db.prepare('INSERT INTO users(id,username,username_key,password_hash,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(id,id,id,'fixture-not-a-password',1,1);const teamIndex=Math.floor(n/5);if(!t.teams[teamIndex]){const team={id:crypto.randomUUID(),seed:teamIndex+1,name:'Human Team '+(teamIndex+1),participants:[]};t.teams.push(team);f.db.prepare('INSERT INTO tournament_teams VALUES(?,?,?,?)').run(team.id,t.id,team.name,team.seed);}const team=t.teams[teamIndex];team.participants.push({id,kind:'user',name:id});f.db.prepare('INSERT INTO tournament_registrations VALUES(?,?,?,?)').run(t.id,team.id,id,'user');}
 const state=JSON.parse(f.db.prepare('SELECT bracket_json FROM tournaments WHERE id=?').get(t.id).bracket_json);state.teams=t.teams;f.db.prepare('UPDATE tournaments SET bracket_json=? WHERE id=?').run(JSON.stringify(state),t.id);return Circuit.getTournament(f.db,USER,t.id);
}
function finish(db,t,g,at){Circuit.claimScheduledGame(db,USER,t.id,g.gameId,{owner:'server',ttlMs:60000},at);Circuit.markScheduledPrepared(db,USER,t.id,g.gameId,at);Circuit.markScheduledStarted(db,USER,t.id,g.gameId,Circuit.getTournament(db,USER,t.id).scheduling.games[g.gameId].lease.token,g.matchStartAt);t=Circuit.getTournament(db,USER,t.id);const s=t.series.find(s=>s.id===g.seriesId);return Circuit.recordGame(db,USER,t.id,s.id,game(t,s,[50,20],{id:g.gameId}),g.matchStartAt+1000);}
for(const count of [40,20,1,0])test('official '+count+' humans: honest 8×5 completion and 40 reserved bots/standbys',()=>{
 const f=fixture();try{let t=humanRoster(f,official(f),count);t=Circuit.prepareReservations(f.db,USER,t.id,t.startsAt-7*60000);assert.equal(t.scheduling.reservations.length,40);assert.equal(new Set(t.scheduling.reservations).size,40);assert.equal(t.teams.flatMap(team=>team.participants).length,count);t=Circuit.advanceScheduled(f.db,USER,t.id,t.startsAt);const people=t.teams.flatMap(team=>team.participants);assert.equal(t.status,'ACTIVE');assert.equal(t.teams.length,8);assert.ok(t.teams.every(team=>team.participants.length===5));assert.equal(new Set(people.map(p=>p.id)).size,40);assert.equal(people.filter(p=>p.kind==='user').length,count);assert.equal(t.scheduling.standbyReservations.length,count);assert.equal(t.scheduling.reservations.length,40);assert.ok(t.scheduling.reservations.every(id=>f.db.prepare('SELECT 1 FROM bots WHERE user_id=? AND bot_id=?').get(USER,id)));f.reopen();assert.deepEqual(Circuit.advanceScheduled(f.db,USER,t.id,t.startsAt+1000).teams,t.teams);
 }finally{f.close();}
});
test('pre-reservation occurs before background game maximum duration without changing bot identities or personality',()=>{
 const f=fixture();try{const t=official(f),before=snapshot(f.db);assert.equal(Circuit.prepareReservations(f.db,USER,t.id,t.startsAt-7*60000-1).scheduling.reservations.length,0);const prepared=Circuit.prepareReservations(f.db,USER,t.id,t.startsAt-7*60000);assert.ok(prepared.scheduling.reservationLeadMs>5*60000);assert.equal(prepared.scheduling.reservedAt,t.startsAt-7*60000);assert.deepEqual(snapshot(f.db),before);assert.deepEqual(Circuit.prepareReservations(f.db,USER,t.id,t.startsAt-6*60000).scheduling.reservations,prepared.scheduling.reservations);
 }finally{f.close();}
});
test('all 40 missing humans replace atomically at deadline and repeat/reconnect never resurrect their slots',()=>{
 const f=fixture();try{let t=humanRoster(f,official(f),40);t=Circuit.advanceScheduled(f.db,USER,t.id,t.startsAt);const at=t.startsAt+90000;t=Circuit.advanceScheduled(f.db,USER,t.id,at);assert.equal(t.replacementHistory.length,40);assert.ok(t.teams.every(team=>team.participants.every(p=>p.kind==='bot')));assert.equal(t.scheduling.reservations.length,40);assert.equal(t.scheduling.standbyReservations.length,0);assert.equal(new Set(t.replacementHistory.map(r=>r.replacement.id)).size,40);for(const r of t.replacementHistory){assert.equal(r.reason,'NO_SHOW');assert.equal(r.round,'QF');assert.equal(r.gameNumber,1);assert.equal(r.at,at);assert.equal(r.payoutOwnerId,r.replacement.id);assert.equal(r.returnPolicy,'permanent-for-event');}const history=clone(t.replacementHistory);f.reopen();assert.deepEqual(Circuit.advanceScheduled(f.db,USER,t.id,at+1).replacementHistory,history);assert.throws(()=>Circuit.checkIn(f.db,USER,t.id,{gameId:history[0].gameId},at+2),/does not occupy/);assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_stats').get().n,0);assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_earnings').get().n,0);
 }finally{f.close();}
});
test('overlapping future reservations conflict visibly, never double-book, release when custom is deleted',()=>{
 const f=fixture();try{const first=official(f),second=Circuit.createCustom(f.db,USER,{name:'Overlap',startsAt:first.startsAt},first.startsAt-3600000),at=first.startsAt-7*60000;const reserved=Circuit.prepareReservations(f.db,USER,first.id,at),conflict=Circuit.prepareReservations(f.db,USER,second.id,at);assert.equal(conflict.scheduling.conflicts[0].code,'ROSTER_ALLOCATION_CONFLICT');assert.equal(conflict.scheduling.reservations.length,0);assert.equal(reserved.scheduling.reservations.length,40);assert.throws(()=>Circuit.registerTeam(f.db,USER,second.id,{name:'Trying booked bot',participantIds:[reserved.scheduling.reservations[0]]},at),/already committed/);Circuit.deleteCustom(f.db,USER,second.id,'Overlap',at+1);assert.equal(JSON.parse(f.db.prepare('SELECT metadata_json FROM tournaments WHERE id=?').get(second.id).metadata_json).scheduling.reservations.length,0);
 }finally{f.close();}
});
test('low competition willingness can decline an invitation yet cannot starve vacant real-bot roster slots',()=>{
 const f=fixture();try{const t=official(f);f.db.prepare('UPDATE bot_competition_profiles SET competitiveness=0,socialness=0,ego=0 WHERE user_id=?').run(USER);f.db.prepare('UPDATE bots SET form=-10 WHERE user_id=?').run(USER);const before=snapshot(f.db);assert.equal(Circuit.decision(f.db,USER,t,'bot_0001').accepted,false);const filled=Circuit.advanceScheduled(f.db,USER,t.id,t.startsAt);assert.equal(filled.status,'ACTIVE');assert.equal(filled.teams.flatMap(team=>team.participants).length,40);assert.deepEqual(snapshot(f.db),before);
 }finally{f.close();}
});
for(const count of [40,20,1,0])test('custom '+count+' humans: autofill and real deadline without official recurring schedule',()=>{
 const f=fixture();try{let t=Circuit.createCustom(f.db,USER,{name:'Custom coverage '+count,startsAt:f.season.startAt+3600000},f.season.startAt);t=humanRoster(f,t,count);t=Circuit.advanceCustom(f.db,USER,t.id,t.startsAt);assert.equal(t.status,'ACTIVE');assert.equal(t.customTimetable,true);assert.equal(t.startsAt,f.season.startAt+3600000);assert.equal(t.teams.flatMap(team=>team.participants).length,40);const q=Object.values(t.scheduling.games);assert.equal(q.length,4);assert.ok(q.every(g=>g.checkInCloseAt===t.startsAt+90000&&g.matchStartAt===t.startsAt+120000));t=Circuit.advanceScheduled(f.db,USER,t.id,t.startsAt+90000);assert.ok(t.teams.every(team=>team.participants.every(p=>p.kind==='bot')));assert.equal(t.replacementHistory?.length||0,count);const presentation=Presentation.schedule(t,[],{},t.startsAt+90000);assert.equal(presentation.status,'confirmed');assert.equal(presentation.seriesGames.length,4);assert.ok(presentation.message.includes('Custom games'));assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_earnings').get().n,0);
 }finally{f.close();}
});
test('custom next game uses saved preceding completion; all 3/3/5 games and payout exclusions survive restart',()=>{
 const f=fixture();try{let t=Circuit.createCustom(f.db,USER,{name:'All custom games',startsAt:f.season.startAt+3600000},f.season.startAt);t=Circuit.advanceCustom(f.db,USER,t.id,t.startsAt);let guard=0;while(t.status!=='COMPLETED'&&guard++<24){const windows=Schedule.gameWindows(t,t.schedulePolicy),pending=windows.filter(w=>!t.series.find(s=>s.id===w.seriesId).games.some(g=>g.id===w.gameId));assert.ok(pending.length);const opening=Math.min(...pending.map(w=>w.checkInOpenAt));t=Circuit.advanceScheduled(f.db,USER,t.id,opening);const due=Object.values(t.scheduling.games).filter(g=>!g.finalizedAt&&g.checkInOpenAt===opening);t=Circuit.advanceScheduled(f.db,USER,t.id,opening+90000);for(const g of due)t=finish(f.db,t,g,opening+90000);if(guard===1){const prior=t.series[0].games[0];f.reopen();t=Circuit.advanceScheduled(f.db,USER,t.id,prior.completedAt);const next=t.scheduling.games[t.series[0].id+':game2'];assert.equal(next.checkInOpenAt,prior.completedAt);}}
 assert.equal(t.status,'COMPLETED');assert.deepEqual(t.series.map(s=>s.games.length),[3,3,3,3,3,3,5]);assert.equal(t.scheduling.reservations.length,0);assert.equal(t.earnings.length,40);assert.ok(t.earnings.every(e=>e.amount===0));assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_matches WHERE tournament_id=?').get(t.id).n,23);
 }finally{f.close();}
});
function graph(db,ids){const tables=['tournaments','tournament_teams','tournament_registrations','tournament_series','tournament_matches','tournament_stats','tournament_placements','tournament_earnings','tournament_invites','tournament_participants'];return Object.fromEntries(tables.map(table=>[table,db.prepare('SELECT * FROM '+table+' ORDER BY rowid').all().filter(row=>ids.has(table==='tournaments'?row.id:row.tournament_id)).map(row=>({...row}))]));}
test('schema10→11 once-only reset retains exact completed history/earnings/shared world and recoverable original/anchor',()=>{
 const f=fixture();let migrated;try{const initial=official(f),anchor=JSON.parse(f.db.prepare('SELECT metadata_json FROM tournaments WHERE id=?').get(initial.id).metadata_json).officialSchedule.anchor;let completed=Circuit.createCustom(f.db,USER,{name:'Historical champion',startsAt:f.season.startAt},f.season.startAt);f.db.prepare("UPDATE tournaments SET kind='official' WHERE id=?").run(completed.id);completed=Circuit.startTournament(f.db,USER,completed.id,completed.startsAt);for(let n=0;completed.status!=='COMPLETED';n++){const s=completed.series.find(s=>Circuit.canPlaySeries(s,completed));completed=Circuit.recordGame(f.db,USER,completed.id,s.id,game(completed,s,[50,20]),completed.startsAt+n+1);}assert.equal(completed.earnings.length,40);
 const unfinished=Circuit.createCustom(f.db,USER,{name:'Retired unfinished',startsAt:initial.startsAt},f.season.startAt);Circuit.registerTeam(f.db,USER,unfinished.id,{name:'Partial',participantIds:[USER]},f.season.startAt);const m=Lifecycle.metadata(f.db,unfinished.id);m.scheduling={games:{stale:{checkIns:{[USER]:{at:1}},lease:{owner:'server'}}},reservations:['bot_0001'],conflicts:[]};m.runtimeGames={stale:{bytes:1}};Lifecycle.saveMetadata(f.db,unfinished.id,m,f.season.startAt);
 const preserved=graph(f.db,new Set([completed.id])),before=snapshot(f.db);f.db.exec('DROP TABLE tournament_reset_archives; DROP TABLE tournament_state_resets; DROP TABLE tournament_schedule_anchors; DELETE FROM save_migrations WHERE version=11; PRAGMA user_version=10');f.db.close();migrated=createDatabase(f.file);assert.equal(migrated.prepare('PRAGMA user_version').get().user_version,11);assert.deepEqual(graph(migrated,new Set([completed.id])),preserved);assert.deepEqual(snapshot(migrated),before);assert.equal(migrated.prepare("SELECT count(*) n FROM tournaments WHERE status<>'COMPLETED'").get().n,0);assert.equal(migrated.prepare('SELECT count(*) n FROM tournament_state_resets').get().n,1);const marker=migrated.prepare('SELECT * FROM tournament_state_resets').get();assert.equal(marker.reset_id,Reset.RESET_ID);assert.ok(fs.existsSync(marker.recovery_file));assert.deepEqual(JSON.parse(migrated.prepare('SELECT anchor_json FROM tournament_schedule_anchors WHERE user_id=?').get(USER).anchor_json),anchor);assert.equal(migrated.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.deepEqual(migrated.prepare('PRAGMA foreign_key_check').all(),[]);
 const original=new DatabaseSync(marker.recovery_file,{readOnly:true});try{assert.equal(original.prepare('PRAGMA user_version').get().user_version,10);assert.ok(original.prepare('SELECT 1 FROM tournaments WHERE id=?').get(unfinished.id));assert.deepEqual(graph(original,new Set([completed.id])),preserved);}finally{original.close();}
 const now=initial.startsAt+10000,events=Circuit.scheduleOfficial(migrated,USER,f.season,now),future=events.filter(t=>t.status==='REGISTRATION');assert.ok(future.length);assert.ok(future.every(t=>t.startsAt>now));const ids=future.map(t=>t.id);migrated.close();migrated=createDatabase(f.file);assert.deepEqual(Circuit.scheduleOfficial(migrated,USER,f.season,now).filter(t=>t.status==='REGISTRATION').map(t=>t.id),ids);assert.equal(migrated.prepare('SELECT count(*) n FROM tournament_state_resets').get().n,1);assert.equal(fs.readdirSync(f.directory).filter(name=>name.includes('.pre-schema10-')).length,1);assert.deepEqual(graph(migrated,new Set([completed.id])),preserved);assert.deepEqual(snapshot(migrated),before);
 }finally{if(migrated?.isOpen)migrated.close();f.close();}
});
test('reset archives accepted games and raw official statistics from an unfinished event without inventing a champion',()=>{
 const f=fixture();let migrated;try{let t=Circuit.createCustom(f.db,USER,{name:'Partial official results',startsAt:f.season.startAt},f.season.startAt);f.db.prepare("UPDATE tournaments SET kind='official' WHERE id=?").run(t.id);t=Circuit.startTournament(f.db,USER,t.id,t.startsAt);const s=t.series[0];t=Circuit.recordGame(f.db,USER,t.id,s.id,game(t,s,[50,20]),t.startsAt+1000);const matches=f.db.prepare('SELECT * FROM tournament_matches WHERE tournament_id=? ORDER BY completed_at,id').all(t.id).map(r=>({...r})),stats=f.db.prepare('SELECT * FROM tournament_stats WHERE tournament_id=? ORDER BY participant_id').all(t.id).map(r=>({...r}));const before=snapshot(f.db);f.db.exec('DROP TABLE tournament_reset_archives; DROP TABLE tournament_state_resets; DROP TABLE tournament_schedule_anchors; DELETE FROM save_migrations WHERE version=11; PRAGMA user_version=10');f.db.close();migrated=createDatabase(f.file);assert.equal(migrated.prepare('SELECT 1 FROM tournaments WHERE id=?').get(t.id),undefined);const row=migrated.prepare('SELECT * FROM tournament_reset_archives WHERE tournament_id=? AND user_id=?').get(t.id,USER),archived=JSON.parse(row.snapshot_json);assert.equal(archived.event.kind,'official');assert.equal(archived.event.name,'Partial official results');assert.deepEqual(archived.matches,matches);assert.deepEqual(archived.stats,stats);assert.deepEqual(archived.earnings,[]);assert.deepEqual(archived.placements,[]);assert.equal(JSON.parse(archived.event.bracket_json).series.find(s=>s.round==='FINAL').winnerTeamId,null);assert.deepEqual(JSON.parse(archived.event.metadata_json),{retiredByReset:Reset.RESET_ID});assert.deepEqual(snapshot(migrated),before);const exact=row.snapshot_json;migrated.close();migrated=createDatabase(f.file);assert.equal(migrated.prepare('SELECT snapshot_json FROM tournament_reset_archives WHERE tournament_id=?').get(t.id).snapshot_json,exact);assert.equal(migrated.prepare('SELECT count(*) n FROM tournament_reset_archives').get().n,1);
 }finally{if(migrated?.isOpen)migrated.close();f.close();}
});
test('failed reset rolls back schema and state; fixing the recorded fault lets one clean retry succeed',()=>{
 const f=fixture();try{const t=official(f);f.db.prepare('UPDATE tournaments SET metadata_json=? WHERE id=?').run('{invalid-json',t.id);f.db.exec('DROP TABLE tournament_reset_archives; DROP TABLE tournament_state_resets; DROP TABLE tournament_schedule_anchors; DELETE FROM save_migrations WHERE version=11; PRAGMA user_version=10');f.db.close();assert.throws(()=>createDatabase(f.file),SyntaxError);const old=new DatabaseSync(f.file);try{assert.equal(old.prepare('PRAGMA user_version').get().user_version,10);assert.equal(old.prepare("SELECT name FROM sqlite_master WHERE name='tournament_state_resets'").get(),undefined);assert.ok(old.prepare('SELECT 1 FROM tournaments WHERE id=?').get(t.id));assert.ok(fs.readdirSync(f.directory).some(name=>name.includes('.pre-schema10-')));old.prepare('UPDATE tournaments SET metadata_json=? WHERE id=?').run('{}',t.id);}finally{old.close();}const restored=createDatabase(f.file);try{assert.equal(restored.prepare('PRAGMA user_version').get().user_version,11);assert.equal(restored.prepare('SELECT count(*) n FROM tournament_state_resets').get().n,1);assert.equal(restored.prepare('PRAGMA integrity_check').get().integrity_check,'ok');}finally{restored.close();}
 }finally{f.close();}
});
test('authenticated custom API auto-fills, checks in, locks, leases, accepts one result and permanently replaces a later no-show',async()=>{
 const f=fixture(),{createServer}=require('../index.cjs'),realNow=Date.now,token=crypto.randomBytes(32).toString('base64url'),cookie='sar_session='+token;let clock=realNow(),app;
 f.db.prepare('INSERT INTO sessions(token_hash,user_id,created_at,expires_at,last_seen_at) VALUES(?,?,?,?,?)').run(crypto.createHash('sha256').update(token).digest('hex'),USER,clock,clock+86400000,clock);Date.now=()=>clock;
 try{app=createServer({db:f.db});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+app.server.address().port,request=async(route,body)=>{const r=await fetch(base+'/api/tournaments'+route,{method:body?'POST':'GET',headers:{cookie,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,body:await r.json()};};
  let r=await request('',{name:'Real custom queue API',startsAt:clock+60000});assert.equal(r.status,201);let t=r.body.tournament;const route='/'+t.id;assert.equal(t.teams[0].participants.length,1);r=await request(route+'/start',{});assert.equal(r.status,200);assert.equal(r.body.tournament.status,'REGISTRATION');clock=t.startsAt;r=await request(route+'/start',{});assert.equal(r.status,200);t=r.body.tournament;assert.equal(t.status,'ACTIVE');assert.equal(t.customTimetable,true);assert.ok(t.teams.every(team=>team.participants.length===5));const team=t.teams.find(team=>team.participants.some(p=>p.id===USER)),series=t.series.find(s=>s.teamIds.includes(team.id)),gameId=series.id+':game1',clientId='custom-api-fixture-client';assert.equal((await request(route+'/play',{gameId,clientId})).status,409);assert.equal((await request(route+'/check-in',{gameId})).status,200);assert.equal((await request(route+'/check-in',{gameId})).status,200);
  clock=t.startsAt+90000;t=Circuit.advanceScheduled(f.db,USER,t.id,clock);for(const g of Object.values(t.scheduling.games).filter(g=>!g.teams.some(team=>team.participants.some(p=>p.kind==='user')))){Circuit.claimScheduledGame(f.db,USER,t.id,g.gameId,{owner:'server',ttlMs:60000},clock);Circuit.markScheduledPrepared(f.db,USER,t.id,g.gameId,clock);}
  r=await request(route+'/play',{gameId,clientId});assert.equal(r.status,200,JSON.stringify(r.body));const context=r.body.context,leaseToken=context.leaseToken;assert.equal(context.schedule.checkInCloseAt,t.startsAt+90000);assert.equal((await request(route+'/ready',{gameId,clientId,leaseToken})).status,200);for(const offset of [100000,110000,120000]){clock=t.startsAt+offset;assert.equal((await request(route+'/heartbeat',{gameId,clientId,leaseToken})).status,200);}
  for(const g of Object.values(Circuit.getTournament(f.db,USER,t.id).scheduling.games).filter(g=>g.gameId!==gameId))Circuit.markScheduledStarted(f.db,USER,t.id,g.gameId,g.lease.token,clock);
  t=Circuit.getTournament(f.db,USER,t.id);const result=game(t,t.series.find(s=>s.id===series.id),[50,20],{id:gameId});clock+=1000;const payload={seriesId:series.id,result,clientId,leaseToken};r=await request(route+'/result',payload);assert.equal(r.status,200,JSON.stringify(r.body));assert.equal((await request(route+'/result',payload)).status,200);assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_matches WHERE id=?').get(gameId).n,1);const acceptedHuman=JSON.parse(f.db.prepare('SELECT stats_json FROM tournament_stats WHERE tournament_id=? AND participant_id=?').get(t.id,USER).stats_json);assert.equal(acceptedHuman.games,1);
  t=Circuit.advanceScheduled(f.db,USER,t.id,clock);const second=t.scheduling.games[series.id+':game2'];assert.equal(second.checkInOpenAt,clock);clock=second.checkInCloseAt;t=Circuit.advanceScheduled(f.db,USER,t.id,clock);assert.equal(t.replacementHistory.length,1);assert.equal(t.replacementHistory[0].previous.id,USER);assert.equal(t.replacementHistory[0].round,'QF');assert.equal(t.replacementHistory[0].gameNumber,2);assert.ok(!t.teams.some(team=>team.participants.some(p=>p.id===USER)));assert.ok([403,409].includes((await request(route+'/check-in',{gameId:second.gameId})).status));assert.deepEqual(JSON.parse(f.db.prepare('SELECT stats_json FROM tournament_stats WHERE tournament_id=? AND participant_id=?').get(t.id,USER).stats_json),acceptedHuman);assert.equal(f.db.prepare('SELECT count(*) n FROM tournament_earnings').get().n,0);
  const world=await fetch(base+'/api/world',{headers:{cookie}}),view=await world.json();assert.equal(view.tournamentResetId,Reset.RESET_ID);assert.ok(view.tournamentReservations.some(event=>event.id===t.id));assert.equal((await request('')).body.tournamentResetId,Reset.RESET_ID);
 }finally{Date.now=realNow;if(app?.server.listening)await new Promise(resolve=>app.server.close(resolve));f.close();}
});
