'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createDatabase}=require('../db.cjs'),{createServer}=require('../index.cjs'),{writeWorld}=require('../world.cjs'),{engine}=require('../../dev/simulate.cjs'),Circuit=require('../tournaments.cjs'),Runtime=require('../tournament-runtime.cjs'),{snapshot,resolvedGame}=require('../../dev/live-circuit-tournament-check.cjs');
const HOUR=3600000;
function account(db,id){const now=Date.now(),world=engine().context.SAR.getUniverse(),token=crypto.randomBytes(32).toString('base64url');db.prepare('INSERT INTO users(id,username,username_key,password_hash,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(id,id,id,'isolated-not-a-real-password',now,now);db.prepare('INSERT INTO sessions(token_hash,user_id,created_at,expires_at,last_seen_at) VALUES(?,?,?,?,?)').run(crypto.createHash('sha256').update(token).digest('hex'),id,now,now+86400000,now);writeWorld(db,id,world,0);return {cookie:'sar_session='+token,world};}
function eligible(db,id,t){return db.prepare('SELECT bot_id FROM bots WHERE user_id=? ORDER BY bot_id').all(id).filter(b=>Circuit.decision(db,id,t,b.bot_id).accepted).map(b=>b.bot_id);}
test('saved-world bootstrap supplies account-owned official and custom active reservations before client allocation',async()=>{
 const db=createDatabase(':memory:'),owner='reservation-api-a',a=account(db,owner),b=account(db,'reservation-api-b'),now=Date.now(),event=Circuit.scheduleOfficial(db,owner,a.world.seasons.current,now)[0];
 let official=Runtime.fillBots(db,owner,event,now);official=Circuit.startTournament(db,owner,official.id,official.startsAt);
 const custom=Circuit.createCustom(db,owner,{name:'Custom reservation',startsAt:now+HOUR},now);db.prepare("UPDATE tournaments SET status='ACTIVE' WHERE id=?").run(custom.id);
 const before=db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(owner).save_json,app=createServer({db});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
 const request=async cookie=>{const response=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/world',{headers:{cookie}});return {status:response.status,body:await response.json()};};
 try{const result=await request(a.cookie);assert.equal(result.status,200);assert.deepEqual(result.body.tournamentReservations.map(t=>t.id).sort(),[official.id,custom.id].sort());const active=result.body.tournamentReservations.find(t=>t.id===official.id);assert.equal(active.teams.flatMap(t=>t.participants).length,40);assert.equal(new Set(active.teams.flatMap(t=>t.participants.map(p=>p.id))).size,40);assert.deepEqual(result.body.world.save,JSON.parse(before));assert.deepEqual((await request(b.cookie)).body.tournamentReservations,[]);assert.equal((await request('')).status,401);assert.equal(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(owner).save_json,before);}
 finally{await new Promise(resolve=>app.server.close(resolve));db.close();}
});
test('all baseline identities can participate and four actual invitations plus automatic bot filling form eight complete teams',()=>{
 const db=createDatabase(':memory:');try{const id='baseline-circuit',a=account(db,id),now=a.world.seasons.current.startAt+HOUR,t=Circuit.createCustom(db,id,{name:'Baseline Participation Fixture',startsAt:now},now),before=db.prepare('SELECT bot_id,competitiveness,socialness,ego FROM bot_competition_profiles ORDER BY bot_id').all();assert.equal(eligible(db,id,t).length,50,'All 50 baseline competition profiles currently meet the actual 0.37 threshold without fixture trait changes');let value=Circuit.registerTeam(db,id,t.id,{name:'Player Circuit',participantIds:[id]},now),host=value.teams[0];
  for(const botId of eligible(db,id,t).slice(0,4))value=Circuit.inviteBot(db,id,t.id,{teamId:host.id,botId},now);assert.equal(value.teams[0].participants.length,5);assert.equal(value.invites.length,4);assert.ok(value.invites.every(invite=>invite.state==='ACCEPTED'));value=Runtime.fillBots(db,id,value,now);assert.equal(value.teams.length,8);assert.ok(value.teams.every(team=>team.participants.length===5));assert.equal(new Set(value.teams.flatMap(team=>team.participants.map(p=>p.id))).size,40);assert.equal(Circuit.startTournament(db,id,t.id,now).status,'ACTIVE');assert.deepEqual(db.prepare('SELECT bot_id,competitiveness,socialness,ego FROM bot_competition_profiles ORDER BY bot_id').all(),before);
 }finally{db.close();}
});
test('actual background combat persists completed games without a client and continues after database restart without changing standard statistics',()=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'sar-circuit-runtime-')),file=path.join(directory,'isolated.sqlite');let db=createDatabase(file);try{const id='background-circuit',a=account(db,id),now=a.world.seasons.current.startAt+HOUR,t=Circuit.createCustom(db,id,{name:'Background Combat Fixture',startsAt:now},now);const before=snapshot(db);Runtime.advance(db,{now,budget:0});assert.equal(db.prepare('SELECT count(*) n FROM tournament_matches WHERE tournament_id=?').get(t.id).n,0,'Opening check-in must not start hidden combat');for(let tick=now+10000;tick<=now+420000;tick+=10000)Runtime.advance(db,{now:tick,budget:400});let current=Circuit.getTournament(db,id,t.id),matches=db.prepare('SELECT id,result_json FROM tournament_matches WHERE tournament_id=?').all(t.id);assert.equal(current.status,'ACTIVE');assert.ok(matches.length>=1,'The real headless engine must complete at least one 5v5 game without a connected client');const firstIds=new Set(matches.map(m=>m.id));for(const match of matches){const result=JSON.parse(match.result_json);assert.equal(result.stats.length,10);assert.ok(result.stats.some(stat=>stat.shots>0));assert.ok(result.stats.some(stat=>stat.damage>0));assert.ok(result.duration>0);assert.equal(new Set(result.stats.map(stat=>stat.participantId)).size,10);}assert.deepEqual(snapshot(db),before,'Tournament combat must not mutate standard career, profile, seasons, familiarity, meta or Gun Score inputs');
  db.close();db=createDatabase(file);const persisted=Circuit.getTournament(db,id,t.id);assert.deepEqual(persisted.series,current.series);for(let tick=now+430000;tick<=now+900000;tick+=10000)Runtime.advance(db,{now:tick,budget:400});matches=db.prepare('SELECT id,result_json FROM tournament_matches WHERE tournament_id=?').all(t.id);assert.ok(matches.length>firstIds.size,'The real engine continues the saved bracket after backend restart');assert.equal(new Set(matches.map(m=>m.id)).size,matches.length);for(const recorded of firstIds)assert.ok(matches.some(m=>m.id===recorded),'An acknowledged game survives restart');assert.deepEqual(snapshot(db),before);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');
 }finally{db.close();assert.ok(path.resolve(directory).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(directory,{recursive:true,force:true});}
});
test('custom host API invitations/start/play/result preserve account isolation and acknowledge a replay once',async()=>{
 const db=createDatabase(':memory:'),id='circuit-api-a',a=account(db,id),b=account(db,'circuit-api-b'),app=createServer({db});await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+app.server.address().port;
 const request=async(route,{cookie=a.cookie,method='GET',body}={})=>{const response=await fetch(base+'/api/tournaments'+route,{method,headers:{cookie,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,body:await response.json()};};
 try{const created=await request('',{method:'POST',body:{name:'Account API Fixture',startsAt:Date.now()+60000}});assert.equal(created.status,201);let t=created.body.tournament;assert.equal(t.kind,'custom');assert.equal(t.teams.length,1);assert.equal(t.teams[0].participants.length,1);assert.equal(t.teams[0].participants[0].id,id);const route='/'+t.id,host=t.teams[0];for(const botId of ['bot_0001','bot_0002','bot_0003','bot_0004'])assert.equal((await request(route+'/invite',{method:'POST',body:{teamId:host.id,botId}})).status,200);
  // Keep this existing authorization/replay fixture as a persisted unscheduled series; new queue APIs have dedicated coverage.
  const at=Date.now();db.prepare('UPDATE tournaments SET starts_at=? WHERE id=?').run(at,t.id);Circuit.startTournament(db,id,t.id,at);
  const started=await request(route+'/start',{method:'POST',body:{}});assert.equal(started.status,200);t=started.body.tournament;assert.equal(t.status,'ACTIVE');assert.equal(t.teams.length,8);assert.ok(t.teams.every(team=>team.participants.length===5));assert.equal((await request(route,{cookie:b.cookie})).status,404);assert.equal((await request(route+'/play',{cookie:b.cookie,method:'POST',body:{}})).status,404);assert.equal((await request(route+'/invite',{cookie:b.cookie,method:'POST',body:{teamId:host.id,botId:'bot_0005'}})).status,404);const play=await request(route+'/play',{method:'POST',body:{}});assert.equal(play.status,200);const context=play.body.context,series=t.series.find(series=>series.id===context.seriesId);assert.equal(context.hasPlayer,true);assert.ok(context.teams.some(team=>team.participants.some(p=>p.kind==='user'&&p.id===id)));
  const result={...resolvedGame(t,series,host.id),id:context.gameId},before=snapshot(db),foreign=await request(route+'/result',{cookie:b.cookie,method:'POST',body:{seriesId:series.id,result}});assert.equal(foreign.status,404);assert.equal(db.prepare('SELECT count(*) n FROM tournament_matches WHERE id=?').get(result.id).n,0);assert.equal((await request(route+'/result',{method:'POST',body:{seriesId:'wrong-series',result}})).status,409);
  const recorded=await request(route+'/result',{method:'POST',body:{seriesId:series.id,result}});assert.equal(recorded.status,200);const after=JSON.parse(db.prepare('SELECT bracket_json FROM tournaments WHERE id=?').get(t.id).bracket_json),stats=db.prepare('SELECT * FROM tournament_stats WHERE tournament_id=? ORDER BY participant_id').all(t.id),replay=await request(route+'/result',{method:'POST',body:{seriesId:series.id,result}});assert.equal(replay.status,200,'A retry of an acknowledged game must return its tournament without counting another game');assert.equal(db.prepare('SELECT count(*) n FROM tournament_matches WHERE id=?').get(result.id).n,1);assert.deepEqual(JSON.parse(db.prepare('SELECT bracket_json FROM tournaments WHERE id=?').get(t.id).bracket_json),after);assert.deepEqual(db.prepare('SELECT * FROM tournament_stats WHERE tournament_id=? ORDER BY participant_id').all(t.id),stats);assert.deepEqual(snapshot(db),before);assert.equal(db.prepare('SELECT count(*) n FROM tournament_earnings WHERE tournament_id=?').get(t.id).n,0,'Custom games never pay virtual money');
 }finally{await new Promise(resolve=>app.server.close(resolve));db.close();}
});
