'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createDatabase}=require('../db.cjs'),{writeWorld}=require('../world.cjs'),{engine}=require('../../dev/simulate.cjs'),AI=require('../local-ai.cjs'),{PROFILES,EVENT_TYPES}=require('../social-personalities.cjs'),{recordSocialEvents}=require('../social-events.cjs'),Circuit=require('../tournaments.cjs'),fixtures=require('../../dev/live-circuit-tournament-check.cjs');
const USER='dialogue-fixture',delay=ms=>new Promise(resolve=>setTimeout(resolve,ms)),clone=value=>JSON.parse(JSON.stringify(value));
function seed(db){const now=Date.now(),world=engine().context.SAR.getUniverse();db.prepare('INSERT INTO users(id,username,username_key,password_hash,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(USER,USER,USER,'isolated-not-a-password',now,now);writeWorld(db,USER,world,0);db.prepare('INSERT INTO ai_preferences(user_id,settings_json,updated_at) VALUES(?,?,?)').run(USER,JSON.stringify({botInitiated:false}),now);return world;}
const out=body=>({subject:'Fixture conversation',body,mood:'focused',category:'personal',wantsReply:true,certainty:.7});
async function waitJob(db,id,job){for(let count=0;count<250;count++){AI.kick(db);const value=AI.jobResult(db,id,job);if(['COMPLETED','FAILED'].includes(value.job.status))return value;await delay(10);}throw Error('Isolated dialogue job timed out');}
async function mockProvider(handler,run){const server=http.createServer(async(req,res)=>{if(req.url==='/api/tags'){res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({models:[{name:'gpt-oss:20b',digest:'dialogue-test-only'}]}));return;}let raw='';for await(const chunk of req)raw+=chunk;const value=await handler(JSON.parse(raw),req,res);if(value===null)return;res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(value));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const previous=process.env.SAR_OLLAMA_URL;process.env.SAR_OLLAMA_URL='http://127.0.0.1:'+server.address().port;try{await run();}finally{await new Promise(resolve=>server.close(resolve));if(previous===undefined)delete process.env.SAR_OLLAMA_URL;else process.env.SAR_OLLAMA_URL=previous;}}
test('actual completed matches create personality-dependent questions and complaints, with no countdown reminders or identity changes',()=>{
 const db=createDatabase(':memory:');try{let world=seed(db);const before=db.prepare('SELECT bot_id,personality_json FROM bot_social_profiles ORDER BY bot_id').all();assert.equal(before.length,50);assert.equal(EVENT_TYPES.includes('SEASON_FINAL_3_DAYS'),false);assert.equal(EVENT_TYPES.includes('SEASON_FINAL_DAY'),false);
  for(let game=1;game<=120;game++){const previous=clone(world);for(const name of ['Vex','Ghost']){const bot=world.bots[name];bot.career.games++;bot.recentMatches.push({at:1700000000000+game,primary:'P90',won:false,kills:2,deaths:8,damage:500});bot.recentMatches=bot.recentMatches.slice(-10);}world.seasons.current.endAt=Date.now()+3600000;recordSocialEvents(db,USER,previous,world,Date.now()+game);}
  const rows=db.prepare("SELECT bot_id,payload_json FROM structured_events WHERE type='MATCH_CONVERSATION'").all(),vex=PROFILES.find(p=>p.name==='Vex').botId,ghost=PROFILES.find(p=>p.name==='Ghost').botId;assert.equal(rows.filter(r=>r.bot_id===vex).length,40);assert.equal(rows.filter(r=>r.bot_id===ghost).length,10);const acts=new Set(rows.map(r=>JSON.parse(r.payload_json).act));assert.ok(acts.has('question'));assert.ok(acts.has('complaint'));for(const row of rows){const event=JSON.parse(row.payload_json);assert.equal(event.match.won,false);assert.equal(event.match.deaths,8);assert.match(event.topic,/P90/);}
  assert.equal(db.prepare("SELECT count(*) n FROM structured_events WHERE type LIKE 'SEASON_FINAL_%'").get().n,0);assert.deepEqual(db.prepare('SELECT bot_id,personality_json FROM bot_social_profiles ORDER BY bot_id').all(),before);assert.equal(PROFILES.length,50);assert.equal(new Set(PROFILES.map(p=>p.botId)).size,50);
 }finally{AI.dispose(db);db.close();}
});
test('topic reservations survive restart, suppress duplicate initiations, and retain direct player conversations',async()=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'sar-dialogue-cooldown-')),file=path.join(directory,'isolated.sqlite');let db=createDatabase(file);const previous=process.env.SAR_OLLAMA_URL;process.env.SAR_OLLAMA_URL='http://127.0.0.1:1';try{seed(db);db.prepare('DELETE FROM structured_events WHERE user_id=?').run(USER);const original=db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(USER).save_json;db.prepare('UPDATE ai_preferences SET settings_json=? WHERE user_id=?').run(JSON.stringify({botInitiated:true}),USER);
  const add=id=>db.prepare('INSERT INTO structured_events(id,user_id,bot_id,type,payload_json,created_at) VALUES(?,?,?,?,?,?)').run(id,USER,'bot_0001','CAREER_MILESTONE',JSON.stringify({act:'reaction',topic:'career:same-milestone',actualCareerKills:2500}),Date.now());add('duplicate-1');add('duplicate-2');await AI.processEvents(db,USER);AI.dispose(db);assert.equal(db.prepare('SELECT count(*) n FROM ai_jobs').get().n,1);assert.equal(db.prepare("SELECT count(*) n FROM structured_events WHERE id LIKE 'duplicate-%' AND messaged_at IS NOT NULL").get().n,1);
  db.close();db=createDatabase(file);add('duplicate-after-restart');await AI.processEvents(db,USER);AI.dispose(db);assert.equal(db.prepare('SELECT count(*) n FROM ai_jobs').get().n,1);const reply=await AI.replyToBot(db,USER,'bot_0001','What do you think about the match?');AI.dispose(db);assert.equal(AI.jobResult(db,USER,reply.jobId).job.status,'QUEUED');assert.equal(db.prepare('SELECT count(*) n FROM ai_jobs').get().n,2);assert.equal(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(USER).save_json,original);
 }finally{AI.dispose(db);db.close();if(previous===undefined)delete process.env.SAR_OLLAMA_URL;else process.env.SAR_OLLAMA_URL=previous;assert.ok(path.resolve(directory).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(directory,{recursive:true,force:true});}
});
test('new circuit dialogue accepts only actual registration, invitation, bracket, series, placement and payout fields',()=>{
 const f=fixtures.fixture(),id='live-circuit-fixture';try{const now=f.season.startAt+3600000,t=Circuit.createCustom(f.db,id,{name:'Verified Fixture Cup',startsAt:now},now);const roster=[id,...Array.from({length:39},(_,index)=>'bot_'+String(index+1).padStart(4,'0'))];for(let index=0;index<8;index++){Circuit.registerTeam(f.db,id,t.id,{name:'Team '+(index+1),participantIds:index===1?roster.slice(5,6):roster.slice(index*5,index*5+5)},now);if(index===1){const team=Circuit.getTournament(f.db,id,t.id).teams[1];Circuit.inviteBot(f.db,id,t.id,{teamId:team.id,botId:'bot_0001'},now);for(const botId of roster.slice(6,10))Circuit.inviteBot(f.db,id,t.id,{teamId:team.id,botId},now);}}let value=Circuit.getTournament(f.db,id,t.id);Circuit.startTournament(f.db,id,t.id,now);value=fixtures.complete(f.db,t.id,now).value;
  const types=new Set();for(const row of f.db.prepare("SELECT bot_id,type,payload_json FROM structured_events WHERE user_id=? AND type LIKE 'TOURNAMENT_%'").all(id)){if(row.type==='TOURNAMENT_ANNOUNCEMENT')continue;const event={...JSON.parse(row.payload_json),type:row.type},context=AI.botContext(f.db,id,row.bot_id,event);assert.equal(AI.verifiedTournamentEvent(context,event),true,row.type);assert.equal(AI.verifiedTournamentEvent(context,{...event,tournamentId:'invented-tournament'}),false);assert.equal(AI.verifiedTournamentEvent(context,{...event,teamName:'Invented Team'}),false);if(Number.isFinite(event.amount))assert.equal(AI.verifiedTournamentEvent(context,{...event,amount:event.amount+1}),false);if(event.winnerTeamId)assert.equal(AI.verifiedTournamentEvent(context,{...event,winnerTeamId:'invented-winner'}),false);types.add(row.type);}
  assert.deepEqual([...types].sort(),['TOURNAMENT_ACCEPT','TOURNAMENT_BRACKET','TOURNAMENT_DECLINE','TOURNAMENT_ELIMINATION','TOURNAMENT_FINAL','TOURNAMENT_PLACEMENT','TOURNAMENT_WIN'].sort());
  const win=f.db.prepare("SELECT payload_json FROM structured_events WHERE user_id=? AND bot_id='bot_0001' AND type='TOURNAMENT_WIN'").get(id),event={...JSON.parse(win.payload_json),type:'TOURNAMENT_WIN'},context=AI.botContext(f.db,id,'bot_0001',event);assert.ok(context.authoritativeGameFacts.tournaments[0].results.winnerParticipants.includes('Ace'));assert.doesNotThrow(()=>AI.mechanicalGuard(out('We won the tournament. Team 1 earned first place.'),context));assert.throws(()=>AI.mechanicalGuard(out('Vex won the tournament.'),context),/winner identity/);assert.throws(()=>AI.mechanicalGuard(out('We faced Ghost in the tournament final.'),context),/opponent/);assert.doesNotThrow(()=>AI.mechanicalGuard(out('I do not know who might win the next tournament.'),context));
 }finally{AI.dispose(f.db);f.close();}
});
test('repeat guard rejects exact and near repeats while permitting distinct supported points',()=>{
 const previous='I want more range data before we touch the P90 again.',context={recentMessages:[{direction:'bot',body:previous}]};assert.throws(()=>AI.repetitionGuard(out(previous),context),/Repeated/);assert.throws(()=>AI.repetitionGuard(out('Before we touch the P90 again, I want more range data.'),context),/Repeated/);assert.doesNotThrow(()=>AI.repetitionGuard(out('Did your last match change what you think about reload timing?'),context));
});
test('real provider delivery repairs repeated text and retains failures without publishing invented fallback dialogue',async()=>{
 let mode='repeat',requests=[];const previous='I want more range data before we touch the P90 again.';await mockProvider(async payload=>{requests.push(payload);const repair=payload.messages.length>2,body=mode==='invalid'?'Nova won the tournament.':repair?'Did the reload timing change how that last fight felt?':previous;return {message:{content:JSON.stringify(out(body))},done:true};},async()=>{
  const db=createDatabase(':memory:');try{seed(db);const world=db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(USER).save_json,identities=db.prepare('SELECT bot_id,personality_json FROM bot_social_profiles ORDER BY bot_id').all();db.prepare('INSERT INTO messages(id,user_id,bot_id,direction,type,body,created_at,source) VALUES(?,?,?,?,?,?,?,?)').run('earlier',USER,'bot_0001','bot','PLAYER_MESSAGE',previous,Date.now(),'test-fixture');
   const reply=await AI.replyToBot(db,USER,'bot_0001','What did you think?'),complete=await waitJob(db,USER,reply.jobId);assert.equal(complete.job.status,'COMPLETED');assert.equal(requests.length,2);assert.match(requests[1].messages.at(-1).content,/Repeated recent bot dialogue/);assert.equal(requests[1].options.temperature,.25);assert.equal(requests[0].format.required.length,6);assert.equal(JSON.parse(requests[0].messages[1].content).event.act,'reaction');assert.equal(AI.messageRows(db,USER).filter(m=>m.direction==='bot'&&m.body===previous).length,1);
   mode='invalid';requests=[];const failure=await AI.replyToBot(db,USER,'bot_0005','Who won the tournament?'),failed=await waitJob(db,USER,failure.jobId);assert.equal(failed.job.status,'FAILED');assert.match(failed.job.error,/Unsupported tournament winner/);assert.equal(requests.length,2);assert.equal(failed.generation,null);assert.equal(db.prepare("SELECT count(*) n FROM messages WHERE event_id=? AND direction='bot'").get(db.prepare('SELECT event_id FROM ai_jobs WHERE id=?').get(failure.jobId).event_id).n,0);assert.equal(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(USER).save_json,world);assert.deepEqual(db.prepare('SELECT bot_id,personality_json FROM bot_social_profiles ORDER BY bot_id').all(),identities);
  }finally{AI.dispose(db);db.close();}
 });
});
test('truncated reasoning retries with the existing larger low-think JSON budget and preserves world data',async()=>{
 const requests=[];await mockProvider(async payload=>{requests.push(payload);return requests.length===1?{message:{content:''},done_reason:'length'}:{message:{content:JSON.stringify(out('Would you rather keep that loadout for the next match?'))},done_reason:'stop'};},async()=>{
  const db=createDatabase(':memory:');try{seed(db);const world=db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(USER).save_json,reply=await AI.replyToBot(db,USER,'bot_0001','What should we try?'),value=await waitJob(db,USER,reply.jobId);assert.equal(value.job.status,'COMPLETED');assert.equal(requests.length,2);assert.equal(requests[0].think,'medium');assert.equal(requests[0].options.num_predict,1200);assert.equal(requests[1].think,'low');assert.equal(requests[1].options.num_predict,4096);assert.match(requests[1].messages.at(-1).content,/exhausted its reply budget/);assert.equal(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(USER).save_json,world);
  }finally{AI.dispose(db);db.close();}
 });
});
test('transient provider failures retry durably instead of becoming permanent failed messages',async()=>{
 let calls=0;await mockProvider(async(payload,req,res)=>{calls++;if(calls<=2){res.writeHead(503,{'content-type':'application/json'});res.end(JSON.stringify({error:'Isolated provider unavailable'}));return null;}return {message:{content:JSON.stringify(out('Did that match make you reconsider the reload timing?'))},done:true};},async()=>{
  const db=createDatabase(':memory:');try{seed(db);const original=db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(USER).save_json,reply=await AI.replyToBot(db,USER,'bot_0001','What happened?');
   for(let attempt=1;attempt<=2;attempt++){for(let count=0;count<200;count++){const row=db.prepare('SELECT status,attempts FROM ai_jobs WHERE id=?').get(reply.jobId);if(row.status==='QUEUED'&&row.attempts===attempt)break;await delay(10);}const row=db.prepare('SELECT * FROM ai_jobs WHERE id=?').get(reply.jobId);assert.equal(row.status,'QUEUED');assert.equal(row.attempts,attempt);assert.match(row.error,/Model HTTP 503/);assert.ok(row.next_attempt_at>Date.now());assert.equal(AI.messageRows(db,USER).filter(m=>m.direction==='bot').length,0);db.prepare('UPDATE ai_jobs SET next_attempt_at=0 WHERE id=?').run(reply.jobId);await AI.probe(db,true);AI.kick(db);}
   const result=await waitJob(db,USER,reply.jobId);assert.equal(result.job.status,'COMPLETED');assert.equal(calls,3);assert.equal(db.prepare('SELECT attempts FROM ai_jobs WHERE id=?').get(reply.jobId).attempts,3);
   AI.dispose(db);db.prepare("UPDATE ai_jobs SET status='FAILED',error='Model HTTP 503',next_attempt_at=0 WHERE id=?").run(reply.jobId);AI.runtime(db);assert.equal(AI.jobResult(db,USER,reply.jobId).job.status,'QUEUED');assert.equal(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(USER).save_json,original);
  }finally{AI.dispose(db);db.close();}
 });
});

test('competitive conversation briefs target the actual event and reject pointless initiations without blocking direct replies',()=>{
 const context={recentMessages:[{direction:'bot',subject:'Reload exposure',body:'Earlier point'},{direction:'player',body:'My answer'}]};
 for(const body of ['Just checking in. How are you?', 'Quick reminder: check the tournament calendar.', 'Ready for the next match?', 'Keep practicing!'])assert.throws(()=>AI.conversationQualityGuard(out(body),context,{type:'MATCH_CONVERSATION'}),/Low-value/);
 assert.doesNotThrow(()=>AI.conversationQualityGuard(out('The longer burst cycle makes a missed opening expensive. Are you staying with the AUG?'),context,{type:'NERF_REACTION'}));
 assert.doesNotThrow(()=>AI.conversationQualityGuard(out('Good luck!'),context,{type:'PLAYER_MESSAGE',playerReply:'Wish me luck.'}));
 const patch=AI.conversationBrief(context,{type:'NERF_REACTION',weapon:'SR-Aug',act:'complaint'});assert.equal(patch.weapon,'SR-Aug');assert.equal(patch.act,'complaint');assert.match(patch.purpose,/actual change/);assert.deepEqual(patch.avoidRecentTopics,['Reload exposure']);assert.equal(patch.questionLimit,1);
 const reply=AI.conversationBrief(context,{type:'PLAYER_MESSAGE'});assert.equal(reply.freshPointRequired,false);assert.match(reply.purpose,/Answer the latest player message directly/);
 const {dialogueIntent,buildSystemPrompt,personalityFor}=require('../social-personalities.cjs'),bot={name:'Vex',socialProfile:personalityFor('Vex')};
 assert.equal(dialogueIntent(bot,{type:'NERF_REACTION',weapon:'SR-Aug',currentPatch:'patch7',act:'complaint'}).topic,dialogueIntent(bot,{type:'META_OPINION',weapon:'SR-Aug',currentPatch:'patch7',act:'question'}).topic,'changing conversational act cannot bypass a topic cooldown');
 assert.notEqual(dialogueIntent(bot,{type:'NERF_REACTION',weapon:'SR-Aug',currentPatch:'patch7'}).topic,dialogueIntent(bot,{type:'NERF_REACTION',weapon:'SR-Aug',currentPatch:'patch8'}).topic,'a genuinely new patch can supply a new topic');
 assert.match(buildSystemPrompt(bot),/answer their actual last question first/);assert.match(buildSystemPrompt(bot),/fictional game Skirmish Arena\./);
});

test('map dialogue rejects invented vertical roof angles and crosswalk cover while retaining existing physical cover',()=>{
 const db=createDatabase(':memory:');try{seed(db);const context=AI.botContext(db,USER,'bot_0001',{type:'MAP_FEEDBACK'});assert.match(context.authoritativeGameFacts.map.movementPlane,/flat world plane/);assert.match(context.authoritativeGameFacts.map.polish,/presentation only/);
 for(const body of ['The new house roofs give vertical angles, cutaway interiors allow quick cover switches, sidewalks and crosswalks create natural chokepoints, and neighborhood props add varied cover options. Do you find the crosswalks give you more cover?', 'The rooftops give us high ground.', 'Can you use the new roofs for an elevation advantage?', 'Crosswalks give you extra cover.', 'Use the road markings for protection.'])assert.throws(()=>AI.mechanicalGuard(out(body),context),/Unsupported map geometry/);
 for(const body of ['The roofs look sharper, but they do not give us high ground.', 'Crosswalks do not provide cover. I would stick to existing physical walls.', 'The house siding is easier to read. Do the crosswalk markings look clearer to you?', 'I still want a physical wall between me and that lane.'])assert.doesNotThrow(()=>AI.mechanicalGuard(out(body),context));
 }finally{AI.dispose(db);db.close();}
});
