'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),bcrypt=require('bcryptjs');
const {createDatabase}=require('../db.cjs'),{writeWorld}=require('../world.cjs'),{engine}=require('../../dev/simulate.cjs'),AI=require('../local-ai.cjs'),{PROFILES,personalityFor}=require('../social-personalities.cjs'),{scores}=require('../weapon-dialogue.cjs');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
test('large pending social backlog avoids loading world context when the initiation budget is full',async()=>{
  const db=createDatabase(':memory:');try{
    const id=seed(db),before=db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(id).save_json;
    AI.setPreferences(db,id,{botInitiated:true});
    for(let i=0;i<6;i++)db.prepare("INSERT INTO ai_jobs(id,user_id,bot_id,kind,priority,status,request_json,created_at,updated_at) VALUES(?,?,?,'event',1,'COMPLETED',?,?,?)").run('budget-'+i,id,'bot_0001',JSON.stringify({event:{type:'CAREER_MILESTONE'}}),Date.now(),Date.now());
    for(let i=0;i<200;i++)db.prepare('INSERT INTO structured_events(id,user_id,bot_id,type,payload_json,created_at) VALUES(?,?,?,?,?,?)').run('pending-'+i,id,'bot_0001','CAREER_MILESTONE','{}',Date.now());
    const prepare=db.prepare.bind(db);let worldReads=0;db.prepare=function(sql){if(/SELECT save_json FROM worlds WHERE user_id/i.test(sql))worldReads++;return prepare(sql);};
    const pending=AI.processEvents(db,id);AI.dispose(db);await pending;db.prepare=prepare;
    assert.equal(worldReads,0,'Budget/cooldown checks must not parse a whole world per pending event');
    assert.equal(db.prepare("SELECT count(*) n FROM structured_events WHERE id LIKE 'pending-%' AND messaged_at IS NULL").get().n,200,'Deferred eligible events remain queued');
    assert.equal(db.prepare('SELECT count(*) n FROM ai_jobs').get().n,6,'Same initiation budget is enforced');
    assert.equal(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(id).save_json,before);
  }finally{AI.dispose(db);db.close();}
});
function seed(db){const id='social-test';db.prepare('INSERT INTO users(id,username,username_key,password_hash,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(id,id,id,bcrypt.hashSync('Secret-never-for-model',4),Date.now(),Date.now());writeWorld(db,id,engine().context.SAR.getUniverse(),0);AI.setPreferences(db,id,{developerMode:true,botInitiated:false});return id;}
async function waitJob(db,id,job){for(let i=0;i<200;i++){AI.kick(db);const result=AI.jobResult(db,id,job);if(['COMPLETED','FAILED'].includes(result.job.status))return result;await delay(20);}throw Error('Mock job timeout');}
test('all fifty assigned social profiles match supplied values, remain separate from combat, and use the actual Gun Score',()=>{assert.equal(PROFILES.length,50);assert.equal(new Set(PROFILES.map(p=>p.botId)).size,50);assert.equal(personalityFor('Vex').social.socialness,.94);assert.equal(personalityFor('Ghost').social.socialness,.12);assert.equal(personalityFor('Quill').social.technicality,1);assert.equal(personalityFor('Moss').social.politeness,.97);const e=engine();for(let i=0;i<300;i++)e.step();const before=JSON.stringify(e.context.SAR.getUniverse()),actual=e.context.SAR.getWeaponScores(),context=scores(e.dev.inspect().SAVE.patchState);for(const r of actual)assert.equal(r.score,context.find(s=>s.name===r.name).score);assert.equal(JSON.stringify(e.context.SAR.getUniverse()),before);});
test('durable single queue, real provider protocol, priority, repair, memory, feedback, export and offline recovery preserve gameplay',async()=>{
  let online=true,invalid=true,active=0,maxActive=0;const requests=[];
  const mock=http.createServer(async(req,res)=>{if(req.url==='/api/tags'){res.writeHead(online?200:503,{'content-type':'application/json'});res.end(JSON.stringify({models:[{name:'gpt-oss:20b',digest:'local-test-version'}]}));return;}let data='';for await(const chunk of req)data+=chunk;const payload=JSON.parse(data);requests.push(payload);active++;maxActive=Math.max(maxActive,active);await delay(30);active--;const repair=payload.messages.length>2;const raw=invalid&&!repair?'broken JSON':JSON.stringify({subject:'Test dialogue',body:'I would wait for more range data before touching the P90.',mood:'focused',category:'balance',wantsReply:true,certainty:.6});invalid=false;res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({message:{content:raw},done:true}));});await new Promise(r=>mock.listen(0,'127.0.0.1',r));
  const previous=process.env.SAR_OLLAMA_URL;process.env.SAR_OLLAMA_URL='http://127.0.0.1:'+mock.address().port;
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sar-social-')),file=path.join(dir,'social.sqlite');let db=createDatabase(file);
  try{const id=seed(db),original=db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(id).save_json;assert.equal(db.prepare('SELECT COUNT(*) AS n FROM bot_social_profiles').get().n,50);
    const connected=await AI.status(db,id);assert.equal(connected.status,'CONNECTED');
    const first=AI.lab(db,id,{botId:'bot_0001',eventType:'BALANCE_FEEDBACK',mockContext:{damageBefore:125,damageAfter:124,hp:250}}),second=AI.lab(db,id,{botId:'bot_0005',eventType:'META_OPINION',mockContext:{}});const a=await waitJob(db,id,first.jobId),b=await waitJob(db,id,second.jobId);assert.equal(a.job.status,'COMPLETED');assert.equal(b.job.status,'COMPLETED');assert.equal(maxActive,1);assert.ok(requests.some(p=>p.messages.length===4),'one actual JSON repair');assert.equal(requests[0].model,'gpt-oss:20b');assert.equal(requests[0].stream,false);assert.equal(requests[0].format.type,'object');assert.ok(!JSON.stringify(requests).includes('Secret-never-for-model'));assert.ok(!JSON.stringify(requests).includes('password_hash'));
    AI.setPreferences(db,id,{botMessages:false});const diagnostic=AI.lab(db,id,{},true);assert.equal((await waitJob(db,id,diagnostic.jobId)).job.status,'COMPLETED','manual model diagnostics work when inbox messaging is off');AI.setPreferences(db,id,{botMessages:true});
    const reply=await AI.replyToBot(db,id,'bot_0001','How is the P90 at range?');assert.equal(reply.pending,true);const received=await waitJob(db,id,reply.jobId);assert.equal(received.job.status,'COMPLETED');assert.ok(AI.messageRows(db,id).some(m=>m.source==='ollama:gpt-oss:20b'));
    const ctx=AI.botContext(db,id,'bot_0001');assert.ok(ctx.importantMemories.some(m=>m.quote==='How is the P90 at range?'));assert.ok(ctx.relationship.playerTrust>50);assert.ok(ctx.recentMessages.length<=8);assert.equal(ctx.patchPerformance,undefined);
    AI.feedback(db,id,{generationId:a.generation.id,rating:'GOOD'});const corrected={...b.generation.validatedMessage,body:'I want a larger sample before changing it.'};AI.feedback(db,id,{generationId:b.generation.id,rating:'EDIT',correctedOutput:corrected});const dataset=AI.exportTraining(db,id).trim().split('\n').map(JSON.parse);assert.equal(dataset.length,2);assert.equal(dataset[1].correctedOutput.body,corrected.body);assert.ok(dataset[1].rawModelResponse);assert.ok(dataset[1].messages.at(-1).content.includes(corrected.body));assert.equal(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(id).save_json,original,'social generation cannot mutate combat');
    online=false;await AI.probe(db,true);assert.equal((await AI.status(db,id)).status,'OLLAMA_OFFLINE');const pending=AI.lab(db,id,{botId:'bot_0001',eventType:'MAP_FEEDBACK',mockContext:{}});await delay(60);assert.equal(AI.jobResult(db,id,pending.jobId).job.status,'QUEUED');online=true;await AI.probe(db,true);assert.equal((await waitJob(db,id,pending.jobId)).job.status,'COMPLETED');
    AI.dispose(db);db.close();db=createDatabase(file);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');assert.equal(AI.exportTraining(db,id).trim().split('\n').length,2);assert.ok(AI.messageRows(db,id).length>=2);assert.equal(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(id).save_json,original);
    assert.throws(()=>AI.validateOutput({body:'broken'}));assert.throws(()=>AI.mechanicalGuard({...corrected,body:'The P90 is a one-shot headshot weapon.'},ctx));assert.throws(()=>AI.mechanicalGuard({...corrected,body:'Nova won the tournament.'},ctx));
  }finally{AI.dispose(db);db.close();await new Promise(r=>mock.close(r));if(previous===undefined)delete process.env.SAR_OLLAMA_URL;else process.env.SAR_OLLAMA_URL=previous;fs.rmSync(dir,{recursive:true,force:true});}
});
