'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {createDatabase}=require('../db.cjs'),{createServer}=require('../index.cjs'),{writeWorld}=require('../world.cjs'),{engine}=require('../../dev/simulate.cjs'),AI=require('../local-ai.cjs');
function account(db,id){const now=Date.now(),token=crypto.randomBytes(32).toString('base64url');db.prepare('INSERT INTO users(id,username,username_key,password_hash,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(id,id,id,'never-sent',now,now);db.prepare('INSERT INTO sessions(token_hash,user_id,created_at,expires_at,last_seen_at) VALUES(?,?,?,?,?)').run(crypto.createHash('sha256').update(token).digest('hex'),id,now,now+86400000,now);writeWorld(db,id,engine().context.SAR.getUniverse(),0);return 'sar_session='+token;}
test('social API enforces account ownership, developer mode, stable pagination and deletion memory',async()=>{
  const prior=process.env.SAR_OLLAMA_URL;process.env.SAR_OLLAMA_URL='http://127.0.0.1:1';const db=createDatabase(':memory:'),a=account(db,'social-a'),b=account(db,'social-b'),app=createServer({db});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
  const req=async(route,cookie=a,method='GET',body)=>{const response=await fetch(base+'/api'+route,{method,headers:{cookie,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,body:await response.json()};};
  try{
    assert.equal((await req('/ai/export')).status,403);assert.equal((await req('/ai/lab',a,'POST',{botId:'bot_0001',eventType:'MAP_FEEDBACK'})).status,403);
    assert.equal((await req('/ai/preferences',a,'PATCH',{developerMode:true,botInitiated:false})).status,200);assert.equal((await req('/ai/status')).body.preferences.developerMode,true);assert.equal((await req('/ai/status',b)).body.preferences.developerMode,false);
    const job=await req('/ai/lab',a,'POST',{botId:'bot_0001',eventType:'MAP_FEEDBACK',mockContext:{map:'Brightfield Blocks'}});assert.equal(job.status,202);assert.equal((await req('/ai/jobs/'+job.body.jobId,b)).status,404);
    const put=db.prepare("INSERT INTO messages(id,user_id,bot_id,direction,type,body,created_at,source) VALUES(?,?,'bot_0001','bot','MAP_FEEDBACK',?,?,'test')");for(let i=0;i<205;i++)put.run(crypto.randomUUID(),'social-a','stored '+i,Date.now());
    const p1=await req('/messages/thread/bot_0001'),p2=await req('/messages/thread/bot_0001?before='+p1.body.nextCursor),p3=await req('/messages/thread/bot_0001?before='+p2.body.nextCursor);assert.equal(p1.body.messages.length,100);assert.equal(p2.body.messages.length,100);assert.equal(p3.body.messages.length,5);assert.equal(p3.body.nextCursor,null);assert.equal(new Set([...p1.body.messages,...p2.body.messages,...p3.body.messages].map(m=>m.id)).size,205);assert.equal((await req('/messages/thread/bot_0001',b)).body.messages.length,0);
    const reply=await req('/messages/reply',a,'POST',{botId:'bot_0001',text:'Remember my actual P90 question.'});assert.equal(reply.status,201);assert.equal((await req('/messages/'+reply.body.messageId,b,'DELETE')).status,404);assert.equal((await req('/messages/'+reply.body.messageId,a,'DELETE')).status,200);assert.equal(AI.jobResult(db,'social-a',reply.body.jobId).job.status,'CANCELLED');assert.ok(!AI.botContext(db,'social-a','bot_0001').importantMemories.some(m=>m.quote==='Remember my actual P90 question.'));
  }finally{await new Promise(r=>app.server.close(r));db.close();if(prior===undefined)delete process.env.SAR_OLLAMA_URL;else process.env.SAR_OLLAMA_URL=prior;}
});
test('friendship evolves only from newly completed, mutually recorded team results',()=>{
  const prior=process.env.SAR_OLLAMA_URL;process.env.SAR_OLLAMA_URL='http://127.0.0.1:1';const db=createDatabase(':memory:');
  try{account(db,'team-test');const e=engine(),save=e.context.SAR.getUniverse();db.prepare('UPDATE worlds SET save_json=? WHERE user_id=?').run(JSON.stringify(save),'team-test');const old=JSON.parse(JSON.stringify(save));e.dev.endMatch(e.dev.inspect().state.matches[0],0);const next=e.context.SAR.getUniverse();writeWorld(db,'team-test',next,1);const rows=db.prepare('SELECT friendship FROM bot_relationships WHERE user_id=?').all('team-test');assert.ok(rows.some(r=>r.friendship===.2));assert.ok(rows.some(r=>r.friendship===.05));const total=rows.reduce((n,r)=>n+r.friendship,0);writeWorld(db,'team-test',next,2);assert.ok(Math.abs(db.prepare('SELECT SUM(friendship) AS n FROM bot_relationships WHERE user_id=?').get('team-test').n-total)<1e-9);assert.deepEqual(Object.values(next.bots).map(b=>b.profile),Object.values(old.bots).map(b=>b.profile));
  }finally{AI.dispose(db);db.close();if(prior===undefined)delete process.env.SAR_OLLAMA_URL;else process.env.SAR_OLLAMA_URL=prior;}
});
