'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {createDatabase}=require('../db.cjs'),{createServer}=require('../index.cjs'),{writeWorld}=require('../world.cjs'),{engine}=require('../../dev/simulate.cjs'),Circuit=require('../tournaments.cjs'),Runtime=require('../tournament-runtime.cjs'),AI=require('../local-ai.cjs');
function account(db,id){const now=Date.now(),world=engine().context.SAR.getUniverse(),token=crypto.randomBytes(32).toString('base64url');db.prepare('INSERT INTO users(id,username,username_key,password_hash,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(id,id,id,'test-only',now,now);db.prepare('INSERT INTO sessions(token_hash,user_id,created_at,expires_at,last_seen_at) VALUES(?,?,?,?,?)').run(crypto.createHash('sha256').update(token).digest('hex'),id,now,now+86400000,now);writeWorld(db,id,world,0);db.prepare('INSERT INTO ai_preferences VALUES(?,?,?)').run(id,JSON.stringify({botMessages:false}),now);return {cookie:'sar_session='+token,world};}
test('custom deletion: creator authorization, named confirmation, no official deletion, durable tombstone, invitation/job cleanup and no orphan engine',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sar-tactical-delete-')),file=path.join(dir,'fixture.sqlite');let db=createDatabase(file);
 try{const owner='fixture-owner',a=account(db,owner);account(db,'different-account');const now=Date.now(),t=Circuit.createCustom(db,owner,{name:'Deleted Fixture',startsAt:now},now),other=Circuit.createCustom(db,owner,{name:'Retained Fixture',startsAt:now+3600000},now),official=Circuit.scheduleOfficial(db,owner,a.world.seasons.current,now)[0];
  assert.throws(()=>Circuit.deleteCustom(db,'different-account',t.id,t.name),e=>e.status===404);assert.throws(()=>Circuit.deleteCustom(db,owner,t.id,'wrong name'),e=>e.status===400);assert.throws(()=>Circuit.deleteCustom(db,owner,official.id,official.name),e=>e.status===403);
  let active=Circuit.registerTeam(db,owner,t.id,{name:'Owner',participantIds:[owner]},now);for(const botId of ['bot_0001','bot_0002','bot_0003','bot_0004'])active=Circuit.inviteBot(db,owner,t.id,{teamId:active.teams[0].id,botId},now);active=Runtime.fillBots(db,owner,active,now);Circuit.startTournament(db,owner,t.id,now);Runtime.advance(db,{now,budget:1});assert.ok(Runtime.activeGames(db).some(g=>g.tournamentId===t.id));
  const before=db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(owner).save_json,event=db.prepare('SELECT id FROM structured_events WHERE user_id=? AND json_extract(payload_json,\'$.tournamentId\')=? LIMIT 1').get(owner,t.id);assert.ok(event);
  db.prepare("INSERT INTO ai_jobs(id,user_id,bot_id,event_id,kind,priority,status,request_json,created_at,updated_at) VALUES(?,?,?,?,'event',1,'RUNNING',?,?,?)").run('cancel-this-job',owner,'bot_0001',event.id,JSON.stringify({event:{tournamentId:t.id}}),now,now);
  assert.equal(Circuit.getTournament(db,owner,t.id).canDelete,true);assert.equal(Circuit.getTournament(db,owner,official.id).canDelete,false);
  const deleted=Circuit.deleteCustom(db,owner,t.id,t.name,now+1);assert.equal(deleted.deleted,true);Runtime.cancel(db,t.id);assert.equal(Runtime.activeGames(db).some(g=>g.tournamentId===t.id),false);
  for(const table of ['tournament_invites','tournament_registrations','tournament_participants'])assert.equal(db.prepare('SELECT count(*) AS n FROM '+table+' WHERE tournament_id=?').get(t.id).n,0);
  assert.equal(db.prepare('SELECT status FROM ai_jobs WHERE id=?').get('cancel-this-job').status,'CANCELLED');assert.throws(()=>Circuit.recordGame(db,owner,t.id,'ignored',{id:'late'}),e=>e.status===410);assert.equal(db.prepare('SELECT count(*) AS n FROM tournament_earnings WHERE tournament_id=?').get(t.id).n,0);assert.equal(db.prepare('SELECT save_json FROM worlds WHERE user_id=?').get(owner).save_json,before);assert.equal(Circuit.getTournament(db,owner,other.id).name,other.name);
  AI.dispose(db);db.close();db=createDatabase(file);assert.throws(()=>Circuit.getTournament(db,owner,t.id),e=>e.status===410);Runtime.advance(db,{now:now+100,budget:1});assert.equal(Runtime.activeGames(db).some(g=>g.tournamentId===t.id),false);assert.equal(Circuit.deleteCustom(db,owner,t.id,t.name).deleted,true);assert.equal(db.prepare('PRAGMA integrity_check').get().integrity_check,'ok');
 }finally{AI.dispose(db);db.close();assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(dir,{recursive:true,force:true});}
});
test('DELETE HTTP route checks the account, name and kind, and hides deleted events from calendar after repeated requests',async()=>{
 const previous=process.env.SAR_OLLAMA_URL;process.env.SAR_OLLAMA_URL='http://127.0.0.1:1';const db=createDatabase(':memory:'),a=account(db,'delete-api-a'),b=account(db,'delete-api-b'),app=createServer({db});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
 const req=async(route,method='GET',body,cookie=a.cookie)=>{const response=await fetch(base+'/api/tournaments'+route,{method,headers:{cookie,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:response.status,data:await response.json()};};
 try{const created=await req('','POST',{name:'API deletion',startsAt:Date.now()+10000}),t=created.data.tournament;assert.equal(created.status,201);assert.equal((await req('/'+t.id,'DELETE',{confirmedName:t.name},b.cookie)).status,404);assert.equal((await req('/'+t.id,'DELETE',{confirmedName:'no'})).status,400);assert.equal((await req('/'+t.id,'DELETE',{confirmedName:t.name})).status,200);assert.equal((await req('/'+t.id,'DELETE',{confirmedName:t.name})).status,200);assert.equal((await req('/'+t.id)).status,410);const list=await req('');assert.ok(!list.data.tournaments.some(e=>e.id===t.id));const official=list.data.tournaments.find(e=>e.kind==='official');assert.equal((await req('/'+official.id,'DELETE',{confirmedName:official.name})).status,403);
 }finally{await new Promise(r=>app.server.close(r));AI.dispose(db);db.close();if(previous===undefined)delete process.env.SAR_OLLAMA_URL;else process.env.SAR_OLLAMA_URL=previous;}
});
